data-driven-forms/react-forms

packages/react-form-renderer/src/form-renderer/index.js, packages/react-renderer-demo/src/editor-demo/common/doc-texts/validators.js
Add the options to do record level validation.
=> fix(form-renderer): Added record-level validation prop to form context.

.travis.yml
Fix Travis  `error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".`
Only start the script on master branch
=> Fix travis on PR branches

packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
Removes hard coded step and allows description and title to be components.
=> fix(pf4 wizard): Fixed step label and title and description.

packages/pf3-component-mapper/src/form-fields/tabs.js, packages/pf3-component-mapper/src/tests/__snapshots__/tabs.test.js.snap
=> fix(tabs): changes tabs look to normal style (instead of PF)

packages/pf3-component-mapper/src/form-fields/select/select-styles.js, packages/pf3-component-mapper/src/tests/form-fields/__snapshots__/select.test.js.snap
Fixes styling of PF3 multiselect.
(_Some strange CSS magic_)
**Before**
Chrome
Firefox
**After**
Chrome
Firefox
=> fix(PF3select): Fix styling of long multiselects

__mocks__/file-mock.js, babel.config.js, config/jest.setup.js, package.json, packages/mui-component-mapper/.babelrc, packages/mui-component-mapper/babel.config.js, packages/mui-component-mapper/package.json, packages/pf3-component-mapper/.babelrc, packages/pf3-component-mapper/babel.config.js, packages/pf3-component-mapper/package.json, packages/pf3-component-mapper/src/tests/form-fields/__snapshots__/select.test.js.snap, packages/pf4-component-mapper/.babelrc, packages/pf4-component-mapper/babel.config.js, packages/pf4-component-mapper/package.json, packages/react-form-renderer/babel.config.js, packages/react-form-renderer/package.json, packages/react-renderer-demo/package.json
- use global babel config
- use global jest config
- generate global test coverage
=> Use global babel config.

.codecov.yml, package.json
Coverage was not being collected via `test-ci` command
=> Updated codecov config

packages/react-form-renderer/package.json, packages/react-form-renderer/src/form-renderer/index.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-information.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
Ads focus on first invalid field on submit. Uses this decorator: https://github.com/final-form/final-form-focus
=> feat(All): Focus first error field on failed submit.

packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/__snapshots__/tabs.test.js.snap, packages/react-form-renderer/src/index.js
Expose schema parsers to users.
=> fix(react-renderer): Exposed schema parsers.

packages/pf3-component-mapper/src/form-fields/select/index.js, packages/pf3-component-mapper/src/tests/form-fields/__snapshots__/select.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields/select.test.js, packages/pf4-component-mapper/demo/demo-schemas/sandbox.js, packages/pf4-component-mapper/package.json, packages/pf4-component-mapper/src/form-fields/component-mapper.js, packages/pf4-component-mapper/src/form-fields/form-fields.js, packages/pf4-component-mapper/src/form-fields/select/select-styles.js, packages/pf4-component-mapper/src/form-fields/select/select-styles.scss, packages/pf4-component-mapper/src/form-fields/select/select.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/form-fields.test.js, packages/pf4-component-mapper/src/tests/select/select.test.js, packages/react-renderer-demo/demo/index.html, packages/react-renderer-demo/src/editor-demo/common/examples-definitions.js, shared/select-helper.js
Ads styled version of react select for PF4
=> feat(pf4): select component.

packages/pf4-component-mapper/src/form-fields/form-fields.js, packages/pf4-component-mapper/src/form-fields/multiple-choice-list.js
PF4 checkbox changed their API
=> fix(pf4): Fix pf4 checkbox.

packages/pf4-component-mapper/src/index.js
Forgot to export the component once it was done.
=> fix(pf4): Exposed select as raw component.

package.json, packages/mui-component-mapper/config/webpack.config.js, packages/pf3-component-mapper/config/webpack.config.js, packages/pf4-component-mapper/config/webpack.config.js, packages/react-form-renderer/config/webpack.config.js, packages/react-renderer-demo/config/webpack.config.js, packages/react-renderer-demo/package.json
Adds better minification process.
- fixes build bundle for mui mapper
- removes component names mangling
=> Added webpack terser plugin minification.

packages/react-form-renderer/src/form-renderer/helpers.js
Compose validators was stripping the second final form validator argument.
=> fix(renderer): Added form values as second argument to validators.

packages/react-renderer-demo/src/editor-demo/common/doc-texts/component-api.js, packages/react-renderer-demo/src/editor-demo/common/documenation-pages.js, packages/react-renderer-demo/src/editor-demo/docs-components/component-api/component-api.md, packages/react-renderer-demo/src/editor-demo/docs-components/component-api/exampleLink.js
Adds documentation for standard components API.
closes https://github.com/data-driven-forms/react-forms/issues/47
=> Adds Component API doc page

packages/pf3-component-mapper/src/form-fields/layout-components.js, packages/react-form-renderer/demo/form-fields-mapper.js, packages/react-form-renderer/demo/index.js, packages/react-form-renderer/demo/layout-mapper.js, packages/react-form-renderer/src/form-renderer/form-controls.js, packages/react-form-renderer/src/form-renderer/index.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-controls.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-information.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/form-controls.test.js, packages/react-form-renderer/src/tests/form-renderer/form-renderer.test.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-renderer-demo/src/editor-demo/common/component/raw-component.js, packages/react-renderer-demo/src/editor-demo/common/doc-texts/form-controls.js, packages/react-renderer-demo/src/editor-demo/common/documenation-pages.js, packages/react-renderer-demo/src/editor-demo/docs-components/form-controls.md, packages/react-renderer-demo/src/editor-demo/docs-components/form-controls/custom-buttons.js
fixes: #49 
- allows defining custom components for form controls
- added submit disable when async submit function is in progress.
=> feat(renderer): Added option to pass custom component for form buttons.

packages/pf4-component-mapper/package.json, packages/pf4-component-mapper/src/form-fields/form-fields.js, packages/pf4-component-mapper/src/form-fields/select/select-styles.js, packages/pf4-component-mapper/src/form-fields/select/select.js, packages/pf4-component-mapper/src/form-fields/tabs.js, packages/react-renderer-demo/src/editor-demo/common/example-common.js, packages/react-renderer-demo/src/editor-demo/common/examples-texts/tabs.js, packages/react-renderer-demo/src/editor-demo/demo-missing-fields/mui-wizzard/step-buttons.js, packages/react-renderer-demo/src/editor-demo/pages/form-renderer-page.js
closes: #41 
Clean up component mapper and docs to prop type remove console errors.
=> Remove console errors in demo

packages/react-renderer-demo/src/editor-demo/common/component/code-editor.js, packages/react-renderer-demo/src/editor-demo/common/component/raw-component.js, packages/react-renderer-demo/src/editor-demo/common/example-common.js, packages/react-renderer-demo/src/editor-demo/common/md-helper/index.js, packages/react-renderer-demo/src/editor-demo/pages/form-renderer-page.js
closes: #56 
Using the same code editor on every docs page.
=> Deduped ace-editor usage.

packages/react-renderer-demo/src/editor-demo/docs-components/component-api/component-api.md
=> Fix typo in link

packages/react-renderer-demo/src/common/md-helper/index.js, packages/react-renderer-demo/src/common/md-helper/mdx-components.js
Md anchor is no longer hidden below the top navbar.
fix found at: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header
=> Fixed md header anchor offset.

packages/react-renderer-demo/src/common/doc-page.js, packages/react-renderer-demo/src/common/doc-texts/component-mapping.js, packages/react-renderer-demo/src/common/helpers/list-of-content.js, packages/react-renderer-demo/src/common/md-helper/index.js, packages/react-renderer-demo/src/common/md-helper/mdx-components.js
=> Reactive content nav

packages/react-renderer-demo/src/common/examples-nav.js, packages/react-renderer-demo/src/common/menu-renderer/mapper.js, packages/react-renderer-demo/src/common/menu-renderer/menu-renderer.js, packages/react-renderer-demo/src/common/menu-renderer/schema-demo.js, packages/react-renderer-demo/src/common/nav-styles.js
closes https://github.com/data-driven-forms/react-forms/issues/81
Add a menu search button.
And actually add a little menu renderer component.
=> Add menu renderer to demo with search

packages/pf4-component-mapper/demo/demo-schemas/sandbox.js, packages/pf4-component-mapper/src/form-fields/select/dropdown-indicator.js, packages/pf4-component-mapper/src/form-fields/select/select-styles.scss, packages/pf4-component-mapper/src/form-fields/select/select.js, packages/pf4-component-mapper/src/tests/select/select.test.js, packages/react-form-renderer/src/form-renderer/enhanced-on-change.js
Load options is called every time search input is changed. Options are cumulatively cached into component state.
=> fix(pf4): Added async filtering to pf4 async select.

packages/react-renderer-demo/src/common/menu-renderer/mapper.js, packages/react-renderer-demo/src/common/menu-renderer/menu-renderer.js
part of https://github.com/data-driven-forms/react-forms/issues/84
- Menu section are getting unique ID when they are closed/opened, so they are always correctly rendered when user is using the search function
- Currently selected item is always selected
- Currently selected menu section is open by default
=> Search enhancement

packages/react-form-renderer/src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-renderer-demo/src/common/doc-texts/renderer-api.js, packages/react-renderer-demo/src/common/documenation-pages.js, packages/react-renderer-demo/src/docs-components/renderer-api/renderer-api.md
closes https://github.com/data-driven-forms/react-forms/issues/37
=> Add renderer API doc

package.json, packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js, packages/pf4-component-mapper/src/form-fields/wizard/wizard.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
Allow to use nested fields in PF4 Wizard
TODO:
=> Allow to use nested fields in PF4 Wizard

packages/react-renderer-demo/src/common/examples-nav.js, packages/react-renderer-demo/src/common/menu-renderer/menu-renderer.js, packages/react-renderer-demo/src/layout.js
Focus on search button when menu is opened
=> Focus search button when menu is opened

package.json, packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
flat is causing errors in node environment, it fails tests in consumers applications. So I replaced it by lodash, it is already there.
=> Use lodash for flat in PF4 wizard

packages/react-renderer-demo/src/common/component/renderer-doc-page.js
Also adds scroll to top when switching between md pages.
=> Fixed lazy loaded components anchor scrolling.

packages/react-renderer-demo/src/layout.js
closes https://github.com/data-driven-forms/react-forms/issues/94
=> Set closed menu only on landing page

packages/mui-component-mapper/src/form-fields/form-fields.js, packages/mui-component-mapper/src/form-fields/radio.js, packages/pf3-component-mapper/src/form-fields/form-fields.js, packages/pf3-component-mapper/src/form-fields/radio.js, packages/pf3-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/form-fields/form-fields.js, packages/pf4-component-mapper/src/form-fields/radio.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
Added default prop options of empty array so the component does not throw an error. Has now same behavior like checkbox or select.
=> fix(Radio): Added default prop options to radio buttons.

README.md, packages/react-renderer-demo/src/components/footer.js, packages/react-renderer-demo/src/pages/landing-page.js
Fixes readme and demo inconsistencies
=> Fixes readme and demo inconsistencies

packages/pf4-component-mapper/demo/demo-schemas/sandbox.js, packages/pf4-component-mapper/package.json, packages/pf4-component-mapper/src/form-fields/form-fields.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/form-fields.test.js, packages/react-renderer-demo/src/common/examples-definitions.js, packages/react-renderer-demo/src/docs-components/component-api.md
fixes https://github.com/data-driven-forms/react-forms/issues/99
- adds on/off Text variant for PF4 switch (and unifies it with PF3)
- fixes default label (until PF fixes it themselves)
- updates docs for Switch
=> Fix pf4switch

packages/react-renderer-demo/package.json, packages/react-renderer-demo/src/App.js, packages/react-renderer-demo/src/common/component/connected-links.js, packages/react-renderer-demo/src/common/component/renderer-doc-page.js, packages/react-renderer-demo/src/common/documenation-pages.js, packages/react-renderer-demo/src/common/example-common.js, packages/react-renderer-demo/src/common/examples-definitions.js, packages/react-renderer-demo/src/common/menu-renderer/find-connected-links.js, packages/react-renderer-demo/src/common/menu-renderer/menu-context.js, packages/react-renderer-demo/src/common/menu-renderer/schema-demo.js, packages/react-renderer-demo/src/common/other-pages.js, packages/react-renderer-demo/src/layout.js
=> Added prev/next links to doc pages.

packages/react-form-renderer/src/form-renderer/index.js, packages/react-renderer-demo/src/docs-components/renderer-api.md
Allows to add/override subscription
=> fix(renderer): Allow to pass custom subscription

packages/react-renderer-demo/src/docs-components/field-provider.md
closes https://github.com/data-driven-forms/react-forms/issues/137
=> Fix wrong link in the field-provider page

packages/react-renderer-demo/src/docs-components/component-api.md
closes https://github.com/data-driven-forms/react-forms/issues/138
Adds `initialValue` description to compontents-api
=> Add initialValue to component api page

packages/mui-component-mapper/package.json, packages/mui-component-mapper/src/form-fields/component-mapper.js, packages/mui-component-mapper/src/form-fields/form-fields.js, packages/mui-component-mapper/src/form-fields/plain-text.js, packages/pf3-component-mapper/src/form-fields/component-mapper.js, packages/pf3-component-mapper/src/form-fields/form-fields.js, packages/pf3-component-mapper/src/form-fields/plain-text.js, packages/pf4-component-mapper/src/form-fields/component-mapper.js, packages/pf4-component-mapper/src/form-fields/form-fields.js, packages/pf4-component-mapper/src/form-fields/plain-text.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/react-form-renderer/src/constants/index.js, packages/react-renderer-demo/src/common/example-common.js, packages/react-renderer-demo/src/common/examples-definitions.js
=> Plain text component

packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/react-renderer-demo/next.config.js, packages/react-renderer-demo/pages/_app.js, packages/react-renderer-demo/pages/_document.js, packages/react-renderer-demo/pages/component-example.js, packages/react-renderer-demo/pages/index.js, packages/react-renderer-demo/pages/live-editor.js, packages/react-renderer-demo/pages/renderer/component-api.md, packages/react-renderer-demo/pages/show-case.js, packages/react-renderer-demo/src/components/navigation/examples-definitions.js, packages/react-renderer-demo/src/components/navigation/examples-texts/custom-component.js, packages/react-renderer-demo/src/components/navigation/examples-texts/generic-mui-component.js, packages/react-renderer-demo/src/components/navigation/examples-texts/tabs.js, packages/react-renderer-demo/src/components/navigation/examples-texts/wizard.js, packages/react-renderer-demo/src/components/navigation/mapper.js, packages/react-renderer-demo/src/components/navigation/schema.js, packages/react-renderer-demo/src/doc-components/pf3-wizard.md, packages/react-renderer-demo/src/doc-components/pf4-wizard.md, packages/react-renderer-demo/src/doc-components/wizard.md
Convert **Component Definitions** to SSR
Other changes:
- Add alias for `@docs/components`
- Add missing link for FontAwesome icons
=> Convert Component Definitions to SSR

packages/react-form-renderer/demo/sandbox.js, packages/react-form-renderer/src/form-renderer/render-form.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/form-renderer.test.js, packages/react-renderer-demo/src/docs-components/component-api.md
closes: #128
cc @skateman 
Adds `hideField` prop
=> Field visibility

README.md, packages/mui-component-mapper/README.md, packages/pf4-component-mapper/README.md, packages/react-form-renderer/README.md, packages/react-renderer-demo/README.md, packages/react-renderer-demo/src/common/documenation-pages.js, packages/react-renderer-demo/src/docs-components/development-setup.md
closes https://github.com/data-driven-forms/react-forms/issues/142
- Adds `README` for each repo with customized content (most of it is copy/paste however)
- Adds `Development setup` to online documentation
=> Add Development setup

packages/react-renderer-demo/src/docs-components/field-array.md
Notify that only `FIELD_ARRAY` get `FieldArrayProvider`
=> Notify that only FIELD_ARRAY gets FieldArrayProvider

packages/react-renderer-demo/src/docs-components/pf4-wizard.md
Missed to update PF4 wizard docs during the initial review process
=> Fix PF4 Wizard doc substep > substepOf

packages/pf3-component-mapper/demo/demo-schemas/sandbox.js, packages/pf3-component-mapper/src/form-fields/date-time-picker/date-time-picker.js
closes #132
Added little different text to date-time picker default input placeholder.
=> fix(pf3): Date time picker placeholder.

packages/react-renderer-demo/src/common/examples-definitions.js, packages/react-renderer-demo/src/common/examples-texts/select.js, packages/react-renderer-demo/src/docs-components/pf3-select.md, packages/react-renderer-demo/src/docs-components/pf4-select.md
- add mising documentation for async selects (https://github.com/data-driven-forms/react-forms/issues/10)
=> Add AsyncSelect docs

packages/react-form-renderer/src/tests/validators/validators.test.js, packages/react-form-renderer/src/validators/index.js
=> fix(renderer): data-type validation for arrays.

packages/pf3-component-mapper/demo/index.js, packages/pf3-component-mapper/src/form-fields/form-fields.js
closes #177 
- fixed initial value not being propagated to pf3 date picker.
=> fix(pf3): fixed initial value for pf3 date-picker.

packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js, packages/pf4-component-mapper/demo/index.js, packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js, packages/pf4-component-mapper/src/form-fields/wizard/wizard.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
Fixes predicting steps and disabling the nav, when the nextstep is a function.
- plus refactors tests and adds a few new use cases
Todo:
=> fix(pf4wizard): fix predicting steps for func nextStep

packages/pf3-component-mapper/src/form-fields/date-time-picker/date-time-picker.js, packages/pf3-component-mapper/src/form-fields/form-fields.js, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/date-time-picker.test.js
fixes: https://github.com/skateman/ddf-editor/issues/2
If field is pristine internal state is overridden with props value
=> fix(pf3): fixed date picker initialization.

packages/react-renderer-demo/package.json, packages/react-renderer-demo/src/app/package.json
=> Fix package json next deploy

packages/pf3-component-mapper/src/tests/__snapshots__/tabs.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/__snapshots__/year-selector.test.js.snap, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/__snapshots__/tabs.test.js.snap, packages/react-form-renderer/src/form-renderer/form-controls.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-controls.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/form-controls.test.js, packages/react-renderer-demo/src/docs-components/renderer-api.md
onCancel now receives `values`
=> fix(renderer): onCancel receives form values

packages/react-renderer-demo/src/app/README.md
Only updates readme for demo, there are many notes which are not applicable to demo.
=> Update repo demo readme for nextjs

packages/pf4-component-mapper/src/icons/add-circle-o-icon.js, packages/pf4-component-mapper/src/icons/caret-down-icon.js, packages/pf4-component-mapper/src/icons/check-icon.js, packages/pf4-component-mapper/src/icons/circle-notch-icon.js, packages/pf4-component-mapper/src/icons/close-icon.js, packages/pf4-component-mapper/src/icons/times-circle-icon.js
vertical-align to verticalAlign
no semicolons
=> Fix verticalAlign PF4 icons

packages/react-renderer-demo/src/app/src/doc-components/component-mapper/form-fields-mapper.js
Create component mapper example needs to import css
=> Import styles to create component mapper demo

packages/pf3-component-mapper/src/form-fields/date-time-picker/date-time-picker.js, packages/pf3-component-mapper/src/form-fields/date-time-picker/picker-input.js, packages/react-renderer-demo/src/app/pages/renderer/component-api.md
=> fix(pf3): date-time picker input format.

package.json, packages/react-renderer-demo/src/app/src/components/layout.js, packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js
Added algolia requirements https://community.algolia.com/docsearch/required-configuration.html
=> Adjusted doc layout to comply with algolia doc-search.

packages/react-renderer-demo/package.json, packages/react-renderer-demo/src/app/src/helpers/list-of-contents.js, yarn.lock
=> Use sticky table of contents in docs

packages/pf4-component-mapper/demo/index.html, packages/pf4-component-mapper/src/form-fields/layout-components-styles.scss, packages/pf4-component-mapper/src/form-fields/layout-components.js, packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap, packages/pf4-component-mapper/src/tests/layout-components.test.js
- fixes pf4 for buttons spacing from 24px to 16px to match current version of PF
cc @panspagetka
=> fix(pf4): updated form buttons to fix spacing.

packages/react-renderer-demo/src/app/pages/renderer/field-array.md
=> Add table of contents to field array

packages/react-renderer-demo/src/app/pages/live-editor.js
=> Remove tag from all schemas

packages/react-form-renderer/src/tests/validators/validators.test.js, packages/react-form-renderer/src/validators/index.js
=> Ignore empty values length validator

packages/react-renderer-demo/src/app/.eslintrc, packages/react-renderer-demo/src/app/package.json, packages/react-renderer-demo/src/app/src/components/layout.js, packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js, packages/react-renderer-demo/src/app/src/components/mdx/share-button.js, packages/react-renderer-demo/src/app/src/helpers/list-of-contents.js
- Moved the docsearch class name to correct element
- added links to anchors to enable site crawling
=> Fixed demo links to enable crawlers.

packages/react-renderer-demo/src/app/pages/index.js, packages/react-renderer-demo/src/app/src/components/common/example-link.js, packages/react-renderer-demo/src/app/src/components/mdx/share-button.js, packages/react-renderer-demo/src/app/src/doc-components/component-mapper/form-fields-mapper.js, packages/react-renderer-demo/src/app/src/doc-components/component-mapper/layout-mapper.js, packages/react-renderer-demo/src/app/src/doc-components/field-array/form-fields-mapper.js, packages/react-renderer-demo/src/app/src/helpers/list-of-contents.js
- added href on get started button
- added href on to example buttons
- fixed potential memory leak on list of contents scrolling
- removed invalid nesting of `a` in share button
=> Fixed missing HREF on rest of anchor tags.

packages/react-form-renderer/src/form-renderer/field-provider.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-renderer-demo/src/app/pages/renderer/initialize-mount.md, packages/react-renderer-demo/src/app/src/components/navigation/documentation-pages.js, packages/react-renderer-demo/src/app/src/doc-components/initialize-mount.js
closes #236 
Introduces an option how to re-initialize initial value of a form field, when the form is mounted (remounted.)
TODO
=> feat(renderer): introduce initializeOnMount

package.json, packages/react-renderer-demo/src/app/pages/_document.js, packages/react-renderer-demo/src/app/src/components/docsearch.js, packages/react-renderer-demo/src/app/src/components/layout.js, yarn.lock
Enabled docs searching
possibly solves #95
=> Added doc search input to documentation.

packages/react-renderer-demo/src/app/package.json, packages/react-renderer-demo/src/app/pages/_document.js, packages/react-renderer-demo/src/app/src/components/docsearch.js, packages/react-renderer-demo/src/app/src/components/layout.js, yarn.lock
- fixed demo doc search initialization and full page refresh
=> Fixed doc search in prod.

packages/react-renderer-demo/src/app/pages/renderer/component-api.md, packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js
=> Fix styling for anchors

packages/react-renderer-demo/src/app/src/components/common/example-link.js
=> Fix link to example

packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js, packages/react-renderer-demo/src/app/src/helpers/list-of-contents.js
=> Fix headers again

packages/react-form-renderer/src/tests/validators/validators.test.js, packages/react-form-renderer/src/validators/validator-mapper.js
=> fix(renderer): allow URL validator to pass custom messages

packages/react-renderer-demo/src/app/pages/renderer/field-provider.md
=> Fix typo in field provider

packages/pf3-component-mapper/demo/demo-schemas/sandbox.js, packages/pf3-component-mapper/src/form-fields/form-fields.js, packages/pf3-component-mapper/src/form-fields/multiple-choice-list.js, packages/pf3-component-mapper/src/tests/__snapshots__/multiple-choice-list.test.js.snap, packages/pf3-component-mapper/src/tests/multiple-choice-list.test.js
=> fix(pf3 multiple checkboxes): allow helperText and description

packages/react-renderer-demo/src/app/src/components/common/raw-component.js, packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js
Adds additional classNames used in Algolia config for
- table
- raw component
- code
=> Add additional classNames for algolia

packages/react-renderer-demo/src/app/pages/component-example/checkbox-multiple.js, packages/react-renderer-demo/src/app/pages/component-example/checkbox.js, packages/react-renderer-demo/src/app/pages/component-example/date-picker.js, packages/react-renderer-demo/src/app/pages/component-example/plain-text.js, packages/react-renderer-demo/src/app/pages/component-example/radio.js, packages/react-renderer-demo/src/app/pages/component-example/select-field.js, packages/react-renderer-demo/src/app/pages/component-example/sub-form.js, packages/react-renderer-demo/src/app/pages/component-example/switch-field.js, packages/react-renderer-demo/src/app/pages/component-example/tabs.js, packages/react-renderer-demo/src/app/pages/component-example/text-field.js, packages/react-renderer-demo/src/app/pages/component-example/textarea-field.js, packages/react-renderer-demo/src/app/pages/component-example/time-picker.js, packages/react-renderer-demo/src/app/pages/component-example/wizard.js, packages/react-renderer-demo/src/app/src/components/common/connected-links.js, packages/react-renderer-demo/src/app/src/components/common/example-link.js, packages/react-renderer-demo/src/app/src/components/component-example.js, packages/react-renderer-demo/src/app/src/components/navigation/examples-definitions.js
Use full routing instead of params in component examples to enable it for docs indexing.
=> Split component example into separate files.

packages/pf4-component-mapper/src/form-fields/layout-components.js, packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap, packages/pf4-component-mapper/src/tests/layout-components.test.js
Classic `disabled` vs `isDisabled` problem :nerd_face:
=> fix(pf4): allow to use disableSubmit

packages/react-form-renderer/demo/index.js, packages/react-form-renderer/demo/sandbox.js, packages/react-form-renderer/src/form-renderer/condition.js, packages/react-form-renderer/src/form-renderer/render-form.js, packages/react-form-renderer/src/parsers/default-schema-validator.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-renderer-demo/src/app/pages/renderer/condition.md
=> Multi field validation

packages/common/src/wizard/enter-handler.js, packages/common/src/wizard/select-next.js, packages/pf3-component-mapper/demo/index.js, packages/pf3-component-mapper/src/form-fields/form-fields.js, packages/pf3-component-mapper/src/form-fields/switch-field.js, packages/pf3-component-mapper/src/form-fields/wizzard/wizzard.js, packages/pf3-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap, packages/pf3-component-mapper/src/tests/switch-field.test.js, packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js, packages/pf4-component-mapper/src/form-fields/wizard/wizard.js, packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js, packages/react-form-renderer/src/form-renderer/form-controls.js, packages/react-form-renderer/src/form-renderer/index.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-controls.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-information.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
Allow to use `enter` to submit the form
TODO LIST
=> Form submit by pressing enter

packages/common/src/multiple-choice-list.js, packages/common/src/prop-types-templates.js, packages/mui-component-mapper/src/form-fields/multiple-choice-list.js, packages/mui-component-mapper/src/tests/multiple-choice-list.test.js, packages/pf3-component-mapper/src/form-fields/multiple-choice-list.js, packages/pf3-component-mapper/src/tests/__snapshots__/multiple-choice-list.test.js.snap, packages/pf4-component-mapper/src/form-fields/multiple-choice-list.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
Creates common multipleChoiceList component
Converts:
=> Common multiple choice list

packages/react-renderer-demo/src/app/pages/component-example/checkbox-multiple.md, packages/react-renderer-demo/src/app/pages/component-example/checkbox.md, packages/react-renderer-demo/src/app/pages/component-example/date-picker.md, packages/react-renderer-demo/src/app/pages/component-example/plain-text.md, packages/react-renderer-demo/src/app/pages/component-example/radio.md, packages/react-renderer-demo/src/app/pages/component-example/select-field.md, packages/react-renderer-demo/src/app/pages/component-example/sub-form.md, packages/react-renderer-demo/src/app/pages/component-example/switch-field.md, packages/react-renderer-demo/src/app/pages/component-example/tabs.md, packages/react-renderer-demo/src/app/pages/component-example/text-field.md, packages/react-renderer-demo/src/app/pages/component-example/textarea-field.md, packages/react-renderer-demo/src/app/pages/component-example/time-picker.md, packages/react-renderer-demo/src/app/pages/component-example/wizard.md, packages/react-renderer-demo/src/app/src/components/component-example-text.js, packages/react-renderer-demo/src/app/src/components/component-example.js, packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js, packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/tabs.js, packages/react-renderer-demo/src/app/src/doc-components/pf3-select.md, packages/react-renderer-demo/src/app/src/doc-components/pf3-wizard.md, packages/react-renderer-demo/src/app/src/doc-components/pf4-select.md, packages/react-renderer-demo/src/app/src/doc-components/pf4-wizard.md, packages/react-renderer-demo/src/app/src/doc-components/wizard.md
- inactive are hidden
- to support algolia
- there is only one header in the documentation of each component's implementation
=> Render all texts on component example

packages/react-renderer-demo/src/app/src/components/docsearch.js
It works! :dancer: :balloon: :tada:
=> Include query in algolia for component examples

package.json, yarn.lock
Brings my changes from https://github.com/karelhala/commit-analyzer-wildcard/pull/15
=> Updated wildcard-release-notes to latest

packages/react-renderer-demo/src/app/pages/live-editor.js
The editor wasn't working because there were undeclared variables used.
Also I changed `key` to `name`
Added breakpoints for smaller screens
Limited max lines of the editor, so user can see all of the code next to the form
=> Fix demo editor

packages/pf4-component-mapper/src/form-fields/select/select.js, packages/pf4-component-mapper/src/tests/select/select.test.js
This PR allow to change `options`, `loadOptions` in runtime.
However, in the future, we should move this feature to the common select to avoid any more inconsistencies between mappers.
=> fix(pf4): allow to update options, loadOptions props

packages/mui-component-mapper/demo/demo-schemas/sandbox.js, packages/mui-component-mapper/src/form-fields/tabs.js, packages/mui-component-mapper/src/tests/subform.test.js, packages/mui-component-mapper/src/tests/tabs.test.js, packages/pf3-component-mapper/demo/demo-schemas/sandbox.js, packages/pf3-component-mapper/src/form-fields/tabs.js, packages/pf3-component-mapper/src/tests/__snapshots__/tabs.test.js.snap, packages/pf3-component-mapper/src/tests/tabs.test.js, packages/pf4-component-mapper/demo/demo-schemas/sandbox.js, packages/pf4-component-mapper/src/form-fields/multiple-choice-list.js, packages/pf4-component-mapper/src/form-fields/tabs.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/sub-form.test.js, packages/pf4-component-mapper/src/tests/tabs.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js, packages/react-form-renderer/src/demo-schemas/miq-schemas/output.js, packages/react-form-renderer/src/parsers/default-schema-validator.js, packages/react-form-renderer/src/parsers/miq-parser/miq-parser.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap, packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js, packages/react-renderer-demo/src/app/pages/renderer/unmounting.md, packages/react-renderer-demo/src/app/src/components/navigation/examples-definitions.js
=> Check if the field has name set, not title or key

packages/react-form-renderer/demo/sandbox.js, packages/react-form-renderer/src/parsers/mozilla-parser/mozilla-helpers.js, packages/react-form-renderer/src/tests/parsers/expected-parser-results.js, packages/react-form-renderer/src/tests/validators/validators.test.js, packages/react-form-renderer/src/validators/validator-mapper.js
=> [V2] fix(renderer): remove treshold warning and option

packages/mui-component-mapper/src/form-fields/form-fields.js, packages/mui-component-mapper/src/form-fields/tabs.js, packages/mui-component-mapper/src/form-fields/tabs.scss, packages/mui-component-mapper/src/tests/tabs.test.js
=> Validate MUI hidden tabs

package.json, packages/common/src/multiple-choice-list.js, packages/mui-component-mapper/src/components/checkbox.js, packages/mui-component-mapper/src/tests/form-fields.test.js, packages/mui-component-mapper/src/tests/multiple-choice-list.test.js, packages/pf3-component-mapper/demo/demo-schemas/sandbox.js, packages/pf3-component-mapper/src/components/checkbox.js, packages/pf3-component-mapper/src/components/wizard/step-buttons.js, packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields.test.js, packages/pf3-component-mapper/src/tests/multiple-choice-list.test.js, packages/pf4-component-mapper/src/common/multiple-choice-list.js, packages/pf4-component-mapper/src/components/checkbox.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/__snapshots__/form-template-common.test.js.snap, packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap, packages/pf4-component-mapper/src/tests/form-fields.test.js, packages/pf4-component-mapper/src/tests/form-template-common.test.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/react-form-renderer/package.json, packages/react-form-renderer/src/components/field-provider.js, packages/react-form-renderer/src/components/renderer-context.js, packages/react-form-renderer/src/form-renderer/field-wrapper.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/data-types.test.js, packages/react-form-renderer/src/tests/form-renderer/field-wrapper.test.js, packages/react-form-renderer/src/tests/form-renderer/form-renderer.test.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, yarn.lock
- updates react final form
- temporarily disabled multiple-choice list (buggy)
=> Upgrade final form

packages/pf4-component-mapper/src/components/field-array.js, packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/react-form-renderer/src/components/field-array.js, packages/react-form-renderer/src/form-renderer/field-wrapper.js, packages/react-form-renderer/src/index.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap
```jsx
import { FieldArray } from '@data-driven-forms/react-form-renderer';
```
=> Export field array instead of using a prop

packages/react-form-renderer/src/tests/validators/validators.test.js, packages/react-form-renderer/src/validators/index.js, packages/react-renderer-demo/src/app/src/doc-components/validators/pattern-validator.js
Allows to add flags to support string patterns
=> fix(renderer): add flags for pattern validator

packages/pf3-component-mapper/demo/demo-schemas/sandbox.js, packages/pf3-component-mapper/src/form-fields/button.js, packages/pf3-component-mapper/src/form-fields/component-mapper.js, packages/pf3-component-mapper/src/form-fields/form-fields.js, packages/pf3-component-mapper/src/form-fields/input-group-fields.js, packages/pf3-component-mapper/src/form-fields/plain-text.js, packages/pf3-component-mapper/src/form-fields/wizzard/button.scss, packages/pf3-component-mapper/src/form-fields/wizzard/step-buttons.js, packages/pf3-component-mapper/src/tests/__snapshots__/input-addon.test.js.snap, packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap, packages/pf3-component-mapper/src/tests/component-mapper.test.js, packages/pf3-component-mapper/src/tests/input-addon.test.js, packages/react-form-renderer/src/constants/index.js
Added the support for PF3 input addon before and after.
The schema is the following:
```js
fields: [{
name: 'text_box_21',
label: 'Text Box With Input Addon',
title: 'Text Box With Input Addon',
component: components.TEXT_FIELD,
inputAddon: {
before: {
fields: [
{
component: components.INPUT_ADDON_BUTTON_GROUP,
name: 'i-a-g-2',
fields: [
{
component: components.BUTTON,
label: 'Set 1',
name: 'set1',
onClick: () => console.log('fooo'),
},
{
component: components.BUTTON,
label: 'Set 2',
name: 'set2',
onClick: () => console.log('foo2o'),
},
],
},
],
},
after: {
fields: [
{
component: components.INPUT_ADDON_GROUP,
name: 'i-a-g-2',
fields: [
{
component: components.PLAIN_TEXT,
label: '-',
name: 'name1',
variant: 'span',
},
],
},
{
component: components.INPUT_ADDON_BUTTON_GROUP,
name: 'i-a-g-3', …
```
=> Added inputAddon support to PF3 text and textarea input fields

packages/pf4-component-mapper/demo/demo-schemas/superschema.js, packages/pf4-component-mapper/demo/index.js, packages/pf4-component-mapper/src/common/is-required.js, packages/pf4-component-mapper/src/components/checkbox.js, packages/pf4-component-mapper/src/components/switch.js, packages/pf4-component-mapper/src/tests/form-fields.test.js
+ tests as well
+ super schema to demo
=> [V2] pf4: Add isRequired to checkbox and switch

packages/react-form-renderer/demo/form-fields-mapper.js, packages/react-form-renderer/demo/index.js, packages/react-form-renderer/demo/sandbox.js, packages/react-form-renderer/src/components/form-renderer.js, packages/react-form-renderer/src/hooks/use-field-api.js, packages/react-form-renderer/src/parsers/default-schema-validator.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap, packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
```jsx
// Returns a function
const actionMapper = {
loadData: (data) => () => new Promise((resolve) => setTimeout(() => resolve({ custom: 'ererewr', ...data }), 1700))
}
title: 'Testing dialog',
description: 'Description of testing Dialog',
fields: [
{
name: 'dataShower',
component: 'dataShower',
// default
loadOptions: () => new Promise((resolve) => setTimeout(() => resolve({ custom: 'data' }), 1500))
},
{
name: 'dataShower',
component: 'dataShower',
// use of actions
actions: {
loadOptions: ['loadData', {x: 'y'}]
}
}
]
};
const App = () => (
<div>
<FormRenderer
...
schema={schema}
actionMapper={actionMapper}
/>
</div>
)
```
@Hyperkid123 What do you think?
=> [V2] Action mapper proposal

packages/react-form-renderer/src/hooks/use-field-api.js
Rest of tests will pass after #342 
Unmount (mount) effects needs empty array in useEffect
=> [V2] fix(renderer): clearOnUnmount only on unmounting

packages/react-form-renderer/src/components/form-renderer.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-renderer-demo/src/app/pages/live-editor.js, packages/react-renderer-demo/src/app/pages/renderer/form-controls.md, packages/react-renderer-demo/src/app/src/components/component-example.js, packages/react-renderer-demo/src/app/src/components/navigation/mapper.js, packages/react-renderer-demo/src/app/src/components/navigation/menu-renderer.js, packages/react-renderer-demo/src/app/src/doc-components/cleared-value.js, packages/react-renderer-demo/src/app/src/doc-components/component-mapper/form-fields-mapper.js, packages/react-renderer-demo/src/app/src/doc-components/custom-buttons.js, packages/react-renderer-demo/src/app/src/doc-components/field-array/pf4-demo.js, packages/react-renderer-demo/src/app/src/doc-components/get-started/get-started.js, packages/react-renderer-demo/src/app/src/doc-components/initialize-mount.js, packages/react-renderer-demo/src/app/src/doc-components/validators/async-validator.js, packages/react-renderer-demo/src/app/src/doc-components/validators/custom-function.js, packages/react-renderer-demo/src/app/src/doc-components/validators/global-message.js, packages/react-renderer-demo/src/app/src/doc-components/validators/length-validators.js, packages/react-renderer-demo/src/app/src/doc-components/validators/number-validator.js, packages/react-renderer-demo/src/app/src/doc-components/validators/pattern-validator.js, packages/react-renderer-demo/src/app/src/doc-components/validators/record-level-validation.js, packages/react-renderer-demo/src/app/src/doc-components/validators/required-validator.js, packages/react-renderer-demo/src/app/src/doc-components/validators/url-validator.js
~~wating for https://github.com/data-driven-forms/react-forms/pull/352~~
=> [V2]Sync demo with v2

packages/react-form-renderer/src/form-renderer/field-provider.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
`clearOnUnmount` should set value to `clearedValue`, not to `undefined`
=> fix(renderer): clearOnUnmount set clearedValue, not undefined

packages/react-renderer-demo/src/app/src/doc-components/initialize-mount.js
Fixes missing `name` attributes in initializeOnMount example
=> FIx initialize on mount demo example

packages/pf4-component-mapper/demo/index.html, packages/pf4-component-mapper/src/form-fields/component-mapper.js, packages/pf4-component-mapper/src/form-fields/dual-list-select.js, packages/pf4-component-mapper/src/form-fields/dual-list-select.scss, packages/pf4-component-mapper/src/tests/dual-list-select.test.js, packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/react-renderer-demo/src/app/pages/component-example/dual-list-select.md, packages/react-renderer-demo/src/app/src/components/layout.js, packages/react-renderer-demo/src/app/src/components/navigation/examples-definitions.js, packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/dual-list-select.js, packages/react-renderer-demo/src/app/src/doc-components/pf4-dual-list.md, yarn.lock
closes #358 
Add Dual List 'placeholder' component
@chambridge  @Hyperkid123 
What do you think about the design?
Will you also need async filtering?
todo:
=> feat(pf4): add duallist component

packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js, packages/pf4-component-mapper/demo/index.js, packages/pf4-component-mapper/src/components/wizard.js, packages/pf4-component-mapper/src/components/wizard/reducer.js, packages/pf4-component-mapper/src/components/wizard/wizard-step.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js, packages/react-renderer-demo/src/app/src/components/navigation/examples-definitions.js, packages/react-renderer-demo/src/app/src/doc-components/initialize-mount.js, packages/react-renderer-demo/src/app/src/doc-components/pf4-wizard.md, packages/react-renderer-demo/src/app/src/schemas/wizard-schema.js
No more 'stepKey'/'name' ambiguity!
=> breaking(pf4 wizard): stepKey is now replaced by name

packages/pf3-component-mapper/demo/demo-schemas/wizard-schema.js, packages/pf3-component-mapper/src/components/button.js, packages/pf3-component-mapper/src/components/wizard.js, packages/pf3-component-mapper/src/components/wizard/step-buttons.js, packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap, packages/pf3-component-mapper/src/tests/wizard.test.js
Same as for PF4 #365 
plus few bugs appeared after conversion fixed
=> breaking(pf3): wizard use name instead of stepKey

packages/pf4-component-mapper/src/components/dual-list-select.js
Just refactoring class to function
=> fix(PF4): duallistselect refactor to hooks

packages/react-form-renderer/demo/index.js, packages/react-form-renderer/src/form-renderer/index.js
=> fix(renderer): propagate props to root Form component.

packages/common/src/form-template.js, packages/pf4-component-mapper/src/components/wizard.js, packages/pf4-component-mapper/src/components/wizard/step-buttons.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-template-common.test.js.snap, packages/pf4-component-mapper/src/tests/form-template-common.test.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js, packages/react-form-renderer/src/components/form-renderer.js
=> [V2] Enhance on cancel reset

packages/react-form-renderer/src/form-renderer/convert-initial-value.js, packages/react-form-renderer/src/form-renderer/enhanced-on-change.js, packages/react-form-renderer/src/form-renderer/field-wrapper.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/form-renderer.test.js, packages/react-form-renderer/src/validators/index.js
=> fix(renderer): convert initialValue dataType

packages/react-renderer-demo/src/app/pages/renderer/action-mapper.md, packages/react-renderer-demo/src/app/pages/renderer/component-api.md, packages/react-renderer-demo/src/app/pages/renderer/condition.md, packages/react-renderer-demo/src/app/pages/renderer/field-array.md, packages/react-renderer-demo/src/app/pages/renderer/form-template.md, packages/react-renderer-demo/src/app/pages/renderer/initialize-mount.md, packages/react-renderer-demo/src/app/pages/renderer/renderer-api.md, packages/react-renderer-demo/src/app/pages/renderer/validators.md, packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js, packages/react-renderer-demo/src/app/src/doc-components/pf4-dual-list.md
No need to import Link, RouterLink anymore!
=> Refactor links in mdx

packages/react-renderer-demo/src/app/src/components/navigation/find-connected-links.js, packages/react-renderer-demo/src/app/src/components/navigation/mapper.js
When user was on componentExample and switch to a mapper, link in the menu was not selected
=> Fix selected menu items with queries

packages/common/src/hooks/use-is-mounted.js, packages/common/src/select/index.js, packages/common/src/select/reducer.js, packages/mui-component-mapper/src/files/select.js, packages/mui-component-mapper/src/files/select/integration-select.js, packages/pf3-component-mapper/demo/demo-schemas/sandbox.js, packages/pf3-component-mapper/src/files/select/select.js, packages/pf3-component-mapper/src/tests/form-fields/select/__snapshots__/select.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields/select/select.test.js, packages/pf4-component-mapper/src/common/select/select.js, packages/pf4-component-mapper/src/files/component-mapper.js, packages/pf4-component-mapper/src/tests/select/select.test.js
- loadOptions functionality moved to common select
- PF4 select is using common now
- PF3 can load options by searching
=> [V2] Share functionality in common select

packages/react-form-renderer/src/files/default-schema-validator.js, packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap, packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
Copy pasted code, forgot to change `and` to `or` :( 
This has to be backported to v1
=> fix(renderer): do not fail when using or

packages/mui-component-mapper/package.json, packages/pf3-component-mapper/package.json, packages/pf4-component-mapper/package.json, packages/react-form-renderer/package.json
:man_facepalming: 
I will deprecate previous versions of v2. What a silly mistake.
=> fix(common): added missing files config for npm

.circleci/config.yml, package.json, packages/react-renderer-demo/src/app/pages/renderer/action-mapper.md, packages/react-renderer-demo/src/app/pages/renderer/component-api.md, packages/react-renderer-demo/src/app/pages/renderer/condition.md, packages/react-renderer-demo/src/app/src/components/code-editor/index.js, packages/react-renderer-demo/src/app/src/components/common/connected-links.js, packages/react-renderer-demo/src/app/src/components/common/raw-component.js, packages/react-renderer-demo/src/app/src/doc-components/action-mapper.js, packages/react-renderer-demo/src/app/src/doc-components/condition.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/and.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/is-empty.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/is-not-empty.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/is.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/not-match.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/not.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/or.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/pattern.js, packages/react-renderer-demo/src/app/src/doc-components/initialize-mount.js, yarn.lock
Part of #399
Only thing I added as extra is a text to the raw component, I think it's better to tell users they can click and expand the code:
=> Fix demo technical debts

packages/common/src/select/index.js, packages/mui-component-mapper/src/files/select.js, packages/mui-component-mapper/src/files/select/integration-select.js, packages/pf3-component-mapper/src/files/select.js, packages/pf4-component-mapper/src/files/select.js, packages/react-form-renderer/src/files/use-field-api.js
=> Builder integration

packages/react-renderer-demo/src/app/babel.config.js, packages/react-renderer-demo/src/app/next.config.js, packages/react-renderer-demo/src/app/package.json, packages/react-renderer-demo/src/app/pages/live-editor.js, packages/react-renderer-demo/src/app/src/components/navigation/schema.js, yarn.lock
=> Added form builder to docs.

packages/react-form-renderer/src/parsers/default-schema-validator.js, packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap, packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
backport of https://github.com/data-driven-forms/react-forms/pull/405
=> [V1] fix(renderer): do not fail when using or

packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js, packages/pf4-component-mapper/src/form-fields/wizard/wizard-step.js, packages/pf4-component-mapper/src/form-fields/wizard/wizard.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard-step.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard-step.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
Async validation should disable the next button
=> fix(pf4): wizard disable next button when validating

packages/pf4-component-mapper/src/files/wizard/step-buttons.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
=> fix(pf4): wizard disable button on validating

babel.config.js, package.json, packages/react-form-renderer/demo/index.js, packages/react-form-renderer/src/files/default-schema-validator.js, packages/react-form-renderer/src/form-renderer/condition.js, packages/react-form-renderer/src/form-renderer/render-form.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/condition.test.js, packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap, packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js, packages/react-renderer-demo/src/app/pages/renderer/condition.md, packages/react-renderer-demo/src/app/src/doc-components/conditions/sequence.js, packages/react-renderer-demo/src/app/src/doc-components/conditions/set.js, yarn.lock
- adds sequence condition
- adds then, else branches
- adds set action
- optimize condition to listen values changes
close #427 
TODO:
=> feat(renderer): enhance conditions

packages/common/src/wizard/reducer.js, packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js, packages/pf4-component-mapper/src/files/wizard.js, packages/pf4-component-mapper/src/files/wizard/step-buttons.js, packages/pf4-component-mapper/src/files/wizard/wizard-nav.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/wizard-nav.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- refactors code, make it more simple and cleaner
- fix bugs when there are some fields on the last step
- disabling navigation when validating is in progress
- optimize subscription more
=> fix(pf4): refactor wizard, validating disable nav

README.md, package.json
=> fix(renderer): fix readme and remove major tags

packages/pf4-component-mapper/src/files/radio.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
=> fix(pf4): fixed radio not being checked.

packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
Allow to pass a container to the wizard, so we can hide it in DOM if we need to
=> fix(pf4): allow to pass container to wizard

packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js, packages/pf4-component-mapper/src/common/select/option.js, packages/pf4-component-mapper/src/common/select/select-styles.scss, packages/pf4-component-mapper/src/files/wizard.js, packages/pf4-component-mapper/src/files/wizard/reducer.js, packages/react-renderer-demo/src/app/src/doc-components/pf4-wizard.md
- wizard can obtain custom `container`
- added styles for disabled select options
=> Updates PF4 from V1

packages/react-renderer-demo/src/app/src/components/common/connected-links.js, packages/react-renderer-demo/src/app/src/components/footer.js, packages/react-renderer-demo/src/app/src/components/layout.js
**Width on smaller screen**
CSS has been broken for so long times on smaller screen
Before
After
**Right footer is being shrink**
Before
After
**Make footer different color**
Before
After
**Make navlink buttons be more consistent part of the layout**
Before
After
=> Fix styling issues on documentation

packages/react-renderer-demo/src/app/src/components/notification-panel.js
There are currently no notifications and that breaks the panel
- added a check for empty notifications
- added a placeholder 'No notifications' to the panel
=> Fix no notifications for demo

.github/labeler.yml, .github/workflows/labeler.yml
Adds labels depending on modified files
=> Add auto-labeler

packages/common/src/dual-list-select/index.js, packages/common/src/dual-list-select/reducer.js, packages/mui-component-mapper/src/files/component-mapper.js, packages/mui-component-mapper/src/files/dual-list-select.js, packages/mui-component-mapper/src/tests/dual-list-select.test.js, packages/pf4-component-mapper/src/files/component-mapper.js, packages/pf4-component-mapper/src/files/dual-list-select.js, packages/pf4-component-mapper/src/tests/dual-list-select.test.js, packages/react-form-renderer/src/files/component-types.js, packages/react-renderer-demo/src/app/pages/component-example/dual-list-select.js, packages/react-renderer-demo/src/app/src/components/navigation/examples-definitions.js, packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/dual-list-select.js, packages/react-renderer-demo/src/app/src/doc-components/mui-dual-list.md
TODO:
example (checkbox variant)
=> Add MUI dual-list-select component

packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/generic-mui-component.js
Updates PF's link to ones that work :man_shrugging: 
+ refactoring my old ugly switch code
=> Fix links to original components

packages/suir-component-mapper/demo/index.js, packages/suir-component-mapper/src/files/component-mapper.js, packages/suir-component-mapper/src/files/dual-list-select.js, packages/suir-component-mapper/src/files/slider.js, packages/suir-component-mapper/src/tests/dual-list-select.test.js
=> [v2.4] Suir slider and dual list select

packages/suir-component-mapper/demo/index.js, packages/suir-component-mapper/src/common/form-field-grid.js, packages/suir-component-mapper/src/common/multiple-choice-list.js, packages/suir-component-mapper/src/files/checkbox.js, packages/suir-component-mapper/src/files/date-picker.js, packages/suir-component-mapper/src/files/dual-list-select.js, packages/suir-component-mapper/src/files/field-array.js, packages/suir-component-mapper/src/files/plain-text.js, packages/suir-component-mapper/src/files/radio.js, packages/suir-component-mapper/src/files/select.js, packages/suir-component-mapper/src/files/sub-form.js, packages/suir-component-mapper/src/files/switch.js, packages/suir-component-mapper/src/files/tabs.js, packages/suir-component-mapper/src/files/text-field.js, packages/suir-component-mapper/src/files/textarea.js, packages/suir-component-mapper/src/files/time-picker.js
=> Suir customization

packages/blueprint-component-mapper/demo/index.js, packages/blueprint-component-mapper/package.json, packages/blueprint-component-mapper/src/files/field-array.js, packages/blueprint-component-mapper/src/files/field-array.scss, packages/blueprint-component-mapper/src/files/wizard.js, packages/blueprint-component-mapper/src/files/wizard/step-buttons.js, packages/blueprint-component-mapper/src/files/wizard/step-buttons.scss, packages/blueprint-component-mapper/src/tests/components.test.js, packages/blueprint-component-mapper/src/tests/field-array.test.js, packages/blueprint-component-mapper/src/tests/wizard.test.js, packages/react-renderer-demo/src/doc-components/examples-texts/blueprint/blueprint-field-array.md, packages/react-renderer-demo/src/doc-components/examples-texts/blueprint/blueprint-wizard.md, packages/react-renderer-demo/src/doc-components/field-array.js, packages/react-renderer-demo/src/doc-components/wizard.js
=> [v2.4] Add missing blueprint components

packages/react-renderer-demo/src/components/common/connected-links.js, packages/react-renderer-demo/src/components/navigation/mapper.js, packages/react-renderer-demo/src/hooks/use-mapper-link.js, packages/react-renderer-demo/src/hooks/use-query-param.js, yarn.lock
=> Persist mapper query param in docs.

packages/react-renderer-demo/src/components/layout.js
This should fix the initial shift
=> [v2.4] Update hidden to css

.github/workflows/labeler.yml
This action will work exclusively for you, @Hyperkid123  :smiley:
=> Do not run labeler on forks

packages/blueprint-component-mapper/demo/demo-schemas/dual-list-schema.js, packages/blueprint-component-mapper/demo/index.js, packages/blueprint-component-mapper/src/files/dual-list-select.js, packages/blueprint-component-mapper/src/files/dual-list-select.scss, packages/blueprint-component-mapper/src/files/form-group.js, packages/blueprint-component-mapper/src/tests/components.test.js, packages/blueprint-component-mapper/src/tests/dual-list-select.test.js, packages/common/babel.config.js, packages/react-renderer-demo/src/doc-components/dual-list-select.js, packages/react-renderer-demo/src/doc-components/examples-texts/blueprint/blueprint-dual-list-select.md
=> [v2.4] fix(blueprint): add dual list

packages/blueprint-component-mapper/src/files/dual-list-select.js, packages/common/babel.config.js, packages/react-renderer-demo/src/stackblitz-templates/blueprint-templates.js, packages/suir-component-mapper/demo/index.js
- Fix demo wizard template for blueprint
- fix(blueprint): do not use Classes
Build of the BJS's Dual list is wrong - Classes object does not exist - replaced by simple string :-/ 
- Return switching schemas to SUIR demo/index
=> Small fixes for BJS

packages/mui-component-mapper/src/files/component-mapper.js, packages/mui-component-mapper/src/files/select.js, packages/mui-component-mapper/src/tests/form-fields.test.js, packages/mui-component-mapper/src/tests/form-template.test.js, packages/mui-component-mapper/src/tests/select.test.js
- DatePicker was wrongly imported in the componentmapper
- Updated tests
=> Update MUI package

package.json, packages/common/package.json, packages/mui-component-mapper/package.json, packages/parsers/package.json, packages/pf3-component-mapper/package.json, packages/pf4-component-mapper/package.json, packages/react-form-renderer/package.json, packages/suir-component-mapper/package.json, templates/component-mapper/package.json, yarn.lock
Should fix failing release
see https://github.com/semantic-release/git/issues/185#issuecomment-573209765
=> Update semantic release to support semantic-release/git

packages/mui-component-mapper/src/files/field-array.d.ts, packages/pf4-component-mapper/package.json, packages/pf4-component-mapper/src/files/checkbox.d.ts, packages/pf4-component-mapper/src/files/component-mapper.d.ts, packages/pf4-component-mapper/src/files/date-picker.d.ts, packages/pf4-component-mapper/src/files/dual-list-select.d.ts, packages/pf4-component-mapper/src/files/field-array.d.ts, packages/pf4-component-mapper/src/files/form-group.d.ts, packages/pf4-component-mapper/src/files/form-template.d.ts, packages/pf4-component-mapper/src/files/plain-text.d.ts, packages/pf4-component-mapper/src/files/plain-text.js, packages/pf4-component-mapper/src/files/radio.d.ts, packages/pf4-component-mapper/src/files/select.d.ts, packages/pf4-component-mapper/src/files/slider.d.ts, packages/pf4-component-mapper/src/files/sub-form.d.ts, packages/pf4-component-mapper/src/files/switch.d.ts, packages/pf4-component-mapper/src/files/tabs.d.ts, packages/pf4-component-mapper/src/files/text-field.d.ts, packages/pf4-component-mapper/src/files/textarea.d.ts, packages/pf4-component-mapper/src/files/time-picker.d.ts, packages/pf4-component-mapper/src/files/wizard.d.ts, packages/pf4-component-mapper/tsconfig.json, packages/react-form-renderer/src/files/field-array.d.ts
=> [TS] added types for pf4 mapper

packages/blueprint-component-mapper/package.json, packages/blueprint-component-mapper/src/files/checkbox.d.ts, packages/blueprint-component-mapper/src/files/component-mapper.d.ts, packages/blueprint-component-mapper/src/files/component-mapper.js, packages/blueprint-component-mapper/src/files/date-picker.d.ts, packages/blueprint-component-mapper/src/files/date-picker.js, packages/blueprint-component-mapper/src/files/dual-list-select.d.ts, packages/blueprint-component-mapper/src/files/dual-list-select.js, packages/blueprint-component-mapper/src/files/field-array.d.ts, packages/blueprint-component-mapper/src/files/form-group.d.ts, packages/blueprint-component-mapper/src/files/form-template.d.ts, packages/blueprint-component-mapper/src/files/plain-text.d.ts, packages/blueprint-component-mapper/src/files/radio.d.ts, packages/blueprint-component-mapper/src/files/select.d.ts, packages/blueprint-component-mapper/src/files/slider.d.ts, packages/blueprint-component-mapper/src/files/sub-form.d.ts, packages/blueprint-component-mapper/src/files/switch.d.ts, packages/blueprint-component-mapper/src/files/tabs.d.ts, packages/blueprint-component-mapper/src/files/text-field.d.ts, packages/blueprint-component-mapper/src/files/textarea.d.ts, packages/blueprint-component-mapper/src/files/time-picker.d.ts, packages/blueprint-component-mapper/src/files/wizard.d.ts, packages/blueprint-component-mapper/tsconfig.json, packages/mui-component-mapper/src/files/component-mapper.d.ts, packages/pf4-component-mapper/src/files/component-mapper.d.ts
=> [TS] blueprint

packages/react-renderer-demo/src/stackblitz-templates/pf4-templates.js
Need to revert when #539 is done
=> Lock PF4 dependencies in examples

packages/react-renderer-demo/src/components/notification-panel.js
Objects are converted to arrays, so notifications can work again.
=> Convert firebase object to array

packages/blueprint-component-mapper/src/files/component-mapper.d.ts, packages/mui-component-mapper/src/files/component-mapper.d.ts, packages/pf4-component-mapper/src/files/component-mapper.d.ts, packages/suir-component-mapper/src/files/component-mapper.d.ts, yarn.lock
=> fix(all): fixed missing component mapper type extension

.eslintignore, .gitignore, package.json, scripts/generate-mapper.js, templates/component-mapper/package.json, templates/component-mapper/src/files/component-mapper.js, templates/typings/src/files/checkbox.d.ts, templates/typings/src/files/component-mapper.d.ts, templates/typings/src/files/date-picker.d.ts, templates/typings/src/files/dual-list-select.d.ts, templates/typings/src/files/field-array.d.ts, templates/typings/src/files/form-group.d.ts, templates/typings/src/files/form-template.d.ts, templates/typings/src/files/plain-text.d.ts, templates/typings/src/files/radio.d.ts, templates/typings/src/files/select.d.ts, templates/typings/src/files/slider.d.ts, templates/typings/src/files/sub-form.d.ts, templates/typings/src/files/switch.d.ts, templates/typings/src/files/tabs.d.ts, templates/typings/src/files/text-field.d.ts, templates/typings/src/files/textarea.d.ts, templates/typings/src/files/time-picker.d.ts, templates/typings/src/files/wizard.d.ts, templates/typings/tsconfig.json
This add option to attach typings to generated mapper.
=> Add TS option to generate templates

packages/suir-component-mapper/src/files/checkbox.d.ts, packages/suir-component-mapper/src/files/checkbox.js, packages/suir-component-mapper/src/files/date-picker.js, packages/suir-component-mapper/src/files/switch.js, packages/suir-component-mapper/src/files/text-field.js, packages/suir-component-mapper/src/files/time-picker.js
- removes meta and input from props list (they are obtained from the hook)
- removes unused props from checkbox (makes proptypes errors)
- do not pass type to formfield in switch, it causes propTypes error
=> Fix suir props

packages/react-renderer-demo/src/components/doc-page.js, packages/react-renderer-demo/src/helpers/list-of-contents-select.js, packages/react-renderer-demo/src/helpers/list-of-contents.js, packages/react-renderer-demo/src/next.config.js, packages/react-renderer-demo/src/pages/mappers/blueprint-component-mapper.md, packages/react-renderer-demo/src/pages/mappers/mui-component-mapper.md, packages/react-renderer-demo/src/pages/mappers/pf3-component-mapper.md, packages/react-renderer-demo/src/pages/mappers/pf4-component-mapper.md, packages/react-renderer-demo/src/pages/mappers/suir-component-mapper.md, packages/react-renderer-demo/src/pages/migration-guide.md, packages/react-renderer-demo/src/pages/renderer/action-mapper.md, packages/react-renderer-demo/src/pages/renderer/cleared-value.md, packages/react-renderer-demo/src/pages/renderer/component-api.md, packages/react-renderer-demo/src/pages/renderer/component-mapping.md, packages/react-renderer-demo/src/pages/renderer/condition.md, packages/react-renderer-demo/src/pages/renderer/data-types.md, packages/react-renderer-demo/src/pages/renderer/development-setup.md, packages/react-renderer-demo/src/pages/renderer/dynamic-fields.md, packages/react-renderer-demo/src/pages/renderer/field-provider.md, packages/react-renderer-demo/src/pages/renderer/file-input.md, packages/react-renderer-demo/src/pages/renderer/form-template.md, packages/react-renderer-demo/src/pages/renderer/get-started.md, packages/react-renderer-demo/src/pages/renderer/global-component-props.md, packages/react-renderer-demo/src/pages/renderer/initialize-mount.md, packages/react-renderer-demo/src/pages/renderer/installation.md, packages/react-renderer-demo/src/pages/renderer/renderer-api.md, packages/react-renderer-demo/src/pages/renderer/schema-validator.md, packages/react-renderer-demo/src/pages/renderer/unmounting.md, packages/react-renderer-demo/src/pages/renderer/validators.md, packages/react-renderer-demo/src/pages/testing.md
=> Use common layout component for each doc page

packages/pf4-component-mapper/demo/demo-schemas/sandbox.js, packages/react-form-renderer/src/files/default-schema-validator.js, packages/react-renderer-demo/src/components/navigation/examples-definitions.js, packages/react-renderer-demo/src/pages/component-example/tabs.js, packages/react-renderer-demo/src/pages/renderer/component-mapping.md
- the existence of TAB_ITEM is hidden, but it will live on until v3 is released
=> fix(renderer): tab children do not need component anymore

packages/react-renderer-demo/src/pages/schema/introduction.md
=> Add introduction for field schema

packages/react-renderer-demo/src/components/navigation/schemas/schema.schema.js, packages/react-renderer-demo/src/pages/schema/constants.md
=> Add constant page to schema section

packages/react-renderer-demo/src/components/navigation/schemas/schema.js, packages/react-renderer-demo/src/pages/optimization.md
=> Add importing section to menu

packages/react-renderer-demo/src/components/navigation/schemas/schema.schema.js, packages/react-renderer-demo/src/pages/schema/actions.md, packages/react-renderer-demo/src/pages/schema/introduction.md, packages/react-renderer-demo/src/pages/schema/validator-mapper.md
=> Add missing files to schema section

packages/react-renderer-demo/src/pages/components/field-provider.md, packages/react-renderer-demo/src/pages/hooks/use-field-api.md, packages/react-renderer-demo/src/pages/input-meta.md, packages/react-renderer-demo/src/pages/mappers/custom-mapper.md
=> Update field pages

packages/react-renderer-demo/src/pages/components/renderer.md
Renderer is missing import example
=> Add import to react form renderer component

packages/react-renderer-demo/src/pages/mappers/blueprint-component-mapper.md, packages/react-renderer-demo/src/pages/schema/constants.md, packages/react-renderer-demo/src/pages/testing.md
module switcher will handle this
=> Update examples to allow module switcher

packages/react-renderer-demo/src/components/navigation/mapper.js, packages/react-renderer-demo/src/components/navigation/nav-styles.js
This should make it easier to organize
=> Add spacing to nested links in docs nav

packages/react-renderer-demo/src/pages/introduction.md, packages/react-renderer-demo/src/pages/schema/data-types.md, packages/react-renderer-demo/src/pages/schema/introduction.md
Rewriting the result from the search would be too complex
=> Change common headlines

packages/react-renderer-demo/firebaseFunctions.js, packages/react-renderer-demo/src/components/notification-panel.js
I've created API endpoint for the notifications in firebase functions
No more ambiguous responses we will always receive an array
Also the expiration is simplified. No more start date. Just expiration date. The panel will show everything that has expiration date larger than the current browser date.
=> migrate docs to use firestore

packages/react-renderer-demo/src/components/component-example-text.js, packages/react-renderer-demo/src/components/docsearch.js
+ also there is no need to have that complicated redirecting logic
=> Get rid of duplication of text to allow searching

packages/react-form-renderer/src/files/wizard-context.d.ts
closes #610
- formOptions are defined in rendererContext
=> fix(renderer): fix wizard context types

packages/mui-component-mapper/package.json, packages/mui-component-mapper/src/files/date-picker.d.ts, packages/mui-component-mapper/src/files/date-picker.js, packages/mui-component-mapper/src/files/time-picker.d.ts, packages/mui-component-mapper/src/files/time-picker.js, yarn.lock
`material-ui-pickers` > `@material-ui/pickers`
=> fix(mui): replace obsolete material-ui-pickers with official package

packages/mui-component-mapper/src/tests/dependencies.test.js
- otherwise it will cause styling troubles
=> Check if demo and MUI mappers uses the same versions

config/jest.setup.js, packages/ant-component-mapper/demo/demo-schemas/wizard-schema.js, packages/ant-component-mapper/demo/index.js, packages/ant-component-mapper/src/common/form-wrapper.js, packages/ant-component-mapper/src/files/wizard.js, packages/ant-component-mapper/src/files/wizard/step-buttons.js, packages/ant-component-mapper/src/files/wizard/wizard-step.js, packages/ant-component-mapper/src/files/wizard/wizard-step.scss, packages/ant-component-mapper/src/tests/wizard.test.js
=> fix(ant): update wizard to latest changes

packages/ant-component-mapper/demo/index.js, packages/ant-component-mapper/package.json, packages/ant-component-mapper/rollup.config.js, packages/ant-component-mapper/src/files/component-mapper.js, packages/common/babel.config.js, yarn.lock
=> fix(ant): treeshake ANT mapper

packages/ant-component-mapper/demo/index.js, packages/ant-component-mapper/src/common/form-wrapper.js, packages/ant-component-mapper/src/common/is-required.js, packages/ant-component-mapper/src/common/multiple-choice-list.js, packages/ant-component-mapper/src/common/style.scss, packages/ant-component-mapper/src/files/checkbox.js, packages/ant-component-mapper/src/files/component-mapper.js, packages/ant-component-mapper/src/files/date-picker.js, packages/ant-component-mapper/src/files/dual-list-select.js, packages/ant-component-mapper/src/files/field-array.js, packages/ant-component-mapper/src/files/form-template.js, packages/ant-component-mapper/src/files/plain-text.js, packages/ant-component-mapper/src/files/radio.js, packages/ant-component-mapper/src/files/select.js, packages/ant-component-mapper/src/files/slider.js, packages/ant-component-mapper/src/files/sub-form.js, packages/ant-component-mapper/src/files/switch.js, packages/ant-component-mapper/src/files/tabs.js, packages/ant-component-mapper/src/files/text-field.js, packages/ant-component-mapper/src/files/textarea.js, packages/ant-component-mapper/src/files/time-picker.js, packages/ant-component-mapper/src/files/wizard.js, packages/ant-component-mapper/src/files/wizard/step-buttons.js, packages/ant-component-mapper/src/files/wizard/wizard-step.js, packages/ant-component-mapper/src/index.js
=> fix(ant): refactor and add customization for each component

packages/ant-component-mapper/demo/demo-schemas/dual-list-select-schema.js, packages/ant-component-mapper/demo/index.js, packages/ant-component-mapper/src/files/dual-list-select.js
based on: https://ant.design/components/transfer/
cc @Arun-42
part of #622
=> fix(ant): add dual list select component

packages/ant-component-mapper/demo/demo-schemas/slider-schema.js, packages/ant-component-mapper/demo/index.js, packages/ant-component-mapper/src/files/slider.js, packages/ant-component-mapper/src/tests/slider.test.js
=> fix(ant): Added slider component.

packages/ant-component-mapper/demo/demo-schemas/field-array-schema.js, packages/ant-component-mapper/demo/index.js, packages/ant-component-mapper/src/files/field-array.js
=> fix(ant): Added field array component

packages/ant-component-mapper/src/files/slider.js, packages/ant-component-mapper/src/files/tabs.js, packages/ant-component-mapper/src/tests/.eslintrc, packages/ant-component-mapper/src/tests/checkbox.test.js, packages/ant-component-mapper/src/tests/components.test.js, packages/ant-component-mapper/src/tests/dual-list-select.test.js, packages/ant-component-mapper/src/tests/field-array.test.js, packages/ant-component-mapper/src/tests/plain-text.test.js, packages/ant-component-mapper/src/tests/select.test.js, packages/ant-component-mapper/src/tests/slider.test.js, packages/ant-component-mapper/src/tests/subform.test.js, packages/ant-component-mapper/src/tests/tabs.test.js
=> Fix(ant): add tests for ant mapper

packages/ant-component-mapper/demo/index.js, packages/ant-component-mapper/src/common/form-wrapper.js
closes #625 
It's an official solution :man_shrugging:
=> fix(ant):r remove name from form.item to use layout component

package.json, packages/form-state-manager/src/tests/utils/state-manager-reducer.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js
=> [state-manager] Add tests for utils functions

packages/common/src/multiple-choice-list.js, packages/mui-component-mapper/src/files/slider.js, packages/pf3-component-mapper/package.json, packages/pf3-component-mapper/src/common/form-wrapper.js, packages/pf3-component-mapper/src/files/button.js, packages/pf3-component-mapper/src/files/select.js, packages/pf3-component-mapper/src/files/tabs.js, packages/pf3-component-mapper/src/files/wizard/step-buttons.js, packages/pf3-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf3-component-mapper/src/tests/__snapshots__/multiple-choice-list.test.js.snap, packages/pf3-component-mapper/src/tests/__snapshots__/tabs.test.js.snap, packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields.test.js, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/__snapshots__/mont-selector.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/__snapshots__/navbar.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/__snapshots__/picker-input.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/__snapshots__/time-picker.test.js.snap, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/date-time-picker.test.js, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/mont-selector.test.js, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/navbar.test.js, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/picker-input.test.js, packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/time-picker.test.js, packages/pf3-component-mapper/src/tests/form-fields/select/select.test.js, packages/pf3-component-mapper/src/tests/form-template.test.js, packages/pf3-component-mapper/src/tests/multiple-choice-list.test.js, packages/pf3-component-mapper/src/tests/tabs.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js, packages/react-form-renderer/src/form-renderer/condition.js, packages/suir-component-mapper/src/tests/form-fields.test.js, yarn.lock
- clears errors/warnings from all tests
- unskips tests that were skipped
- updates PF3 trying to remove 
```jsx
Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
```
however, it didn't help.
=> Clear tests

packages/form-state-manager/demo/index.tsx, packages/form-state-manager/package.json, packages/form-state-manager/src/files/form-manager-context.ts, packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/types/form-manager-context.d.ts, packages/form-state-manager/src/types/form-state-manager.d.ts, packages/form-state-manager/src/types/state-manager-reducer.d.ts, packages/form-state-manager/src/types/use-field.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/utils/state-manager-reducer.ts, packages/form-state-manager/src/utils/use-subscription.ts, scripts/copy-files.js
- extract types to seperate folder
- Allow to use types folder to generate types (just pass any argument to copy-files.. :smile:  we can specify it later if we will need to)
=> [STATE-MANAGER] Extract types to /types folder

packages/form-state-manager/src/files/form-manager-context.ts, packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/types/form-manager-context.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> feat(manager): create global manager api

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
closes #675
Add all metadata.
Added computation example for change field.
=> feat(state): Add basic form metadata

packages/form-state-manager/src/files/form-manager-context.ts, packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/types/field-state.ts, packages/form-state-manager/src/types/form-manager-context.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> [manager] Store field state in global state

packages/form-state-manager/src/files/form-manager-context.ts, packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/types/form-manager-context.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> feat(manager): add blur and focus event handlers

packages/form-state-manager/src/files/form-manager-context.ts, packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/types/form-state-manager.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> feat(state): clearOnUnmount

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> feat(state): introduce initializeOnMount

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/helpers/text-field.tsx, packages/form-state-manager/src/tests/utils/validate.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/types/use-field.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/types/validate.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts, packages/form-state-manager/src/utils/validate.ts
part of #687 
- adds managerApi validation flag mutation
- adds field level sync/async validator
=> feat(manager): add field level validation API

packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
closes #649 
Seems that https://github.com/data-driven-forms/react-forms/pull/666 fixed this issue too. I cannot reproduce it.
=> Unskip PF4 wizard test

packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/types/form-state-manager.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/types/use-field.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> feat(state): add subscription API

packages/form-state-manager/demo/index.tsx, packages/form-state-manager/src/tests/helpers/text-field.tsx, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/utils/use-subscription.ts
=> [manager ]feat(manager): mutate field level state on validation error

packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/types/form-manager-context.d.ts, packages/form-state-manager/src/types/form-state-manager.d.ts, packages/form-state-manager/src/types/use-subscription.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> feat(state): implement clearedValue

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
=> fix(state): add initialValues to values

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/any-object.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> fix(state): match FF's getState output

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(state): add batch function

packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/form-state-manager.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
Waiting for https://github.com/data-driven-forms/react-forms/pull/706/
Part of https://github.com/data-driven-forms/react-forms/issues/690
=> feat(manager): add debug prop

packages/form-state-manager/src/files/form-manager-context.ts, packages/form-state-manager/src/files/form-spy.ts, packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/tests/form-spy.test.js, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/types/form-manager-context.d.ts, packages/form-state-manager/src/types/form-spy.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/generate-id.ts, packages/form-state-manager/src/utils/manager-api.ts, packages/form-state-manager/src/utils/use-subscription.ts
parts of https://github.com/data-driven-forms/react-forms/issues/705
- also implements FormSpy
=> feat(state): add subscribe/unsubscribe

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/utils/manager-api.ts
part of  https://github.com/data-driven-forms/react-forms/issues/705
=> feat(manager): match FF's field getState

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): add reset/restart functions

packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
FF exports submit, not handleSubmit
=> fix(manager): add submit

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/files/use-field-array.test.js, packages/form-state-manager/src/types/use-field-array.d.ts, packages/form-state-manager/src/types/use-field.d.ts
part of: https://github.com/data-driven-forms/react-forms/issues/721
- adds bare minimum field array support to be able to register field array fields
- map
- forEach
=> feat(manager): Add basic field array support

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/use-subscription.test.js, packages/form-state-manager/src/utils/manager-api.ts
=> fix(manager): unflat values in state

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): introduce resume/pause validation

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/tests/files/use-field-array.test.js, packages/form-state-manager/src/types/use-field-array.d.ts
=> feat(manager): add field array remove/shift/pop methods

packages/common/src/select/index.js, packages/pf3-component-mapper/src/files/select/select.js
@skateman can you link this changes locally? It looks like to be fixed when reproducing locally, but I have no PF3 example handy
=> fix(common): use isMounted.current in select

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): introduce isEqual and validateFields

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/tests/files/use-field-array.test.js, packages/form-state-manager/src/types/use-field-array.d.ts
=> feat(manager): add field array update method

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/tests/files/use-field-array.test.js, packages/form-state-manager/src/types/use-field-array.d.ts, packages/form-state-manager/src/utils/array-move.ts
=> feat(manager): add move and swap field array methods

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/tests/files/use-field-array.test.js, packages/form-state-manager/src/types/use-field-array.d.ts
=> feat(manager): add field array unshift method

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/files/use-field.test.js, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> fix(manager): rename value to initialValue in field config

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/tests/files/use-field-array.test.js, packages/form-state-manager/src/types/use-field-array.d.ts
part of: https://github.com/data-driven-forms/react-forms/issues/721
=> feat(manager): add field array insert method

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/files/use-field.test.js, packages/form-state-manager/src/types/use-field.d.ts
=> feat(manager): add support for field.type

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/tests/files/use-field-array.test.js, packages/form-state-manager/src/types/use-field-array.d.ts
=> feat(manager): add concat and removeBatch field array methods

packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/types/use-field-array.d.ts
=> fix(manager): add length to field array meta

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): introduce defaultValue

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/files/use-field.test.js, packages/form-state-manager/src/types/use-field.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): introduce format & parse

packages/form-state-manager/src/files/form-manager-context.ts, packages/form-state-manager/src/files/form-state-manager.tsx, packages/form-state-manager/src/files/use-field-array-api.ts, packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/types/form-manager-context.d.ts, packages/form-state-manager/src/types/use-field-array-api.d.ts, packages/form-state-manager/src/types/use-field-array.d.ts
=> fix(manager): create common field array api hook

packages/form-state-manager/src/files/field-array.tsx, packages/form-state-manager/src/files/use-field-array.ts, packages/form-state-manager/src/types/field-array.d.ts, packages/form-state-manager/src/types/use-field-array.d.ts
=> feat(manager): add FieldArray component

packages/form-state-manager/src/tests/files/use-field.test.js, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/validate.test.js, packages/form-state-manager/src/utils/manager-api.ts
=> fix(manager): do initial validation

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): add data in registerField

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/field-config.d.ts, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/types/use-field.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): add after/before submit callbacks

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/files/use-field.test.js, packages/form-state-manager/src/types/use-field.d.ts
=> feat(manager): implement allowNull

packages/form-state-manager/src/files/use-field.ts, packages/form-state-manager/src/tests/files/use-field.test.js
Will simplify using of multi selects.
=> feat(manager): implement multiple for on change

packages/form-state-manager/src/tests/files/use-field.test.js, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
closes https://github.com/data-driven-forms/react-forms/issues/739
=> fix(manager): allow multiple isEqual for a field

packages/form-state-manager/src/files/field.tsx, packages/form-state-manager/src/tests/files/field.test.js, packages/form-state-manager/src/types/field.d.ts
=> feat(manager): add field component

packages/react-renderer-demo/src/helpers/list-of-contents-select.js
=> Fix popper position on mobile screens

packages/react-renderer-demo/src/components/code-example.js
- having H1 messed up Algolia
- Link actually supports the same API as the Typography
=> Merge typography and link components in code example

README.md, packages/ant-component-mapper/README.md, packages/blueprint-component-mapper/README.md, packages/mui-component-mapper/README.md, packages/parsers/README.md, packages/pf3-component-mapper/README.md, packages/pf4-component-mapper/README.md, packages/react-form-renderer/README.md, packages/suir-component-mapper/README.md, templates/component-mapper/README.md
Adds two twitter badges to all readmes:
=> Add twitter badges to readmes

packages/react-renderer-demo/src/components/docsearch.js
- full screen
- proper position
**Before**
**After**
=> Fix algolia search on mobile screens

packages/carbon-component-mapper/demo/index.js, packages/carbon-component-mapper/package.json, packages/carbon-component-mapper/src/files/dual-list-select.d.ts, packages/carbon-component-mapper/src/files/dual-list-select.js, packages/carbon-component-mapper/src/files/dual-list-select.scss, packages/carbon-component-mapper/src/tests/dual-list-select.test.js, packages/common/babel.config.js, yarn.lock
part of https://github.com/data-driven-forms/react-forms/issues/795
TODO:
=> feat(carbon): add dual list component

packages/carbon-component-mapper/demo/demo-schemas/widget-schema.js, packages/carbon-component-mapper/demo/index.js, packages/carbon-component-mapper/src/files/field-array.d.ts, packages/carbon-component-mapper/src/files/field-array.js, packages/carbon-component-mapper/src/files/field-array.scss, packages/carbon-component-mapper/src/tests/field-array.test.js
TODO:
- wait for https://github.com/data-driven-forms/react-forms/issues/795 to get clsx for merging classNames
=> feat(carbon): add field array component

packages/carbon-component-mapper/demo/demo-schemas/wizard-schema.js, packages/carbon-component-mapper/src/files/wizard.d.ts, packages/carbon-component-mapper/src/files/wizard.js, packages/carbon-component-mapper/src/files/wizard.scss, packages/carbon-component-mapper/src/tests/wizard.test.js, packages/common/babel.config.js
part of https://github.com/data-driven-forms/react-forms/issues/795
TODO:
=> feat(carbon): wizard component

packages/react-form-renderer/src/index.js
=> fix(renderer): export validator mapper in index.js

packages/react-renderer-demo/src/components/navigation/schemas/mappers.schema.js, packages/react-renderer-demo/src/doc-components/date-picker.js, packages/react-renderer-demo/src/doc-components/dual-list-select.js, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-date-picker.md, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-dual-list-select.md, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-field-array.md, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-plain-text.md, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-radio.md, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-sub-form.md, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-time-picker.md, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-wizard.md, packages/react-renderer-demo/src/doc-components/field-array.js, packages/react-renderer-demo/src/doc-components/plain-text.js, packages/react-renderer-demo/src/doc-components/radio.js, packages/react-renderer-demo/src/doc-components/sub-form.js, packages/react-renderer-demo/src/doc-components/time-picker.js, packages/react-renderer-demo/src/doc-components/wizard.js, packages/react-renderer-demo/src/pages/mappers/sub-form.js
Part of https://github.com/data-driven-forms/react-forms/issues/795
=> Add texts for Cabon components

packages/carbon-component-mapper/src/files/date-picker.js, packages/carbon-component-mapper/src/files/field-array.js, packages/carbon-component-mapper/src/files/form-group.d.ts, packages/carbon-component-mapper/src/files/select.js, packages/carbon-component-mapper/src/files/slider.js, packages/carbon-component-mapper/src/files/text-field.js, packages/carbon-component-mapper/src/files/textarea.js, packages/carbon-component-mapper/src/files/time-picker.js
part of https://github.com/data-driven-forms/react-forms/issues/795
=> fix(carbon): introduce validateOnMount

packages/carbon-component-mapper/README.md, packages/carbon-component-mapper/src/common/helper-text-block.js, packages/carbon-component-mapper/src/common/helper-text-block.scss, packages/carbon-component-mapper/src/files/checkbox.js, packages/carbon-component-mapper/src/files/date-picker.js, packages/carbon-component-mapper/src/files/radio.js, packages/carbon-component-mapper/src/files/slider.js, packages/carbon-component-mapper/src/files/switch.js, packages/carbon-component-mapper/src/files/time-picker.js, packages/carbon-component-mapper/src/tests/components.test.js, packages/react-renderer-demo/src/pages/mappers/carbon-component-mapper.md
- adds helperText and errorTexts where are not natively supported
=> Carbon helper text

packages/carbon-component-mapper/README.md, packages/carbon-component-mapper/rollup.config.js, packages/carbon-component-mapper/src/files/dual-list-select.js, packages/carbon-component-mapper/src/files/wizard.js, packages/common/babel.config.js
closes #818
StructuredList/ProgressStep components are exported differently than all other components. I will try to solve this in Carbon project, until then this fix should work well.
cc @skateman
=> fix(carbon): add seperate transformation for progressStep/structuredList

packages/pf3-component-mapper/src/tests/__snapshots__/input-addon.test.js.snap, packages/pf3-component-mapper/src/tests/__snapshots__/multiple-choice-list.test.js.snap, packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/react-form-renderer/src/files/condition.d.ts, packages/react-form-renderer/src/files/default-schema-validator.js, packages/react-form-renderer/src/files/parse-condition.d.ts, packages/react-form-renderer/src/files/parse-condition.js, packages/react-form-renderer/src/form-renderer/condition.js, packages/react-form-renderer/src/form-renderer/render-form.js, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap, packages/react-form-renderer/src/tests/form-renderer/condition.test.js, packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js, packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap, packages/react-renderer-demo/src/pages/schema/condition-schema.md
closes #820
- when in condition can be a function that gets the current field as the first argument
**Function**
*currentField => string | string[]*
A function receiving the current field as the first argument. Can be used to get dynamically created field name:
```jsx
{
when: (field) => `${getFieldNumber(field)}.name`
}
/*
field = {
name: 'person[14]',
}
*/
```
A function in an array cannot return another array.
=> feat(renderer): dynamic when attribute

packages/form-state-manager/src/files/form-error.ts, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
allows to use async function for submits
=> feat(manager): implement async onSubmit

packages/react-renderer-demo/src/components/landing-page/landing-page-cards.js, packages/react-renderer-demo/src/pages/hooks/use-field-api.md
Using code blocks to describe content makes it unreachable in Algolia.
Also I added some examples to make it easier for beginners.
=> Fix useFieldApi doc page

packages/react-renderer-demo/src/components/navigation/schemas/schema.js, packages/react-renderer-demo/src/pages/faq.md
closes https://github.com/data-driven-forms/react-forms/issues/806
Add popular question from issues to web
=> Add FAQ page to demo

packages/react-renderer-demo/src/components/code-example.js
closes https://github.com/data-driven-forms/react-forms/issues/811
- fixes wrong url to github (old project structure)
- using the same heading for examples as for headers (with a link)
=> Update codeExample heading and url to github

packages/pf4-component-mapper/src/files/dual-list-select.js, packages/pf4-component-mapper/src/files/dual-list-select.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-9548
Old
New
=> PF4 Dual List Select mobile styling

packages/react-renderer-demo/src/components/code-editor/index.js, packages/react-renderer-demo/src/components/code-example.js
- ExapnsionPanel was renamed to Accordion
=> Fix MUI imports in demo

packages/pf3-component-mapper/package.json, yarn.lock
=> fix(pf3): downgrade version of react day picker

packages/react-renderer-demo/src/examples/components/validators/url-validator.js, packages/react-renderer-demo/src/helpers/list-of-contents.js, packages/react-renderer-demo/src/pages/schema/async-validator.md, packages/react-renderer-demo/src/pages/schema/custom-validator.md, packages/react-renderer-demo/src/pages/schema/length-validator.md, packages/react-renderer-demo/src/pages/schema/number-value-validator.md, packages/react-renderer-demo/src/pages/schema/pattern-validator.md, packages/react-renderer-demo/src/pages/schema/record-level-validation.md, packages/react-renderer-demo/src/pages/schema/required-validator.md, packages/react-renderer-demo/src/pages/schema/url-validator.md
- more wordy, more searchable, more inline examples
=> Update validation docs

packages/react-renderer-demo/src/examples/components/action-mapper.js, packages/react-renderer-demo/src/examples/components/condition.js, packages/react-renderer-demo/src/examples/components/conditions/and.js, packages/react-renderer-demo/src/examples/components/conditions/is-empty.js, packages/react-renderer-demo/src/examples/components/conditions/is-not-empty.js, packages/react-renderer-demo/src/examples/components/conditions/not-match.js, packages/react-renderer-demo/src/examples/components/conditions/not.js, packages/react-renderer-demo/src/examples/components/conditions/pattern.js, packages/react-renderer-demo/src/examples/components/conditions/set.js, packages/react-renderer-demo/src/examples/components/field-array/pf4-demo.js, packages/react-renderer-demo/src/examples/components/form-template/custom-buttons.js, packages/react-renderer-demo/src/examples/components/schema-validator.js, packages/react-renderer-demo/src/examples/components/validators/async-validator.js, packages/react-renderer-demo/src/examples/components/validators/custom-function.js, packages/react-renderer-demo/src/examples/components/validators/global-message.js, packages/react-renderer-demo/src/examples/components/validators/length-validators.js, packages/react-renderer-demo/src/examples/components/validators/number-validator.js, packages/react-renderer-demo/src/examples/components/validators/pattern-validator.js, packages/react-renderer-demo/src/examples/components/validators/record-level-validation.js, packages/react-renderer-demo/src/examples/components/validators/required-validator.js, packages/react-renderer-demo/src/examples/components/validators/url-validator.js
- this devs exists because they were setting 'pf4' class in the past.
=> Remove obsolete divs from code examples

yarn.lock
This package should be vulnerable according to other repos.
=> Update object path dependency to fix vulnerability

packages/pf4-component-mapper/demo/index.html, packages/pf4-component-mapper/package.json, packages/pf4-component-mapper/src/common/form-group.js, packages/pf4-component-mapper/src/common/show-error.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/__snapshots__/form-template-common.test.js.snap, packages/pf4-component-mapper/src/tests/form-fields.test.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard-step.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js, yarn.lock
part of #844 
- updates PF4 to latest to allow using `validated: warning` variant
=> feat(pf4): show meta.warnings

packages/blueprint-component-mapper/src/files/form-group.js, packages/blueprint-component-mapper/src/tests/components.test.js
Part of https://github.com/data-driven-forms/react-forms/issues/844
=> feat(blueprint): implement warning intent

packages/mui-component-mapper/src/files/checkbox.js, packages/mui-component-mapper/src/files/date-picker.js, packages/mui-component-mapper/src/files/dual-list-select.js, packages/mui-component-mapper/src/files/radio.js, packages/mui-component-mapper/src/files/select.js, packages/mui-component-mapper/src/files/slider.js, packages/mui-component-mapper/src/files/switch.js, packages/mui-component-mapper/src/files/text-field.js, packages/mui-component-mapper/src/files/textarea.js, packages/mui-component-mapper/src/files/time-picker.js, packages/mui-component-mapper/src/tests/form-fields.test.js
part of https://github.com/data-driven-forms/react-forms/issues/844
- MUI components does not have a warning state... so the warning is just passed to helperText
TODO:
=> feat(mui): implement warning validation

packages/ant-component-mapper/src/common/form-wrapper.js, packages/ant-component-mapper/src/tests/components.test.js
part of https://github.com/data-driven-forms/react-forms/issues/844
=> feat(ant): add warning

packages/suir-component-mapper/src/common/helpers.js, packages/suir-component-mapper/src/files/checkbox.js, packages/suir-component-mapper/src/files/date-picker.js, packages/suir-component-mapper/src/files/dual-list-select.js, packages/suir-component-mapper/src/files/radio.js, packages/suir-component-mapper/src/files/select.js, packages/suir-component-mapper/src/files/switch.js, packages/suir-component-mapper/src/files/text-field.js, packages/suir-component-mapper/src/files/textarea.js, packages/suir-component-mapper/src/files/time-picker.js, packages/suir-component-mapper/src/tests/form-fields.test.js
part of https://github.com/data-driven-forms/react-forms/issues/844
Warning are passed as helper text
=> feat(suir): implement warning as helperText

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/form-spy.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> fix(manager): do not allow send submit when invalid

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/utils/manager-api.ts
=> fix(manager): set touched on blur

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/utils/manager-api.ts
=> fix(manager): recalculate dirty/pristine based on fields

packages/react-renderer-demo/src/doc-components/examples-texts/mui/text-field.md
=> Add FormFieldGridProps to mua text field docs.

packages/ant-component-mapper/src/files/form-template.d.ts, packages/ant-component-mapper/src/files/form-template.js, packages/blueprint-component-mapper/src/files/form-template.d.ts, packages/carbon-component-mapper/src/files/form-template.d.ts, packages/carbon-component-mapper/src/files/form-template.js, packages/common/src/form-template.d.ts, packages/common/src/form-template.js, packages/mui-component-mapper/src/files/form-template.d.ts, packages/mui-component-mapper/src/files/form-template.js, packages/pf3-component-mapper/src/files/form-template.js, packages/pf3-component-mapper/src/tests/__snapshots__/multiple-choice-list.test.js.snap, packages/pf4-component-mapper/src/files/form-template.d.ts, packages/pf4-component-mapper/src/files/form-template.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-template-common.test.js.snap, packages/react-renderer-demo/src/pages/components/form-template.md, packages/suir-component-mapper/src/files/form-template.d.ts, packages/suir-component-mapper/src/files/form-template.js, templates/component-mapper/src/files/form-template.js, templates/typings/src/files/form-template.d.ts
closes https://github.com/data-driven-forms/react-forms/issues/804
=> feat(formTemplate): allow to pass props to each component

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/manager-api.ts
=> fix(manager): set form.validating to true when a field is being validated

packages/pf4-component-mapper/demo/index.html, packages/pf4-component-mapper/package.json, packages/pf4-component-mapper/src/files/wizard.js, packages/pf4-component-mapper/src/files/wizard/reducer.js, packages/pf4-component-mapper/src/files/wizard/wizard-toggle.js, packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap, packages/pf4-component-mapper/src/tests/wizard/wizard-toggle.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js, packages/react-renderer-demo/src/stackblitz-templates/pf4-templates.js, yarn.lock
=> Wizard dropdown nav

packages/pf4-component-mapper/src/files/dual-list-select.d.ts, packages/pf4-component-mapper/src/files/dual-list-select.js, packages/react-renderer-demo/src/doc-components/examples-texts/pf4/dual-list-select.md
Added necessary props to make dual-list pf4 mapper elements customizable
@Hyperkid123
=> Make dual-list pf4 mapper elements customizable

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/utils/manager-api.ts
part of #860 
- fields meta attributes corresponds to form state
- submit fails on resolve, not on catch
- submit data are restarted on submitting
=> fix(manager): fix submitting

packages/form-state-manager/demo/index.tsx, packages/form-state-manager/src/tests/helpers/text-field.tsx, packages/form-state-manager/src/tests/utils/focus-error.test.js, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/types/manager-api.d.ts, packages/form-state-manager/src/utils/focus-error.ts, packages/form-state-manager/src/utils/manager-api.ts
=> feat(manager): focus on error input

packages/carbon-component-mapper/src/files/checkbox.js, packages/carbon-component-mapper/src/files/date-picker.js, packages/carbon-component-mapper/src/files/dual-list-select.js, packages/carbon-component-mapper/src/files/field-array.js, packages/carbon-component-mapper/src/files/prepare-props.d.ts, packages/carbon-component-mapper/src/files/prepare-props.js, packages/carbon-component-mapper/src/files/radio.js, packages/carbon-component-mapper/src/files/select.js, packages/carbon-component-mapper/src/files/slider.js, packages/carbon-component-mapper/src/files/switch.js, packages/carbon-component-mapper/src/files/text-field.js, packages/carbon-component-mapper/src/files/textarea.js, packages/carbon-component-mapper/src/files/time-picker.js, packages/carbon-component-mapper/src/index.js
This function can be very useful when building custom carbon-based components...
=> feat(carbon): make prepareProps available externally

packages/react-renderer-demo/src/pages/mappers/pf3-component-mapper.md
After merging I will create a new notification in the DB to point to these news.
=> Add alert for PF3 mapper

packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/utils/manager-api.ts
closes #882 
- fixes inconsistency when storing errors
- makes `flatErrors` internal object to have more easily accessible object
=> fix(manager): fix error format inconsistency

.github/pull_request_template.md
This should help our community and us to make correct PRs with all needed formalities.
=> Create Pull request template

packages/react-renderer-demo/src/components/navigation/schemas/custom-examples.schema.js, packages/react-renderer-demo/src/components/navigation/schemas/schema.js, packages/react-renderer-demo/src/examples/components/examples/sample-example.js, packages/react-renderer-demo/src/pages/examples/sample-example.md
- add custom components demo section to docs
cc @jinxac
=> Add custom components docs section.

packages/react-renderer-demo/src/pages/development-setup.md
Add a step by step guide to add a custom example to the docs.
=> Custom examples guide.

packages/react-renderer-demo/src/components/footer.js
=> Fix missing curly brackets in footer.js

.github/ISSUE_TEMPLATE/issue.md
=> Issue template desc has maximum size of 200 chars

packages/pf4-component-mapper/src/files/radio.js
Allows to customize radio options.
=> fix(pf4): Allow to customize radio options

packages/react-renderer-demo/src/pages/schema/introduction.md
=> fix(doc): Fix minor typo

packages/pf4-component-mapper/src/files/wizard.js, packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
Allows to set up a custom class name on wizard.
=> fix(pf4): fix wizard classname prop

packages/react-renderer-demo/src/components/footer.js, packages/react-renderer-demo/src/pages/_document.js
=> Add Copyright to documenation page

packages/react-renderer-demo/src/components/code-editor/index.js, packages/react-renderer-demo/src/components/code-editor/transform-imports.js, packages/react-renderer-demo/src/components/landing-page/landing-page-cards.js, packages/react-renderer-demo/src/components/mdx/mdx-components.js, packages/react-renderer-demo/src/pages/components/renderer.md, packages/react-renderer-demo/src/pages/mappers/custom-mapper.md, packages/react-renderer-demo/src/pages/optimization.md, packages/react-renderer-demo/src/pages/testing.md
- updated optimization page
- no switcher
- automatically transforms root imports to relative one
=> Update demo code editor

packages/react-renderer-demo/src/components/code-editor/index.js, packages/react-renderer-demo/src/components/navigation/schemas/schema.js, packages/react-renderer-demo/src/pages/migration-guide-v3.md, packages/react-renderer-demo/src/pages/optimization.md
=> Add migration guide to V3

packages/mui-component-mapper/src/files/field-array.d.ts, packages/mui-component-mapper/src/files/field-array.js, packages/react-renderer-demo/src/doc-components/examples-texts/mui/field-array.md
This PR adds customization for field array.
Opening it as draft until we resolve our strategy for v2/v3 transition.
=> feat(mui): allow customization for field array

packages/react-renderer-demo/src/components/navigation/schemas/custom-examples.schema.js, packages/react-renderer-demo/src/examples/components/examples/custom-layout-component.js, packages/react-renderer-demo/src/examples/components/examples/resolve-props-db.js, packages/react-renderer-demo/src/examples/components/examples/resolve-props-formspy.js, packages/react-renderer-demo/src/examples/components/examples/resolve-props-subscription.js, packages/react-renderer-demo/src/pages/examples/custom-layout-component.md, packages/react-renderer-demo/src/pages/examples/resolve-props-db.md, packages/react-renderer-demo/src/pages/examples/resolve-props-example.md
- resolveProps multiple solutions
- custom layout components
- resolveProps stored in DB
=> Add examples to demo

packages/ant-component-mapper/package.json, packages/mui-component-mapper/package.json, packages/pf4-component-mapper/package.json, packages/pf4-component-mapper/src/date-picker/date-picker.js, packages/pf4-component-mapper/src/tests/form-fields.test.js, packages/pf4-component-mapper/src/tests/form-template-common.test.js, packages/pf4-component-mapper/src/time-picker/time-picker.js, packages/suir-component-mapper/package.json, yarn.lock
Use original DatePicker and TimePicker PF4 components
=> Use original DatePicker and TimePicker PF4 components

packages/carbon-component-mapper/src/select/select.js, packages/carbon-component-mapper/src/tests/select.test.js
fixes #1022 
Will be backported to v2 after merge
=> fix(carbon): combobox initial value label

README.md, packages/ant-component-mapper/README.md, packages/ant-component-mapper/package.json, packages/blueprint-component-mapper/README.md, packages/blueprint-component-mapper/package.json, packages/carbon-component-mapper/README.md, packages/carbon-component-mapper/package.json, packages/common/package.json, packages/mui-component-mapper/README.md, packages/mui-component-mapper/package.json, packages/parsers/README.md, packages/parsers/package.json, packages/pf4-component-mapper/README.md, packages/pf4-component-mapper/package.json, packages/react-form-renderer/README.md, packages/react-form-renderer/package.json, packages/react-renderer-demo/src/pages/development-setup.md, packages/suir-component-mapper/README.md, packages/suir-component-mapper/package.json, templates/component-mapper/README.md
Adds a shortcut for yarn test for each package
=> Add yarn test shortcut for each package

packages/react-renderer-demo/src/components/navigation/schemas/schema.schema.js, packages/react-renderer-demo/src/examples/components/validators/custom-message.js, packages/react-renderer-demo/src/pages/schema/custom-validator-message.md, packages/react-renderer-demo/src/pages/schema/introduction.md
=> Better validate docs

packages/react-renderer-demo/package.json, packages/react-renderer-demo/src/helpers/field-properties.js, packages/react-renderer-demo/src/pages/live-editor.js, yarn.lock
=> Return live editor page

packages/react-renderer-demo/src/components/code-editor/index.js, packages/react-renderer-demo/src/pages/live-editor.js
=> Fix width of codeEditor in live editor page

packages/react-renderer-demo/src/components/component-example.js, packages/react-renderer-demo/src/helpers/generic-mui-component.js, packages/react-renderer-demo/src/helpers/original-component-link.js
Adds link to original components and github in component example page
=> Add links to original components and DDF implementation

packages/react-renderer-demo/src/stackblitz-templates/ant-templates.js, packages/react-renderer-demo/src/stackblitz-templates/blueprint-templates.js, packages/react-renderer-demo/src/stackblitz-templates/carbon-templates.js, packages/react-renderer-demo/src/stackblitz-templates/pf4-templates.js, packages/react-renderer-demo/src/stackblitz-templates/suir-template.js
The only issue that happens is this one:
It does because of react-jss. 🤔  Trying to figure what is going there.
=> Update stackblitz templates

packages/carbon-component-mapper/src/tests/text-field.test.js, packages/carbon-component-mapper/src/text-field/text-field.js
**fixes:** https://github.com/data-driven-forms/react-forms/issues/1037
For number input value should be e.imaginaryTarget.value instead of e.target.value
=> fix(carbon): textinput type Number onchange function

packages/common/package.json, packages/react-renderer-demo/src/stackblitz-templates/ant-templates.js, packages/react-renderer-demo/src/stackblitz-templates/blueprint-templates.js, packages/react-renderer-demo/src/stackblitz-templates/carbon-templates.js, packages/react-renderer-demo/src/stackblitz-templates/mui-templates.js, packages/react-renderer-demo/src/stackblitz-templates/pf4-templates.js, packages/react-renderer-demo/src/stackblitz-templates/suir-template.js
=> Add common to stackblitz templates

packages/carbon-component-mapper/src/files/switch.js, packages/carbon-component-mapper/src/tests/switch.test.js
Backport of https://github.com/data-driven-forms/react-forms/pull/1049
=> fix(carbon): fix switch toggled attribute

packages/react-form-renderer/src/form-renderer/render-form.js, packages/react-form-renderer/src/get-condition-triggers/get-condition-triggers.js
Do not memoize condition triggers function
- this breaks if multiple fields are using same function (will be problem in field arrays)
Use Object customizer to create values
- if you are using number keys in your object, this can create a large array of null elements
=> Fix condition trigger

.eslintrc.json, package.json, packages/blueprint-component-mapper/src/tests/components.test.js, packages/pf4-component-mapper/src/tests/wizard/wizard.test.js, packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js, packages/react-form-renderer/src/tests/validators/validators.test.js, yarn.lock
This adds [eslint-plugin-jest](https://www.npmjs.com/package/eslint-plugin-jest) to check any `.only` leftovers.
=> Add jest plugin for eslint

packages/common/src/test/dual-list-select/dual-list-select.test.js, packages/common/src/test/form-template/form-template.test.js, packages/common/src/test/hooks/use-is-mounted.test.js, packages/common/src/test/multiple-choice-list/multiple-choice-list.test.js, packages/common/src/test/utils.test.js, packages/common/src/test/wizard/enter-handler.test.js, packages/common/src/test/wizard/reducer.test.js, packages/common/src/test/wizard/select-next.test.js, packages/common/src/test/wizard/wizard.test.js, packages/common/src/wizard/reducer.js, packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js
Part of #932
Missing select component, will make it in a separate PR. I don't have power to do that in me anymore. :D
=> Add tests for common package

packages/common/src/select/reducer.js, packages/common/src/select/select.js, packages/common/src/test/select/parse-internal-value.test.js, packages/common/src/test/select/select.test.js
=> Add tests for common select

packages/pf4-component-mapper/src/text-field/text-field.js, packages/pf4-component-mapper/src/textarea/textarea.js
=> fix(pf4): add missing isRequired prop

packages/react-renderer-demo/src/components/component-example.js
`checkbox-multiple` should be redirected to `checkbox`
=> Correct checkbox-multiple links in demo

packages/react-renderer-demo/src/components/navigation/schemas/custom-examples.schema.js, packages/react-renderer-demo/src/examples/components/examples/value-listener-b.js, packages/react-renderer-demo/src/examples/components/examples/value-listener.js, packages/react-renderer-demo/src/pages/examples/value-listener.md
This adds an example for custom value listener
=> Add example for a value listener

packages/react-renderer-demo/src/components/component-example.js
=> Add alert for examples that do not work

packages/carbon-component-mapper/src/files/select.js, packages/carbon-component-mapper/src/tests/select.test.js
backport of https://github.com/data-driven-forms/react-forms/pull/1078
=> fix(carbon): fix empty initial value in multi select

packages/carbon-component-mapper/src/files/select.js
backport of https://github.com/data-driven-forms/react-forms/pull/1081
=> fix(carbon): pass isMulti to ddf select

packages/common/babel.config.js
Fixes #https://github.com/data-driven-forms/react-forms/issues/1038
- this should fix the errors in the example
=> fix(common): transform react-jss to esm/cjs

packages/react-renderer-demo/src/components/component-example.js, packages/react-renderer-demo/src/stackblitz-templates/blueprint-templates.js, packages/react-renderer-demo/src/stackblitz-templates/carbon-templates.js, packages/react-renderer-demo/src/stackblitz-templates/suir-template.js
Fixes #https://github.com/data-driven-forms/react-forms/issues/1038
=> Fix all demo examples and remove the alert

.github/workflows/main.yml, packages/react-renderer-demo/firebaseFunctions.js, packages/react-renderer-demo/package.json, yarn.lock
Adds an action that shows the next version in PR comments
_Let's see what will happen_
=> Add custom action to show next version in comments

packages/carbon-component-mapper/src/files/checkbox.js, packages/carbon-component-mapper/src/tests/checkbox.test.js
backport of https://github.com/data-driven-forms/react-forms/pull/1089
=> fix(carbon): fix multiple checkbox by correctly passing event

packages/react-renderer-demo/src/doc-components/examples-texts/carbon/select.md
My Mac loves to produce this stupid space that is not a space.
=> Fix wrong space character in demo

packages/carbon-component-mapper/src/files/select.js, packages/carbon-component-mapper/src/tests/select.test.js
backport of https://github.com/data-driven-forms/react-forms/pull/1092
=> feat(carbon): allow to group options in single select

packages/common/babel.config.js
Fixes wrong import paths for react-jss
=> fix(common): no default conversion for react-jss

packages/react-renderer-demo/src/components/component-example-text.js, packages/react-renderer-demo/src/components/component-example.js, packages/react-renderer-demo/src/doc-components/examples-texts/select.md, packages/react-renderer-demo/src/helpers/update-field-schema.js, packages/react-renderer-demo/src/pages/provided-mappers/select.js
Adds a simple system allowing us to offer more schema variants.
**After**
=> Add schemas variant for demo

packages/carbon-component-mapper/src/radio/radio.js
For some reasons it does not work with the "component: radio" which is pretty usual now. 😭
=> fix(carbon): do not send component in radio to not set type

packages/react-renderer-demo/src/pages/provided-mappers/dual-list-select.js
Adds a tree variant demo for PF4 dual list selector
=> Add tree variant for dual list select demo

package.json, packages/ant-component-mapper/package.json, packages/blueprint-component-mapper/package.json, packages/carbon-component-mapper/package.json, packages/common/package.json, packages/mui-component-mapper/package.json, packages/parsers/package.json, packages/pf4-component-mapper/package.json, packages/react-form-renderer/package.json, packages/react-renderer-demo/package.json, packages/suir-component-mapper/package.json, templates/component-mapper/package.json
- add homepage url
- add bugs url
=> Update repository attributes in package.json s

packages/react-renderer-demo/package.json, yarn.lock
Firebase deploy repeatedly failed because of "missing webpack".
=> Add webpack do dependencies list to fix firebase

packages/react-renderer-demo/src/pages/provided-mappers/mui-component-mapper.md
Part of #1139 
Adds a migration guide for MUI5, this is going straight to the master branch
=> Add migration guide for MUI5

packages/react-renderer-demo/src/pages/_document.js
- because we are using a gradient, it is hard to use a color that matches our app... but still better than the previous one
**Before**
**After**
=> Update color theme

packages/react-renderer-demo/package.json, packages/react-renderer-demo/src/pages/live-editor.js, yarn.lock
=> Update form builder to MUI5

packages/react-renderer-demo/src/components/component-example.js
Fixes some styling issues appeared after the migration.
**Before migration**
**After migration**
**After this PR**
=> Fix styling of component example page

packages/react-renderer-demo/src/components/component-mapper-bar.js, packages/react-renderer-demo/src/components/navigation/schemas/provider-mappers.schema.js, packages/react-renderer-demo/src/pages/provided-mappers/aws-northstar.md
See https://github.com/aws/aws-northstar/discussions/466
cc @mteichtahl
**After**
=> Add AWS Northstar component to documentation

packages/react-renderer-demo/src/components/component-example.js
=> Fix variant tab color

packages/mui-component-mapper/config/jest.setup.js, packages/mui-component-mapper/src/dual-list-select/dual-list-select.js, packages/mui-component-mapper/src/tests/dual-list-select.test.js, packages/mui-component-mapper/src/tests/form-fields.test.js, packages/mui-component-mapper/src/tests/form-template.test.js, packages/mui-component-mapper/src/tests/plain-text.test.js, packages/mui-component-mapper/src/tests/subform.test.js, packages/mui-component-mapper/src/tests/tabs.test.js
=> Replace Enzyme with RTL in MUI

packages/ant-component-mapper/config/jest.setup.js, packages/ant-component-mapper/src/tests/checkbox.test.js, packages/ant-component-mapper/src/tests/components.test.js, packages/ant-component-mapper/src/tests/dual-list-select.test.js, packages/ant-component-mapper/src/tests/field-array.test.js, packages/ant-component-mapper/src/tests/plain-text.test.js, packages/ant-component-mapper/src/tests/select.test.js, packages/ant-component-mapper/src/tests/slider.test.js, packages/ant-component-mapper/src/tests/subform.test.js, packages/ant-component-mapper/src/tests/tabs.test.js, packages/ant-component-mapper/src/tests/wizard.test.js
=> Convert ANT tests to RTL

packages/carbon-component-mapper/src/files/helper-text-block.d.ts, packages/carbon-component-mapper/src/files/helper-text-block.js, packages/carbon-component-mapper/src/files/time-picker-base.d.ts, packages/carbon-component-mapper/src/files/time-picker-base.js, packages/carbon-component-mapper/src/files/time-picker-date.d.ts, packages/carbon-component-mapper/src/files/time-picker-date.js, packages/carbon-component-mapper/src/files/time-picker-string.d.ts, packages/carbon-component-mapper/src/files/time-picker-string.js, packages/carbon-component-mapper/src/files/time-picker.d.ts, packages/carbon-component-mapper/src/files/time-picker.js, packages/carbon-component-mapper/src/files/time-pircker-date.d.ts, packages/carbon-component-mapper/src/tests/time-picker-string.test.js, packages/carbon-component-mapper/src/tests/time-picker.test.js, packages/react-form-renderer/src/form-renderer/enhanced-on-change.js, packages/react-form-renderer/src/tests/form-renderer/enhanced-on-change.test.js, packages/react-renderer-demo/src/doc-components/examples-texts/carbon/time-picker.md
This PR allows for the back port of the time picker component changes to v2.
=> Backport timepicker to v2

packages/blueprint-component-mapper/config/jest.setup.js, packages/blueprint-component-mapper/src/dual-list-select/dual-list-select.js, packages/blueprint-component-mapper/src/tests/checkbox.test.js, packages/blueprint-component-mapper/src/tests/components.test.js, packages/blueprint-component-mapper/src/tests/dual-list-select.test.js, packages/blueprint-component-mapper/src/tests/field-array.test.js, packages/blueprint-component-mapper/src/tests/plain-text.test.js, packages/blueprint-component-mapper/src/tests/select.test.js, packages/blueprint-component-mapper/src/tests/subform.test.js, packages/blueprint-component-mapper/src/tests/tabs.test.js, packages/blueprint-component-mapper/src/tests/wizard.test.js, packages/react-renderer-demo/src/doc-components/examples-texts/blueprint/dual-list-select.md
=> Convert blueprint tests to RTL

packages/carbon-component-mapper/config/jest.setup.js, packages/carbon-component-mapper/src/tests/checkbox.test.js, packages/carbon-component-mapper/src/tests/components.test.js, packages/carbon-component-mapper/src/tests/dual-list-select.test.js, packages/carbon-component-mapper/src/tests/field-array.test.js, packages/carbon-component-mapper/src/tests/plain-text.test.js, packages/carbon-component-mapper/src/tests/select.test.js, packages/carbon-component-mapper/src/tests/subform.test.js, packages/carbon-component-mapper/src/tests/switch.test.js, packages/carbon-component-mapper/src/tests/tabs.test.js, packages/carbon-component-mapper/src/tests/text-field.test.js, packages/carbon-component-mapper/src/tests/time-picker-string.test.js, packages/carbon-component-mapper/src/tests/time-picker.test.js, packages/carbon-component-mapper/src/tests/wizard.test.js
=> Convert Carbon enzyme tests to RTL

packages/suir-component-mapper/config/jest.setup.js, packages/suir-component-mapper/src/dual-list-select/dual-list-select.js, packages/suir-component-mapper/src/field-array/field-array.js, packages/suir-component-mapper/src/tests/dual-list-select.test.js, packages/suir-component-mapper/src/tests/field-array.test.js, packages/suir-component-mapper/src/tests/form-fields.test.js, packages/suir-component-mapper/src/tests/plain-text.test.js, packages/suir-component-mapper/src/tests/subform.test.js, packages/suir-component-mapper/src/tests/tabs.test.js, packages/suir-component-mapper/src/tests/wizard.test.js
=> Convert semantic tests to RTL

packages/react-renderer-demo/src/stackblitz-templates/mui-templates.js
=> Add LocalizationProvider to MUI template

packages/common/config/jest.setup.js, packages/common/src/tests/dual-list-select/dual-list-select.test.js, packages/common/src/tests/form-template/form-template.test.js, packages/common/src/tests/hooks/use-is-mounted.test.js, packages/common/src/tests/multiple-choice-list/multiple-choice-list.test.js, packages/common/src/tests/select/select.test.js, packages/common/src/tests/wizard/wizard.test.js
=> Convert common tests to RTL

packages/react-renderer-demo/src/components/cookie-modal.js, packages/react-renderer-demo/src/pages/_app.js, packages/react-renderer-demo/src/pages/_document.js
- GoogleTags are loaded after users agree to use cookies
=> Update cookie consent

packages/react-renderer-demo/src/pages/introduction.md
Updates introduction page to be more beginner friendly and more attractive.
=> Update introduction page

packages/pf4-component-mapper/src/select/select/select.js
Makes the PF4 select focusable
=> fix(pf4): make select focusable on keyboard

packages/react-renderer-demo/src/pages/schema/introduction.md
- Reorganized the language and improved the doc style. 
- Added one example in Introduction/component (required)/string.
```jsx
```
=> doc: revise schema/introduction

packages/react-renderer-demo/src/pages/input-meta.md, packages/react-renderer-demo/src/pages/schema/clear-on-unmount.md, packages/react-renderer-demo/src/pages/schema/cleared-value.md, packages/react-renderer-demo/src/pages/schema/constants.md, packages/react-renderer-demo/src/pages/schema/data-types.md, packages/react-renderer-demo/src/pages/schema/initialize-on-mount.md, packages/react-renderer-demo/src/pages/schema/resolve-props.md
Revised language and improved style of schema/fieldProperties.
```jsx
```
=> doc: revise schema/fieldProperties

packages/react-form-renderer/src/form-renderer/form-renderer.d.ts, packages/react-form-renderer/src/form-renderer/form-renderer.js, packages/react-form-renderer/src/tests/form-renderer/form-renderer.test.js, packages/react-renderer-demo/src/components/navigation/schemas/renderer.schema.js, packages/react-renderer-demo/src/pages/components/children.md, packages/react-renderer-demo/src/pages/components/renderer.md
- fix: respect of children prop to support subscribing to contexts through child components rather than only `FormTemplate` or fields.
- feat: optimized portability of `FormRender` by supporting `FormTemplate` pass prop through `FormTemplateProps`.
- feat: overridable form rendering by passing children as a render function.
Please include a summary of the change.
```jsx
// Children prop as ReactElement
const MyOtherChild = ({allowReset}) => {
const {onReset} = useFormApi()
return !allowReset ? null : (
<button onClick={() => onReset()}/>Reset</button>
)
}
<FormRenderer
FormTemplate={AuthFormTemplateComponent}
componentMapper={simpleComponentMapper}
onSubmit={handleFormSubmit}
schema={formSchema}
subscription={{values: true}}
clearOnUnmount
>
<MyOtherChild …
```
=> feat(react): pass props and child render props

packages/react-renderer-demo/src/pages/components/children.md, packages/react-renderer-demo/src/pages/components/renderer.md
Based on post-review comments of #1218
=> Fix the latest doc changes

packages/form-state-manager/src/manager-api/manager-api.ts, packages/form-state-manager/src/tests/utils/manager-api.test.js
=> fix(manager): submit error should make form invalid

packages/blueprint-component-mapper/demo/index.html, packages/blueprint-component-mapper/package.json, packages/blueprint-component-mapper/src/dual-list-select/dual-list-select.js, packages/blueprint-component-mapper/src/form-template/form-template.js, packages/blueprint-component-mapper/src/tests/components.test.js, packages/blueprint-component-mapper/src/tests/dual-list-select.test.js, packages/blueprint-component-mapper/src/tests/select.test.js, packages/react-renderer-demo/src/pages/provided-mappers/blueprint-component-mapper.md, packages/react-renderer-demo/src/stackblitz-templates/blueprint-templates.js, yarn.lock
Updates Blueprint to version 4
=> feat(blueprint): update blueprint to version 4

packages/form-state-manager/src/manager-api/manager-api.ts
Instead of calculating isEqual on each change, the function is calculated only when a field is being registered/unregistered
=> fix(manager): recalculate isEqual only when registering

packages/form-state-manager/src/manager-api/manager-api.ts
This fixes bugs when using form+field validators:
- valid is not resetted when there were previously set errors
- when there is a field error and the field has no validator, the error is cleared (previously set by form validator)
- fixed updating flatErrors by merging them with state.errors
**Before**
**After**
=> fix(manager): fix form validate performance

packages/react-renderer-demo/src/examples/components/examples/custom-wizard.js
After submit, the template is rerendered
=> Fix custom wizard example to template after submit

packages/ant-component-mapper/src/tests/dual-list-select.test.js, packages/blueprint-component-mapper/src/tests/dual-list-select.test.js, packages/carbon-component-mapper/src/tests/dual-list-select.test.js, packages/common/src/tests/dual-list-select/dual-list-select.test.js, packages/common/src/tests/select/select.test.js, packages/form-state-manager/src/compose-validators/compose-validators.ts, packages/form-state-manager/src/manager-api/manager-api.ts, packages/form-state-manager/src/tests/files/use-field.test.js, packages/form-state-manager/src/tests/utils/manager-api.test.js, packages/form-state-manager/src/tests/utils/validate.test.js, packages/form-state-manager/src/use-field/use-field.ts, packages/mui-component-mapper/src/tests/dual-list-select.test.js, packages/pf4-component-mapper/src/tests/dual-list-select.test.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, packages/suir-component-mapper/src/tests/dual-list-select.test.js
This fixes bugs found on documentation site:
- clearedValue is set only when field had an initial value
- debug is using `getState` to break references
- all async validators (field level/form level/submit level) should be using return instead of throw to return errors
=> [Manager] Little bug fixes

packages/form-state-manager/src/use-field/use-field.ts, packages/react-form-renderer/src/common-types/field.d.ts, packages/react-form-renderer/src/common-types/index.d.ts, packages/react-form-renderer/src/field-array/field-array.d.ts, packages/react-form-renderer/src/form-renderer/form-renderer.d.ts, packages/react-form-renderer/src/form-spy/form-spy.d.ts, packages/react-form-renderer/src/renderer-context/renderer-context.d.ts, packages/react-form-renderer/src/use-field-api/use-field-api.d.ts
Fixes #935
Changes to the usage of manager types, not DDF's.
=> [MANAGER] Fix(renderer): use types from manager

packages/common/babel.config.js, packages/mui-component-mapper/demo/index.js, packages/mui-component-mapper/package.json, packages/mui-component-mapper/src/date-picker/date-picker.d.ts, packages/mui-component-mapper/src/date-picker/date-picker.js, packages/mui-component-mapper/src/tests/form-fields.test.js, packages/mui-component-mapper/src/time-picker/time-picker.d.ts, packages/mui-component-mapper/src/time-picker/time-picker.js, packages/react-renderer-demo/src/examples/components/conditions/is-function.js, packages/react-renderer-demo/src/pages/editor/live-editor.md, packages/react-renderer-demo/src/stackblitz-templates/mui-templates.js, yarn.lock
Fixes #1284 
Fixes imports because date pickers would no more be available in @mua/lab
@Hyperkid123
=> Migrate MUI date pickers to x-date-pickers

packages/common/babel.config.js
=> fix(mui): fix date pickers import

packages/react-renderer-demo/package.json, packages/react-renderer-demo/src/components/editor.js, packages/react-renderer-demo/src/pages/editor/live-editor.md, yarn.lock
Returns and updates editor to Demo
=> Return editor to Demo

packages/react-renderer-demo/package.json, packages/react-renderer-demo/src/examples/components/conditions/is-function.js, packages/react-renderer-demo/src/stackblitz-templates/mui-templates.js
=> Fix docs datepickers imports

package.json, yarn.lock
=> Update react types requirements

packages/ant-component-mapper/src/wizard/wizard.js
=> fix(atn): fix wizard onCancel typo

packages/common/src/select/select.js, packages/common/src/tests/select/select.test.js, packages/mui-component-mapper/src/select/select.js
Fixes #1366
Memoize select array values to prevent MUI search input value reset
=> Fix mui select

packages/react-form-renderer/src/condition/condition.js
=> fix(renderer): fix proptypes for is function

packages/react-form-renderer/src/form-renderer/render-form.js
Ref: https://github.com/data-driven-forms/react-forms/issues/1385
=> fix(react-form-renderer): Add subscription to 'initial' in ConditionTriggerDetector

packages/react-form-renderer/src/condition/condition.js, packages/react-form-renderer/src/tests/form-renderer/condition.test.js
Fixes #1390 
- React.memo was caching the field based on condition/values. I rewrote the logic to not cache the whole component but only the result of the parse condition function
Performance should stay unaffected as well
see issue
=> fix(condition): Remove useMemo and parse condition on change

packages/react-renderer-demo/src/components/common/doc-link.js, packages/react-renderer-demo/src/components/component-example.js
[Fix] #1393
Fixing links/button colors to be black.
=> fixing colors for links and buttons

packages/pf4-component-mapper/src/wizard/wizard.js
Fixes missing CSS in PF4 wizard in modal
=> fix(pf4): Add modal form class for PF4 wizard.

packages/pf4-component-mapper/demo/index.js, packages/pf4-component-mapper/src/slider/slider.js, packages/pf4-component-mapper/src/text-field/text-field.js, packages/pf4-component-mapper/src/textarea/textarea.js, packages/pf4-component-mapper/src/time-picker/time-picker.js, packages/pf4-component-mapper/src/wizard/wizard.js
First pass at resolving some issues noticed on the PF demo page while migrating to the PF5 components.
```jsx
```
=> fix(pf4): clean up errors and functional issues noticed on pf demo page

packages/react-renderer-demo/src/pages/schema/number-value-validator.md
Update a number value validation example (threshold / value).
=> Update documentation:  number value validation example

packages/react-renderer-demo/src/components/code-example.js
=> fix(docs): update codesandbox code template

packages/common/src/dual-list-select/dual-list-select.js
Update filter options to be case insensitive
Please include a summary of the change.
Update filter options to be case insensitive
```jsx
```
=> feat(mui5):Update filter options to case insensitive

package.json, packages/react-form-renderer/src/parse-condition/parse-condition.js, packages/react-form-renderer/src/tests/form-renderer/render-form.test.js, yarn.lock
Fixes #1478
The `isEmptyValue` needs a special handler for `Date` objects
=> fix(renderer): handle isEmpty for Date value
