- packages/pf4-component-mapper/package.json
This should get rid of build warnings
> fix(PF4 mapper): fixed pf4/react-core peer dependency.

- packages/pf3-component-mapper/src/form-fields/form-fields.js
- packages/pf3-component-mapper/src/form-fields/layout-components.js
- packages/pf3-component-mapper/src/form-fields/multiple-choice-list.js
- packages/pf3-component-mapper/src/form-fields/switch-field.js
- packages/pf3-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
- packages/pf3-component-mapper/src/tests/__snapshots__/multiple-choice-list.test.js.snap
- packages/pf3-component-mapper/src/tests/form-fields/__snapshots__/select.test.js.snap
- packages/pf3-component-mapper/src/tests/layout-components.test.js
- packages/pf4-component-mapper/demo/index.html
- packages/pf4-component-mapper/src/tests/__snapshots__/tabs.test.js.snap
- packages/pf4-component-mapper/src/tests/tabs.test.js
Makes all form vertical by default.
* removes `COL` component 
WIP because design is not clear.
@terezanovotna How should switch/checkboxes/radios look in a vertical form?
cc @martinpovolny @Hyperkid123
> feat(layout): makes PF3 forms vertical

- .travis.yml
- packages/pf3-component-mapper/src/form-fields/tabs.js
- packages/pf3-component-mapper/src/tests/__snapshots__/tabs.test.js.snap
- packages/pf3-component-mapper/src/tests/tabs.test.js
- packages/pf4-component-mapper/package.json
- packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard-step.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/react-renderer-demo/src/demo-data/wizard-schema.js
- packages/react-renderer-demo/src/editor-demo/common/examples-definitions.js
- packages/react-renderer-demo/src/editor-demo/common/examples-texts/tabs.js
- packages/react-renderer-demo/src/editor-demo/common/examples-texts/wizard.js
- removed demo publish condition
- we will publish everything to demo site 
- addressed visual feedback on PF4 wizard
- for wizard buttons customization added option to specify custom CSS class
- added option to customize controls text
- next button is disabled until current step is valid
- adjusted sizes of default Wizard and Step titles
- Added visual feedback for invalid tab content for PF3 tabs
- user can add a list of validated fields
- no simple way to handle this by default (schema is too flexible)
> Update pf4 wizard pf3 tabs

- packages/pf3-component-mapper/src/form-fields/tabs.js
- packages/pf3-component-mapper/src/tests/__snapshots__/tabs.test.js.snap
- packages/pf3-component-mapper/src/tests/tabs.test.js
When using scoped field names tabs validation was not working.
```javascript
name: 'field.nested' // in form state {field: { nested: 'value' }}
```
Before it was directly accessing `{"field.nested": "value"}`. Fixed by using lodash `get` function on object.
> fix(PF3: tabs): fixed scoped fields validation

- packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard-step.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard-styles.scss
- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard-step.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- packages/react-renderer-demo/src/editor-demo/common/examples-texts/wizard.js
- packages/react-renderer-demo/src/vendor.scss
- updates wizard according to PF4 component (however, it isn't using the component!)
**Props**
| Props  | Type | Default |  Decription |
| ------------- | ------------- | ------------- | ------------- |
| fields  | array  |   |   |
| isCompactNav  | bool  |   |  |
| setFullWidth  | bool  |   |   |
| setFullHeight  | bool  |   |   |
| isDynamic  | bool  |   |  |
| title  | node  |   |   |
| buttonsClassName  | string  |   |   |
| buttonLabels | object  |   |   |
| description  | node  |   |  |
**How to do substeps**
Field in Wizard fields should contain `substep` <`string`> which is title of the primary step. Steps with the same substep are combined together in the primary step.
**First step**
First step should have `stepKey: 1`
**Variants of Wizard**
**Simple wizard**
- …
> feat(pf4wizard): update according to PF4

- packages/react-form-renderer/src/tests/validators/validators.test.js
- packages/react-form-renderer/src/validators/validator-mapper.js
There was a bug causing false value assignment to validator arguments. The OR statement caused the deprecated value to be always assigned.
> fix(react renderer): Fixed length validators value assignment.

- packages/mui-component-mapper/config/webpack.config.js
Externals for MUI package was not configured properly. It was causing styling overrides when used in consumer app.
> Fixed MUI mapper externals

- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/form-renderer/index.js
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
solves: #50 
@rvsia we should add this prop to the document renderer API issue.
- allows adding a callback which is triggered on every state update and sends the form state as an argument.
> fix(renderer): added formSpy option to export form state.

- packages/pf4-component-mapper/src/form-fields/select/select.js
- packages/pf4-component-mapper/src/tests/select/select.test.js
- basically same implementation as a PF3 async select
- `loadOptions` to provide a function which loads options
- `loadingMessage` to provide a text during loading 
**Schema to test**
```jsx
{
name: 'async_sselect',
component: components.SELECT,
loadOptions: () => new Promise((resolve) => {
setTimeout(() => {
resolve(options);
}, 3000);
}),
loadingMessage: 'Nacitam se, kamo.',
label: 'Cool Label',
},
```
> fix(pf4Select): make async variant

- packages/pf3-component-mapper/src/form-fields/button.js
- packages/pf3-component-mapper/src/form-fields/form-fields.js
- packages/pf3-component-mapper/src/form-fields/layout-components.js
- packages/pf3-component-mapper/src/form-fields/multiple-choice-list.js
- packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/form-fields/multiple-choice-list.js
- packages/pf4-component-mapper/src/form-fields/select/select.js
- packages/pf4-component-mapper/src/form-fields/tabs.js
- packages/pf4-component-mapper/src/tests/select/select.test.js
fixes: #40 
- removed anonymous components from pf3 mapper
- will now show component names in DOM properly
- fixed missing prop types
- fixed invalid prop types definitions in pf4 select component
> Remove anonymous components

- __mocks__/mock-layout-mapper.js
- packages/react-form-renderer/src/constants/index.js
- packages/react-form-renderer/src/form-renderer/enhanced-on-change.js
- packages/react-form-renderer/src/form-renderer/field-provider.js
- packages/react-form-renderer/src/form-renderer/render-form.js
- packages/react-form-renderer/src/index.js
- packages/react-form-renderer/src/parsers/default-schema-validator.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/data-types.test.js
- packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap
- packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
- packages/react-form-renderer/src/validators/index.js
- packages/react-renderer-demo/src/common/doc-texts/validators.js
- packages/react-renderer-demo/src/common/documenation-pages.js
- packages/react-renderer-demo/src/editor-demo/common/doc-texts/data-types.js
- packages/react-renderer-demo/src/editor-demo/docs-components/data-types.md
- packages/react-renderer-demo/src/editor-demo/docs-components/data-types/data-types-example.js
closes: #65 
Adds data types casting to form fields (both default and custom)
- enhances FieldProvider `onChange` function with type casting if the `dataType` prop has been given
- supported data types
- integer
- float
- number
- boolean
- string
> Data types feature

- packages/react-renderer-demo/src/common/md-helper/index.js
- packages/react-renderer-demo/src/common/md-helper/mdx-components.js
Sorry, didn't test https://github.com/data-driven-forms/react-forms/pull/79 properly yesterday. :sob: :crab: 
Without `display: block` it does not work.
**Before**
**After**
> Fix anchor css styles

- packages/react-form-renderer/src/form-renderer/enhanced-on-change.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/enhanced-on-change.test.js
Form onChange was missing field type checking for checkboxes.
> fix(renderer): fixed onChange for single checkbox.

- packages/pf4-component-mapper/demo/demo-schemas/sandbox.js
- packages/pf4-component-mapper/src/form-fields/select/clear-indicator.js
- packages/pf4-component-mapper/src/form-fields/select/select-styles.scss
- packages/pf4-component-mapper/src/form-fields/select/select.js
Padding on single select was off
Before:
After:
Fixed clear able button margin:
> fix(pf4): Select styling.

- packages/pf3-component-mapper/src/form-fields/select/index.js
- packages/pf3-component-mapper/src/tests/form-fields/__snapshots__/select.test.js.snap
- packages/pf3-component-mapper/src/tests/form-fields/select.test.js
Empty props was overwriting state when async options.. because of new repo, it is not possible to track when it got broken. :ghost: 
Thanks @andyvesel for reporting!
> fix(pf3select): props options was overwriting state

- packages/pf3-component-mapper/demo/index.js
- packages/pf3-component-mapper/src/form-fields/layout-components.js
- packages/pf3-component-mapper/src/form-fields/layout-components.scss
- packages/pf3-component-mapper/src/tests/layout-components.test.js
- packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
- packages/react-form-renderer/src/form-renderer/index.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/array-form-component.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-information.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
Fixes pf3 buttons alignment. Swapped ButtonGroup with flex layout.
> fix(pf3): using flex-layout instead of float in pf3-form group.

- packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js
- packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- packages/react-renderer-demo/src/docs-components/pf4-wizard.md
Allow to use custom buttons components for each step (and the component is provided with all parts to be able to implement its own buttons)
**Schema**
```jsx
const Buttons = () => <div>Hello</div>;
[{
title: 'foo-step',
stepKey: '1',
name: 'foo',
buttons: Buttons,
fields: [{
name: 'foo-field',
}],
nextStep: '2',
}]
```
It will allow to do crazy things like this:
TODO
> feat(pf4wizard): Allow custom buttons for steps

- packages/pf3-component-mapper/demo/demo-schemas/sandbox.js
- packages/pf3-component-mapper/src/form-fields/date-time-picker/date-time-picker.js
- packages/pf3-component-mapper/src/form-fields/date-time-picker/helpers.js
- packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/helpers.test.js
- packages/react-renderer-demo/src/docs-components/component-api.md
closes #150
- strings can be now used to define disabled days for date picker, any string can be used as long as its accepted by Date constructor
- added alias `today` which is equal to `new Date()`
> Allow strings for disabled days time picker

- packages/pf3-component-mapper/src/form-fields/form-fields.js
- packages/pf3-component-mapper/src/tests/form-fields.test.js
closes https://github.com/data-driven-forms/react-forms/issues/127
`helperText` > icon popover
`description` > Help block
Before
After
> fix(pf3): use fieldLevelHelp for helperText

- packages/pf3-component-mapper/src/form-fields/select/index.js
- packages/pf3-component-mapper/src/tests/form-fields/select.test.js
Fixes re-loading when `options`, `loadOptions` are changed (and clears the input value if the new options do not include the value)
**After**
> fix(pf3): async options reload

- packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard-step.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard-step.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/wizard-step.test.js
- packages/react-renderer-demo/src/docs-components/pf4-wizard.md
closes https://github.com/data-driven-forms/react-forms/issues/151
Adds these:
| Prop  | Type | Default |  Decription |
| ------------- | ------------- | ------------- | ------------- |
|showTitles|bool|undefined|If true, step titles will be shown in the wizard body|
| Props  | Type  |  Decription |
| ------------- | ------------- | ------------- |
|showTitle|bool|If true, step titles will (not if false) be shown in the wizard body|
|Custom title|node|Use if you want to render as the title different/custom title (for example, title with a popover|
> feat(pf4wizard): show titles

- packages/mui-component-mapper/src/form-fields/sub-form.js
- packages/pf3-component-mapper/src/form-fields/sub-form.js
- packages/pf3-component-mapper/src/tests/__snapshots__/sub-form.test.js.snap
- packages/pf4-component-mapper/src/form-fields/sub-form.js
- packages/pf4-component-mapper/src/tests/__snapshots__/sub-form.test.js.snap
Allows subform to receive all props, it wasn't possible to add `className` before. 
I need to customize subforms in Sources.
> fix(subform): allow to receive other props

- packages/pf3-component-mapper/demo/demo-schemas/sandbox.js
- packages/pf3-component-mapper/src/form-fields/select/select-styles.js
closes #160
For some reason normal form input with selector `.input-group .form-control` has z-index value of 2.
Since there is probably some reason for it and removing that might break everything, I just added higher value to select menu.
> fix(pf3): give select menu higher z-index than input.

- packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- packages/react-renderer-demo/src/docs-components/pf4-wizard.md
Back to the future with PF4 wizard!
- jumping back on a step with compile mapper will disable jumping forward
- jumping can be disabled by a prop `disableForwardJumping`
- it's opt-in, wizard has to get `predictSteps` prop to predict the steps in the navigation
- Adds props
**Wizard**
| Prop  | Type | Default |  Decription |
| ------------- | ------------- | ------------- | ------------- |
|predictSteps|bool|undefined|If true, dynamic wizard will predict steps in the navigation.|
**Wizard step**
| Props  | Type  |  Decription |
| ------------- | ------------- | ------------- |
|disableForwardJumping|bool|When use return to this step, jumping forward in the navigation is disabled.| 
Predicting
Disable jumping forward
> feat(pf4): predict the future in the wizard nav

- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- Nav is being disabled in dynamic wizard instead of disappearing (it looks really bad in Sources UI and it was inconsistent, when jumped into the step, the nav disappears, however after clicking on back it appears again (because nav builder was able to find value))
Before
After
- Refactored the whole `jumping` logic, it was really hard to orientate in it and the number logic (count vs indexing by zero) sometimes fails
> fix(pf4wizard): refactor and fix number logic

- packages/pf3-component-mapper/src/form-fields/layout-components.js
- packages/pf3-component-mapper/src/tests/layout-components.test.js
Changes `h3` PF3 title to `h1`
see https://github.com/data-driven-forms/react-forms/pull/172
> fix(pf3title): make it <h1 />

- packages/react-form-renderer/src/tests/validators/validators.test.js
- packages/react-renderer-demo/src/docs-components/component-mapper/form-fields-mapper.js
- packages/react-renderer-demo/src/docs-components/validators/length-validators.js
> Fix typo lenght => length

- packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js
- packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js
- packages/react-renderer-demo/src/docs-components/pf4-wizard.md
- simplifies `nextStep` button (with `formOptions` there is no need to use `fieldProvider`)
- allow to use custom function in the `nextStep` object (instead of coming up with some crazy JSON syntax)
**Docs**
- another option is to use custom function. The custom function receives as the first argument an object with values and the function has to return a `stepKey` in string.
```jsx
nextStep: ({ values }) => (values.aws === '123' &&& values.password === 'secret') ? 'secretStep' : 'genericStep'
```
> feat(pf4wizard): allow functions in nextStep object

- packages/pf3-component-mapper/demo/demo-schemas/sandbox.js
- packages/react-form-renderer/src/form-renderer/enhanced-on-change.js
- packages/react-form-renderer/src/tests/form-renderer/enhanced-on-change.test.js
closes #187 
On change callback was converting arrays instead of the items if those arrays
```jsx
["1"] => /*1 instead of*/ ["1"] => [1]
```
> fix(common): fixed data type conversion of array values.

- packages/pf3-component-mapper/demo/demo-schemas/sandbox.js
- packages/pf3-component-mapper/src/form-fields/date-time-picker/date-time-picker.js
- packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/date-time-picker.test.js
closes #189 
Day picker can now accept value as a string.
> fix(pf3): stop date picker crash when value is string.

- packages/pf3-component-mapper/demo/demo-schemas/sandbox.js
- packages/react-form-renderer/src/parsers/default-schema-validator.js
- packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
closes #174
This was an issue only in schema validator. Renderer does not use validate property if it is not an array.
> fix(renderer): Allow undefined value for validate attribute in schema.

- packages/mui-component-mapper/size-snapshot.json
- packages/pf3-component-mapper/size-snapshot.json
- packages/pf4-component-mapper/size-snapshot.json
- packages/react-form-renderer/size-snapshot.json
- these files should not be longer tracked
The problem is the files have been already tracked by git, so I ran `git rm --cached` over them
> Remove size-snapshot from git

- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/form-fields/wizard/step-buttons.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard-step.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js
- packages/pf4-component-mapper/src/tests/wizard/wizard-step.test.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
Follow-up of https://github.com/data-driven-forms/react-forms/pull/202
pF4 wizard cancel button now pass formValues
> fix(pf4wizard): onCancel button receives formValues

- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
Missed that onClose icon button needs values as well :(
> fix(pf4wizard): pass formValues to onClose icon cancel action

- packages/react-renderer-demo/src/app/src/doc-components/pf4-wizard.md
During the migration to NextJS, the latest changes to PF4 Wizard documentation were lost.
Now, they are back!
> Update PF4 wizard doc

- packages/react-renderer-demo/src/app/src/components/navigation/mapper.js
- left nav in demo was missing href tag
- next js does not propagate its props to anything other than anchors
> Added href links to left nav

- packages/pf4-component-mapper/src/form-fields/select/select-styles.scss
- packages/pf4-component-mapper/src/form-fields/select/select.js
- packages/pf4-component-mapper/src/tests/select/select.test.js
- packages/react-renderer-demo/src/app/src/doc-components/pf4-select.md
Use `menuIsPortal` prop to enable it. portal is appended to body element.
> fix(pf4 select): Added prop that enables select menu portaling

- packages/pf3-component-mapper/src/form-fields/date-time-picker/intervals.js
- packages/pf3-component-mapper/src/form-fields/date-time-picker/navbar.js
- packages/pf3-component-mapper/src/form-fields/date-time-picker/year-selector.js
- packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/__snapshots__/year-selector.test.js.snap
closes #254
I tried to integrate the official PF3 datetimepicker to DDF, but it looks like a lot more work than I expected... so here is a fix for the buttons issue.
**Before**
**After**
> fix(pf3): datetimepickers buttons do not show texts

- packages/react-renderer-demo/src/app/src/components/docsearch.js
This appends hash to algolia suggestions.
> Use hash when searching

- packages/pf3-component-mapper/src/form-fields/form-fields.js
- packages/pf3-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
- packages/pf3-component-mapper/src/tests/form-fields.test.js
closes #250 
Adds helperText to single checkbox variant
> fix(pf3): add helpertext to single checkbox

- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
PF4 Wizard wasn't submitting formOptions/formApi as the second argument
> fix(pf4): send formOptions as second argument in wizard

- packages/react-renderer-demo/src/app/pages/component-example/checkbox-multiple.js
- packages/react-renderer-demo/src/app/pages/component-example/checkbox-multiple.md
- packages/react-renderer-demo/src/app/pages/component-example/checkbox.js
- packages/react-renderer-demo/src/app/pages/component-example/checkbox.md
- packages/react-renderer-demo/src/app/pages/component-example/date-picker.js
- packages/react-renderer-demo/src/app/pages/component-example/date-picker.md
- packages/react-renderer-demo/src/app/pages/component-example/plain-text.js
- packages/react-renderer-demo/src/app/pages/component-example/plain-text.md
- packages/react-renderer-demo/src/app/pages/component-example/radio.js
- packages/react-renderer-demo/src/app/pages/component-example/radio.md
- packages/react-renderer-demo/src/app/pages/component-example/select-field.js
- packages/react-renderer-demo/src/app/pages/component-example/select-field.md
- packages/react-renderer-demo/src/app/pages/component-example/sub-form.js
- packages/react-renderer-demo/src/app/pages/component-example/sub-form.md
- packages/react-renderer-demo/src/app/pages/component-example/switch-field.js
- packages/react-renderer-demo/src/app/pages/component-example/switch-field.md
- packages/react-renderer-demo/src/app/pages/component-example/tabs.js
- packages/react-renderer-demo/src/app/pages/component-example/tabs.md
- packages/react-renderer-demo/src/app/pages/component-example/text-field.js
- packages/react-renderer-demo/src/app/pages/component-example/text-field.md
- packages/react-renderer-demo/src/app/pages/component-example/textarea-field.js
- packages/react-renderer-demo/src/app/pages/component-example/textarea-field.md
- packages/react-renderer-demo/src/app/pages/component-example/time-picker.js
- packages/react-renderer-demo/src/app/pages/component-example/time-picker.md
- packages/react-renderer-demo/src/app/pages/component-example/wizard.js
- packages/react-renderer-demo/src/app/pages/component-example/wizard.md
- packages/react-renderer-demo/src/app/src/components/component-example.js
- Component pages are converted into MDX
- Header is set in the MDX, not in the component itself
Should help Algolia to crawl these pages
> Convert component examples to mdx

- README.md
- packages/pf3-component-mapper/demo/index.js
- packages/pf3-component-mapper/src/tests/wizard.test.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap
- packages/react-form-renderer/README.md
- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/form-renderer/index.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-information.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/form-renderer.test.js
- packages/react-renderer-demo/src/app/pages/renderer/renderer-api.md
- packages/react-renderer-demo/src/app/src/components/navigation/schema.js
- removes `formType`
- removes ability to parse different schemas (parsers could be exported separately)
- removes `resetAble` formType
> Clean obsolete props in formRenderer

- packages/react-renderer-demo/src/app/pages/_app.js
- packages/react-renderer-demo/src/app/pages/component-example/checkbox-multiple.md
- packages/react-renderer-demo/src/app/pages/component-example/checkbox.md
- packages/react-renderer-demo/src/app/pages/component-example/date-picker.md
- packages/react-renderer-demo/src/app/pages/component-example/plain-text.md
- packages/react-renderer-demo/src/app/pages/component-example/radio.md
- packages/react-renderer-demo/src/app/pages/component-example/select-field.md
- packages/react-renderer-demo/src/app/pages/component-example/sub-form.md
- packages/react-renderer-demo/src/app/pages/component-example/switch-field.md
- packages/react-renderer-demo/src/app/pages/component-example/tabs.md
- packages/react-renderer-demo/src/app/pages/component-example/text-field.md
- packages/react-renderer-demo/src/app/pages/component-example/textarea-field.md
- packages/react-renderer-demo/src/app/pages/component-example/time-picker.md
- packages/react-renderer-demo/src/app/pages/component-example/wizard.md
- packages/react-renderer-demo/src/app/src/common/examples-texts/select.js
- packages/react-renderer-demo/src/app/src/components/component-example-text.js
- packages/react-renderer-demo/src/app/src/components/component-example.js
- is possible to use query param to switch the active mapper (you can share the link!)
- specific text for each mapper is rendered on first render => better algolia support
- reworked grids - on smaller screens each of the three boxes takes all 12 columns
- add spinner when editor is being loaded
> ComponentExample cleanup

- .circleci/config.yml
commit-analyzer supports only TRAVIS
https://github.com/karelhala/commit-analyzer-wildcard/blob/00e93203765c9956b8f7efa718c8d3e32cd42db9/packages/release-notes/analyzer.js#L46
So, we need to add this environment variable to CircleCI to properly create links in release notes
> Set TRAVIS_REPO_SLUG in Circle_CI

- __mocks__/mock-layout-mapper.js
- packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap
- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/form-renderer/form-controls.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-controls.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-information.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/data-types.test.js
fixes https://github.com/data-driven-forms/react-forms/issues/292
OnClick is removed from the submit button, as the submit event is already included in form.
This breaks some tests as jest cannot call parents' events.
> fix(renderer): prevent double submitting by button

- packages/mui-component-mapper/src/form-fields/form-fields.js
- packages/mui-component-mapper/src/form-fields/sub-form.js
- packages/pf3-component-mapper/src/form-fields/form-fields.js
- packages/pf3-component-mapper/src/form-fields/sub-form.js
- packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/form-fields/fieldArray/index.js
- packages/pf4-component-mapper/src/form-fields/form-fields.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard-nav.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/wizard-nav.test.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- packages/react-form-renderer/src/form-renderer/field-wrapper.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap
- packages/react-renderer-demo/src/app/pages/renderer/field-provider.md
- packages/react-renderer-demo/src/app/src/doc-components/pf4-wizard.md
PF4 Wizard is now able to generate the schema in a realtime. It just needs to get a list of names, that can change next steps of the wizard.
Also, FormSpy is passed to all components as a FormSpyProvider.
TODO:
**docs**
**Crossroads**
With the help of `crossroads` you can manually defined which fields change next steps and together with `predictSteps`, it will cause that the wizard navigation is always refreshed, when one of the crossroads name is changed.
Ex.: `crossroads: ['name', 'nested.password']`
| Prop  | Type | Default |  Description |
| ------------- | ------------- | ------------- | ------------- |
|crossroads|array|undefined|Array of field names, which change next steps|
> feat(pf4): wizard predicts nextSteps in realtime

- packages/react-renderer-demo/src/app/pages/renderer/field-provider.md
- packages/react-renderer-demo/src/app/pages/renderer/get-started.md
- packages/react-renderer-demo/src/app/pages/renderer/installation.md
- fixes one page where header was above the table of contents
- adds tables of contents where missing
**Before**
**After**
> Add and fix table of contents where missing

- packages/react-renderer-demo/package.json
- packages/react-renderer-demo/src/app/pages/releases.js
- packages/react-renderer-demo/src/app/src/components/navigation/schema.js
- yarn.lock
Adds `Releases` page with data obtained by the GitHub's API
> Add releases page to demo

- config/jest.setup.js
- packages/pf4-component-mapper/src/form-fields/wizard/wizard-step.js
For instance, when there are two step that are too long for the wizard container (e.g. too many fields) and are next to each other. If you scroll down in one of them and switch to the other, the
location of your scroll bar won't reset to the top but will stay at the bottom.
This is bad because the user expects the scroll bar to go back to the top of the next step.
//cc @rvsia
> fix(pf4): scroll to top on switching to a different step

- __mocks__/mock-form-template.js
- packages/common/src/form-template.js
- packages/pf4-component-mapper/src/components/wizard.js
- packages/pf4-component-mapper/src/tests/__snapshots__/form-template-common.test.js.snap
- packages/pf4-component-mapper/src/tests/field-array/__snapshots__/field-array.test.js.snap
- packages/pf4-component-mapper/src/tests/form-template-common.test.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/react-form-renderer/demo/form-template.js
- packages/react-form-renderer/src/components/form-renderer.js
- packages/react-form-renderer/src/components/form-spy.js
- packages/react-form-renderer/src/components/form.js
- packages/react-form-renderer/src/form-renderer/field-wrapper.js
- packages/react-form-renderer/src/index.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap
```jsx
import { FormSpy } from '@data-driven-forms/react-form-renderer';
```
> feat(FormSpy): export formSpy instead of passing it as a prop

- packages/react-renderer-demo/src/app/pages/releases.js
- GitHub's API has limit for request from one IP address
> Add fallback for releases

- packages/common/src/form-template.js
- packages/pf4-component-mapper/src/tests/form-template-common.test.js
- packages/react-form-renderer/src/components/form-renderer.js
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
user can do it in formTemplate (all mappers' default formTemplates support it)
Custom implementation in formTemplates:
```jsx
import { FormSpy } from '@data-driven-forms/react-form-renderer';
{onStateUpdate && <FormSpy onChange={onStateUpdate} />}
```
> [V2] feat(renderer): remove onStateUpdate prop

- packages/react-form-renderer/src/form-renderer/condition.js
- packages/react-form-renderer/src/parsers/default-schema-validator.js
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
- packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap
- packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
- packages/react-renderer-demo/src/app/pages/renderer/condition.md
- Fixes string support in conditions
- adds flags as a another argument
Supports:
```jsx
condition: {
when: 'Foo',
pattern: 'bar',
flags: 'i'
}
```
> fix(renderer): add support for string pattern and flags

- packages/pf3-component-mapper/src/tests/__snapshots__/input-addon.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/react-form-renderer/demo/form-fields-mapper.js
- packages/react-form-renderer/src/components/form-renderer.js
- packages/react-form-renderer/src/form-renderer/render-form.js
- packages/react-form-renderer/src/parsers/default-schema-validator.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
- packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap
- packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
- packages/react-form-renderer/src/tests/validators/validators.test.js
- packages/react-form-renderer/src/validators/validator-mapper.js
Allows to use a custom validator mapper
```jsx
const customValidatorMapper = {
custom: () => (value) => value > 6 ? 'Value is bigger than 6' : undefined
}
fields: [{
name: 'name',
validate: [{type: 'custom'}]
}]
}
<FormRenderer 
...
schema={schema}
validatorMapper={customValidatorMapper}
/>
```
- This mapper is merged with the default one (user can rewrite the default ones)
- schemaValidator still controls if the type is in validatorMapper (even the custom ones!)
(and as a bonus, empty validation is no longer passed as a prop!)
> [V2] Validator mapper

- packages/react-form-renderer/src/form-renderer/enhanced-on-change.js
- packages/react-form-renderer/src/tests/form-renderer/enhanced-on-change.test.js
When setting initialValue on `checkbox` type fields, the `checkEmpty` method always returns `true`, so the value is set to `clearedValue` (which is `undefined`)
Fixed by setting that a `boolean` value is never empty.
> fix(renderer): boolean is never empty

- packages/react-form-renderer/src/form-renderer/field-provider.js
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
- Fixes falsy values set in initialValue + initializeOnMount
When a field is mounted first time, initialValue is registered into the form state. So, falsy values work well. However, if truly value is registered first, falsy value is not able to override it as the condition in  fieldProvider thinks that the initialValue is not set at all.
```jsx
fields: [{
component: components.TEXT_FIELD,
name: 'input',
}, {
component: components.TEXT_FIELD,
name: 'unmounted',
initialValue: false,
initializeOnMount: true,
condition: {
when: 'input',
is: 'show_false',
},
}, {
component: components.TEXT_FIELD,
name: 'unmounted',
initialValue: true,
initializeOnMount: true,
condition: {
when: 'input',
is: 'show_true',
},
}],
};
```
1. user sets 'show_false'
-> formState's initialValue is set …
> Fixes falsy values for initialValue + initiliazeOnMount

- packages/react-renderer-demo/src/app/src/components/navigation/examples-definitions.js
Components wrapped in a form group now share the same basic set of variants in components examples
> Add shared variants form demo examples

- packages/mui-component-mapper/src/form-fields/form-fields.js
- yarn.lock
The mui text field label position was distorted due to the absolute positioning. Added relative position to its container to make it properly position itself.
> fix(mui): Add relative position to field wrapper.

- packages/pf3-component-mapper/src/tests/__snapshots__/input-addon.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/components/form-renderer.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
onStateUpdate prop is removed from the renderer, instead of it use debug (please see [Final Form Documentation)](https://final-form.org/docs/react-final-form/types/FormProps#debug)
```jsx
<FormRenderer {...} debug={console.log} />
```
> [V2] feat(renderer): use debug instead of onStateUpdate

- packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js
- packages/pf4-component-mapper/src/components/wizard.js
- packages/pf4-component-mapper/src/components/wizard/reducer.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- packages/react-renderer-demo/src/app/pages/renderer/migration-guide.md
- packages/react-renderer-demo/src/app/src/doc-components/pf4-wizard.md
Removes predictSteps from PF4 wizard. It's always true. (There is no reason to not show all steps in the navigation, when it's possible.)
> fix(pf4): wizard predicts steps by default

- packages/react-renderer-demo/src/app/src/components/mdx/mdx-components.js
- removes the additional last line
- hides cursor
- hides lineNumbers (I don't think it's useful and it also makes the code examples harder to read)
Before
After
> Update CodeEditor options for md codes snippets

- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/components/form-renderer.js
- packages/react-form-renderer/src/index.js
- packages/react-form-renderer/src/parsers/default-schema-validator.js
- packages/react-form-renderer/src/tests/form-renderer/schema-validator-mapper.test.js
- packages/react-renderer-demo/src/app/pages/renderer/renderer-api.md
- packages/react-renderer-demo/src/app/pages/renderer/schema-validator.md
- packages/react-renderer-demo/src/app/src/components/navigation/documentation-pages.js
- packages/react-renderer-demo/src/app/src/doc-components/schema-validator.js
todo:
```jsx
import FormRenderer, { DefaultSchemaError } from '@data-driven-forms/react-form-renderer';
const schemaValidatorMapper = {
components: {
// schema validators for components
[component]: (field) => {
if(someError(field)) {
throw new DefaultSchemaError(`Error message in field ${field.name}`);
}
}
},
actions: {
// schema validators for actions
[actionName]: (action, fieldName) => {
if(someError(action)) {
throw new DefaultSchemaError(`Error message in field ${fieldName}`);
}
}
},
validators: {
// schema validators for validators
[validatorType]: (validator, fieldName) => {
if(someError(validator)) {
throw new DefaultSchemaError(`Error message in field ${fieldName}`);
}
}
}
}
...
<FormRenderer
{...props}
schemaValidatorMapper={schemaValidatorMapper}
/>
```
> [V2] feat(renderer): add schemaValidatorMapper

- packages/react-form-renderer/src/form-renderer/condition.js
- packages/react-form-renderer/src/parsers/default-schema-validator.js
- packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js
- packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap
- packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
- packages/react-renderer-demo/src/app/pages/renderer/condition.md
- packages/react-renderer-demo/src/app/src/doc-components/condition.js
Closes #390 
TODO: 
Is it alright @Hyperkid123 @skateman ? If so, I will finish it after the next meeting
Adds
- or
- and
- not
- can be nested
(All old conditions still work!)
Examples (look on the tests)
```js
condition = {
and: [
{ and: [{ when: 'x', pattern: /true/ }, { when: 'z', is: 'true' }]},
{ or: [{ when: 'y', pattern: /true/ }, { when: 'a', is: 'true' }]},
],
};
condition = {
or: [
{ not: { when: 'x', pattern: /true/ }},
{ not: { when: 'y', pattern: /true/ }},
{ not: { when: 'z', pattern: /true/ }},
],
};
```
> feat(renderer): add proper not, and, or conditions

- package.json
- packages/react-renderer-demo/package.json
- packages/react-renderer-demo/src/app/package.json
- yarn.lock
+ removing unused packages
I tried to update all non-design libraries, but it exploded :boom:
> Fix NEXT vulnerability

- .eslintignore
- packages/react-renderer-demo/.eslintrc.json
- packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/custom-component.js
- packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/dual-list-select.js
- packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/generic-mui-component.js
- packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/select.js
- packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/tabs.js
- packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/wizard.js
- packages/react-renderer-demo/src/app/src/doc-components/custom-buttons.js
- packages/react-renderer-demo/src/app/src/doc-components/get-started/get-started.js
> Enable linter in demo

- packages/react-form-renderer/package.json
- yarn.lock
Updates final form to prevents react update warnings
closes #419 
cc @dave-calleja
> fix(renderer): update final form deps

- packages/react-renderer-demo/src/app/pages/_document.js
- packages/react-renderer-demo/src/app/pages/index.js
- packages/react-renderer-demo/src/app/src/components/layout.js
- packages/react-renderer-demo/src/app/src/components/notification-panel.js
This PR adds a notification panel to demo
- last checked is stored in localStorage
- using MDX to format messages (can use links, etc.)
- messages are hard coded in the code
> Add notification panel to demo

- packages/react-renderer-demo/src/app/src/components/layout.js
- packages/react-renderer-demo/src/app/src/components/notification-panel.js
On the first render the last checked message is set to latest to not show empty badge.
Also, there is a enhancement which will count the right number of notifications, when we delete one of them. 
Before
After
> Fix notificiation counter on first render

- packages/mui-component-mapper/demo/demo-schemas/field-array-schema.js
- packages/mui-component-mapper/demo/index.js
- packages/mui-component-mapper/src/files/component-mapper.js
- packages/mui-component-mapper/src/files/field-array.js
- packages/mui-component-mapper/src/tests/field-array.test.js
- packages/react-renderer-demo/src/app/pages/component-example/field-array.js
- packages/react-renderer-demo/src/app/pages/renderer/dynamic-fields.md
- packages/react-renderer-demo/src/app/src/components/navigation/examples-definitions.js
- packages/react-renderer-demo/src/app/src/components/navigation/examples-texts/field-array.js
- packages/react-renderer-demo/src/app/src/components/navigation/field-array-schema.js
- packages/react-renderer-demo/src/app/src/doc-components/mui-field-array.md
- packages/react-renderer-demo/src/app/src/doc-components/pf3-field-array.md
- packages/react-renderer-demo/src/app/src/doc-components/pf4-field-array.md
Same as PF4
I have remove the `hr` from mockups, because it actually looks as an another MUI field. :smiley: 
+ Allows to revert `remove` actions
TODO:
closes #421
> fix(mui): add default field array

- packages/common/src/wizard/wizard.js
- packages/mui-component-mapper/src/files/plain-text.js
- packages/mui-component-mapper/src/files/sub-form.js
- packages/pf3-component-mapper/src/files/button.js
- packages/pf3-component-mapper/src/files/sub-form.js
- packages/pf3-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
- packages/pf3-component-mapper/src/tests/__snapshots__/input-addon.test.js.snap
- packages/pf3-component-mapper/src/tests/__snapshots__/wizard.test.js.snap
- packages/pf3-component-mapper/src/tests/form-fields.test.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/files/sub-form.js
- packages/pf4-component-mapper/src/files/tabs.js
- packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
- packages/pf4-component-mapper/src/tests/form-fields.test.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/files/field-provider.js
- packages/react-form-renderer/src/files/use-field-api.js
- packages/react-form-renderer/src/form-renderer/assign-special-type.js
- packages/react-form-renderer/src/form-renderer/condition.js
- packages/react-form-renderer/src/form-renderer/render-form.js
- packages/react-form-renderer/src/form-renderer/validator-helpers.js
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/form-renderer.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/__snapshots__/render-form.test.js.snap
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
- packages/react-form-renderer/src/tests/form-renderer/use-field-api.test.js
- packages/react-renderer-demo/src/app/examples/tests/__snapshots__/custom-component-outside-renderer.test.js.snap
- packages/react-renderer-demo/src/app/examples/tests/__snapshots__/custom-component-with-renderer.test.js.snap
- packages/react-renderer-demo/src/app/examples/tests/custom-component-outside-renderer.test.js
- packages/react-renderer-demo/src/app/pages/renderer/component-mapping.md
Some functionality left in render single field, but it should be moved to useField to make sense.
- `renderSingleField` does not do anything, only renders component and use action mapper to assign props
- `useField` now creates the validate, validatorArray, converting initialValue
- fixes some propTypes
- fixes wrong initializeOnMount tests
- **breaking**: FieldProvider uses `Component` instead of `component` (due to props naming conflict)
> fix(renderer): move functionality from render to useField

- packages/react-renderer-demo/package.json
- packages/react-renderer-demo/src/app/pages/_document.js
- packages/react-renderer-demo/src/app/pages/index.js
- yarn.lock
react-githubs-buttons + modified styles
The button will be always loaded
**Before**
**After**
> Use react-github-buttons instead of outside script

- packages/pf4-component-mapper/demo/demo-schemas/wizard-schema.js
- packages/pf4-component-mapper/src/form-fields/select/option.js
- packages/pf4-component-mapper/src/form-fields/select/select-styles.scss
Disabled option was missing styling, done according to PF select component.
> fix(pf4): add styling for disabled options

- packages/react-renderer-demo/src/app/examples/components/get-started/get-started.js
- packages/react-renderer-demo/src/app/pages/migration-guide.md
- fix using `canReset` in get started demo
- add `canReset` to the list of moved props in the migration guide
> Fix canReset use in getStarted

- packages/react-renderer-demo/src/app/src/components/layout.js
On small screen the menu is temporary and the content is not shifted
On medium+ screens the menu is persistent (business as usual)
> Make menu on small screen temporary

- packages/common/src/select/index.js
- packages/pf3-component-mapper/src/tests/form-fields/select/select.test.js
- packages/react-renderer-demo/src/app/src/doc-components/pf3-select.md
- packages/react-renderer-demo/src/app/src/doc-components/pf4-select.md
fix for the bug found in https://github.com/RedHatInsights/approval-ui/pull/233
This PR adds opt-in prop to disable `value` manipulation when the selected value is not in new options (after the props is changed, not when filtering!)
It would make more sense to make it opt-out, however, this feature was made to allow editing options in editors and it could introduce breaking changes for someone. What do you think, @Hyperkid123 ?
> fix(common): make props to control deselection of values

- packages/blueprint-component-mapper/package.json
- packages/common/package.json
- packages/mui-component-mapper/package.json
- packages/pf3-component-mapper/package.json
- packages/pf4-component-mapper/package.json
- packages/react-form-renderer/package.json
- packages/suir-component-mapper/package.json
- templates/component-mapper/package.json
`PropTypes.elementType` cause consumer apps to crash if they used an older version of `prop-types` package.
> fix(all): include prop-types in dependencies

- package.json
- yarn.lock
So what is happening:
- Karel's analyzers writes new version in package.jsons (you can check the log in the CI)
- these modified files are released (you can check in other projects, that DDF dependencies have bundled the right package.json versions)
- however, these changes are not committed to the repository
- semantic-release/git should commit these changes to master
(`@semantic-release/github` does not have the message option)
(`"@semantic-release/git": "^8.0.0",` version 9 requires higher node version and it doesn't bring anything new, so I used 8 for now)
Please see
https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository
https://github.com/semantic-release/git
> Update versions in package.jsons

- packages/mui-component-mapper/src/files/select.js
close #531 
- the autocomplete considers `''` as a value, so the select is by default 'filled'
- changed to `null` (`undefined` is uncontrolled)
- Also tested on the latest iPadOS. The double click is now gone. (see video below)
- everything else seems working well
**Before**
Notice that the clearable button is shown immediately with no value selected.
**After**
**iPadOS** (well... :smile_cat: )
> fix(mui): change empty value in select from '' to null

- packages/pf4-component-mapper/demo/demo-schemas/dual-list-schema.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/files/dual-list-select.js
- packages/pf4-component-mapper/src/tests/dual-list-select.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/pf4/pf4-dual-list.md
I want to add the ability to pass a selected items status to the dual list.
This is a draft:
The message will have placeholders `[selected]` and `[options]` to put the number of selected items and the number of options in the list respectively.
> Add selected items status message to dual list

- packages/pf4-component-mapper/src/files/dual-list-select.js
- packages/pf4-component-mapper/src/tests/dual-list-select.test.js
- packages/suir-component-mapper/demo/demo-schemas/dual-list-select-schema.js
- packages/suir-component-mapper/demo/index.js
- packages/suir-component-mapper/src/files/dual-list-select.js
- packages/suir-component-mapper/src/tests/dual-list-select.test.js
This is a nit change I was asked to do by @nlcwong 
//cc @rvsia @Hyperkid123
> fix(pf4,suir): Make sort icons consistent among all dual-list selectors

- packages/common/src/wizard/enter-handler.js
- packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js
closes https://github.com/data-driven-forms/react-forms/issues/542
Enter cannot skip the validation anymore
> fix(common): wizard check validating on enter

- packages/react-renderer-demo/src/stackblitz-templates/pf4-templates.js
Fixes missing dep in PF4 examples
> Add TSlib as dep to demo stackblitz template

- packages/react-renderer-demo/src/components/code-editor/index.js
- packages/react-renderer-demo/src/helpers/list-of-contents-select.js
- packages/react-renderer-demo/src/helpers/list-of-contents.js
- packages/react-renderer-demo/src/next.config.js
- packages/react-renderer-demo/src/pages/mappers/blueprint-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/mui-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/pf3-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/pf4-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/suir-component-mapper.md
- packages/react-renderer-demo/src/pages/migration-guide.md
- packages/react-renderer-demo/src/pages/renderer/action-mapper.md
- packages/react-renderer-demo/src/pages/renderer/cleared-value.md
- packages/react-renderer-demo/src/pages/renderer/component-api.md
- packages/react-renderer-demo/src/pages/renderer/component-mapping.md
- packages/react-renderer-demo/src/pages/renderer/condition.md
- packages/react-renderer-demo/src/pages/renderer/data-types.md
- packages/react-renderer-demo/src/pages/renderer/development-setup.md
- packages/react-renderer-demo/src/pages/renderer/dynamic-fields.md
- packages/react-renderer-demo/src/pages/renderer/field-provider.md
- packages/react-renderer-demo/src/pages/renderer/file-input.md
- packages/react-renderer-demo/src/pages/renderer/form-template.md
- packages/react-renderer-demo/src/pages/renderer/get-started.md
- packages/react-renderer-demo/src/pages/renderer/global-component-props.md
- packages/react-renderer-demo/src/pages/renderer/initialize-mount.md
- packages/react-renderer-demo/src/pages/renderer/installation.md
- packages/react-renderer-demo/src/pages/renderer/renderer-api.md
- packages/react-renderer-demo/src/pages/renderer/schema-validator.md
- packages/react-renderer-demo/src/pages/renderer/unmounting.md
- packages/react-renderer-demo/src/pages/renderer/validators.md
- packages/react-renderer-demo/src/pages/testing.md
On mobile phone the content is put to the end of pages and it's not very useful (especially on long screens):
This PR hides this list on smaller screen and puts a menu to the top of the page:
+ fix a bug when the code editor was bigger than the viewport.
> Add mobile friendly table of content

- packages/react-form-renderer/src/files/compose-validators.js
- packages/react-form-renderer/src/files/validators.d.ts
- packages/react-form-renderer/src/tests/form-renderer/validator.test.js
- packages/react-form-renderer/src/validators/helpers.d.ts
- packages/react-form-renderer/src/validators/helpers.js
- packages/react-renderer-demo/src/pages/renderer/validators.md
Memoize wasn't passing other arguments except the value, so allValues were missing.
+ also added meta as the third argument (same as in FF)
> fix(renderer): memoize do not pass all arguments

- packages/react-renderer-demo/src/components/code-editor/index.js
- packages/react-renderer-demo/src/components/code-editor/transform-imports.js
- packages/react-renderer-demo/src/components/landing-page/landing-page-cards.js
- packages/react-renderer-demo/src/components/mdx/mdx-components.js
- packages/react-renderer-demo/src/pages/components/field-provider.md
- packages/react-renderer-demo/src/pages/components/form-template.md
- packages/react-renderer-demo/src/pages/hooks/use-field-api.md
- packages/react-renderer-demo/src/pages/optimization.md
Code snippets where are UMD imports of DDF libraries can be switched to CJS/ESM.
> Add env switcher to code examples

- packages/react-renderer-demo/src/examples/components/ts-example.js
- packages/react-renderer-demo/src/pages/typescript.md
closes #593 
Used codesanbox embed editor (stackblitz TS template did not work with extended types for some reason).
> [DOCS] Added TS example to docs.

- packages/react-renderer-demo/src/components/component-mapper-bar.js
- packages/react-renderer-demo/src/next.config.js
- packages/react-renderer-demo/src/pages/mappers/blueprint-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/mui-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/pf3-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/pf4-component-mapper.md
- packages/react-renderer-demo/src/pages/mappers/suir-component-mapper.md
It's more appealing than just plain links and we can remove some text boilerplate.
desktop
mobile
> Add bar for component mappers

- packages/react-renderer-demo/src/components/notification-panel.js
This prevents notifications issues when the response is `null` or empty.
Eventually, we will migrate to something else
> Add fallback to empty notification response

- packages/react-renderer-demo/src/components/component-example-text.js
- testing for algolia wait time
- `{`${avalableMappers.find(({ mapper }) => mapper === activeMapper).title} ${linkText}`}` is because there is a function that creates header id and it need to have only string child
> Use package title in the main component heading

- README.md
- packages/blueprint-component-mapper/README.md
- packages/mui-component-mapper/README.md
- packages/parsers/README.md
- packages/pf3-component-mapper/README.md
- packages/pf4-component-mapper/README.md
- packages/react-form-renderer/README.md
- packages/react-renderer-demo/src/pages/development-setup.md
- packages/suir-component-mapper/README.md
- templates/component-mapper/README.md
- rm yarn.lock should be the last option, we should not probably encourage it as a routine
- demo repository is unclear, changet to the full name
> Make dev setup more clear

- packages/react-renderer-demo/src/pages/optimization.md
This example is specifically made for UMD
**After**
> Make babel transform plugin result's code snippet unswitchable

- packages/common/src/wizard/reducer.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/files/wizard.d.ts
- packages/pf4-component-mapper/src/files/wizard/wizard-nav.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/pf4/pf4-wizard.md
- name of steps is used as keys (so titles supports ReactNodes)
- substepOf has new definition, can use ReactNode as title
> Make PF4 wizard more translatable

- packages/pf4-component-mapper/demo/demo-schemas/select-schema.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/common/select/menu.js
- packages/pf4-component-mapper/src/common/select/select.js
- packages/pf4-component-mapper/src/files/select.d.ts
- packages/pf4-component-mapper/src/tests/select/select.test.js
- allow to set up keys for each option
- translated strings are properly rendered in value container
Before
After
> fix(pf4): allow translated strings in select

- packages/react-renderer-demo/src/helpers/list-of-contents.js
- packages/react-renderer-demo/src/pages/components/field-array.md
- packages/react-renderer-demo/src/pages/components/renderer.md
- packages/react-renderer-demo/src/pages/development-setup.md
- packages/react-renderer-demo/src/pages/mappers/action-mapper.md
- packages/react-renderer-demo/src/pages/mappers/component-api.md
- packages/react-renderer-demo/src/pages/schema/clear-on-unmount.md
- On every page there should be only one h1 header to make better docsearch hiearchy
- also updates Contents component to put h1 level link as the header (having 'content' text does not provide any additional value and it creates better hiearchy)
Before
After
> Make headers consistent

- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/files/wizard.d.ts
- packages/pf4-component-mapper/src/files/wizard.js
- packages/pf4-component-mapper/src/files/wizard/wizard-step.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard-step.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/wizard-nav.test.js
- packages/pf4-component-mapper/src/tests/wizard/wizard-step.test.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/pf4/pf4-wizard.md
- component allowing to define custom steps
- also this commit allows to define more props in step definitions
Example:
```jsx
{
name: 'step',
hasNoBodyPadding: true,
StepTemplate: ({ formFields }) => <div style={{ width: '100%', height: '100%', background: 'red', padding: 32 }}>{formFields}</div>
....
}
```
cc @PanSpagetka
> feat(pf4): introduce StepTemplate

- globalSetup.js
- package.json
Sets the global jest environment timezone to UTC.
Fix: #650
> PF3 datepicker test timezone fix

- packages/react-form-renderer/src/files/field.d.ts
- packages/react-form-renderer/src/files/use-field-api.js
- packages/react-form-renderer/src/form-renderer/render-form.js
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
- packages/react-renderer-demo/src/components/navigation/schemas/schema.schema.js
- packages/react-renderer-demo/src/examples/components/resolve-props.js
- packages/react-renderer-demo/src/pages/schema/introduction.md
- packages/react-renderer-demo/src/pages/schema/resolve-props.md
closes #646
For more details read the documentation page
This PR
- add `resolveProps` for form-connected fields
- moves actionsMapper functionality to renderForm (so you can use actions for subForms etc.)
- allows to merge mapper's actions and field's actions
**Example of resolve props**
```jsx
{
name: 'text_box_2',
label: 'Validate me',
isRequired: true,
validate: [{
type: 'required'
}],
component: components.TEXT_FIELD,
resolveProps: (_props, {
meta
}) => {
if (meta.valid && meta.touched) {
return {
helperText: 'Validated',
validated: 'success'
};
}
return {};
}
}
```
> Introduce resolve props

- packages/pf4-component-mapper/demo/demo-schemas/select-schema.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/common/select/input.js
- packages/pf4-component-mapper/src/common/select/menu.js
- packages/pf4-component-mapper/src/common/select/menu.scss
- packages/pf4-component-mapper/src/common/select/select-styles.scss
- packages/pf4-component-mapper/src/common/select/select.js
- packages/pf4-component-mapper/src/common/select/value-container.js
This just ate my whole day!
- use typeahead styling for PF4 select
- add top cropping of the menu if the element is of the scrollable parent element (bottom is not needed since the the menu should overflow the parent)
- add scroll overflow to the menu to prevent window overflow
> Use pf4 select component

- packages/form-state-manager/demo/index.js
- packages/form-state-manager/src/files/form-manager-context.js
- packages/form-state-manager/src/files/form-state-manager.js
- packages/form-state-manager/src/files/use-field.js
- packages/form-state-manager/src/utils/get-form-values.js
- packages/form-state-manager/src/utils/state-manager-reducer.js
- packages/form-state-manager/src/utils/use-subscription.js
Added initial implementation of state manager context, `useField` and `useSubscriotion` hooks. This will render fields on demand not on every state change.
- fields are currently only subscribed to their state mutation
- form context only extracts field values on form submit
- we are using class instance (closure) per field to hold its internal state
- class method reference is registered on the field mount to context and called on-demand to retrieve the field state (currently only on submit)
- the instance must be synchronized when the field state changes
Note: I am thinking about writing this purely in TS. We should make the decision ASAP so it won't be much work if we decide to do it later. TS will help a lot with all of these interfaces and functions.
> feat(manager): create subscription based state manager

- packages/pf4-component-mapper/src/common/form-group.js
- packages/pf4-component-mapper/src/files/checkbox.d.ts
- packages/pf4-component-mapper/src/files/checkbox.js
- packages/pf4-component-mapper/src/files/date-picker.js
- packages/pf4-component-mapper/src/files/dual-list-select.d.ts
- packages/pf4-component-mapper/src/files/dual-list-select.js
- packages/pf4-component-mapper/src/files/form-group.d.ts
- packages/pf4-component-mapper/src/files/radio.js
- packages/pf4-component-mapper/src/files/select.js
- packages/pf4-component-mapper/src/files/slider.js
- packages/pf4-component-mapper/src/files/switch.js
- packages/pf4-component-mapper/src/files/text-field.js
- packages/pf4-component-mapper/src/files/textarea.js
- packages/pf4-component-mapper/src/files/time-picker.js
- packages/pf4-component-mapper/src/tests/__snapshots__/form-fields.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
- introduces FormGroupProps
- validated can be overwritten by props
- some types and props bugs fixed
example
```jsx
{
name: 'validate',
label: 'Async validation',
validate: [asyncValidate, {
type: 'required'
}],
resolveProps: (input, {
meta
}) => {
console.log(meta.validating)
if (meta.validating) {
return {
helperText: <span><Spinner size="md" />Validating</span>
}
}
if (meta.valid) {
return {
helperText: "It's okay!",
validated: 'success',
FormGroupProps: {
validated: 'success'
}
}
}
return {}
}
}
```
> fix(pf4): allow more customization

- packages/pf4-component-mapper/demo/demo-schemas/select-schema.js
- packages/pf4-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/common/select/input.js
- packages/pf4-component-mapper/src/common/select/select.js
- pressing spacebar inside the searchable input toggled the menu (close/open)
- the event is no longer propagated to input parent elements (toggle root)
- added a check for the type of filter value
- opening a menu with set input value from the initial value caused the menu to crash
- it was trying to run `toLowerCase` on an array
> Pf4 select updates

- packages/pf4-component-mapper/demo/demo-schemas/select-schema.js
- packages/pf4-component-mapper/src/common/select/select.js
this should fix both UX issues listed in https://github.com/RedHatInsights/catalog-ui/pull/682#pullrequestreview-456330633
It will no longer happen that the menu gets opened while in a loading state
> fix(pf4): prevent select filter trigger on value selection

- packages/pf4-component-mapper/src/common/select/select.js
- reset the highlight index after an item selection
> fix(pf4): prevent portal menu warping on open

- packages/form-state-manager/.eslintrc
- packages/form-state-manager/demo/index.tsx
- packages/form-state-manager/src/tests/helpers/text-field.tsx
- packages/form-state-manager/src/tests/performance/field-render-cycle.test.js
This test measures number of re-renders in component with `useField` hook.
This should always let us know if we suddenly break the detached state updates
> [manager] render cycle tests

- packages/form-state-manager/src/tests/utils/validate.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/types/validate.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- packages/form-state-manager/src/utils/validate.ts
part of https://github.com/data-driven-forms/react-forms/issues/687
- add form.validate that is being called on each change 
- in the future, it should be probably configurable with `validateOnBlur` (see https://github.com/data-driven-forms/react-forms/issues/690)
- does not sets the error
> feat(state): add form level validate

- packages/form-state-manager/src/files/form-manager-context.ts
- packages/form-state-manager/src/files/form-state-manager.tsx
- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/tests/utils/use-subscription.test.js
- packages/form-state-manager/src/types/form-manager-context.d.ts
- packages/form-state-manager/src/types/form-state-manager.d.ts
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- packages/form-state-manager/src/utils/use-subscription.ts
part of https://github.com/data-driven-forms/react-forms/issues/690
> feat(state): add initialValues

- packages/form-state-manager/src/files/form-state-manager.tsx
- packages/form-state-manager/src/tests/utils/use-subscription.test.js
- packages/form-state-manager/src/types/form-state-manager.d.ts
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/types/validate.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- packages/form-state-manager/src/utils/use-subscription.ts
- packages/form-state-manager/src/utils/validate.ts
part of #687
Only handles field-level validation
To enable it for form-level validation, we will need to register all validation functions and run them again after the form level validation passes. We need a way to clear form level validation errors, but do not remove field-level validation results at the same time. The only safe way I can think of is re-run all field-level validators, update the state, and possibly trigger the field render.
We will have also trigger the field render after we run form level validation for invalid fields.
> feat(manager): mutate error object on field-level validation.

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/tests/utils/use-subscription.test.js
- packages/form-state-manager/src/tests/utils/validate.test.js
- packages/form-state-manager/src/types/field-config.d.ts
- packages/form-state-manager/src/types/form-manager-context.d.ts
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- packages/form-state-manager/src/utils/use-subscription.ts
closes #708 
- fields no longer have local state
- the state is now stored inside the `fieldListeners` state 
- field state is updated and after the update, all fields registered under the same name are re-rendered
- we can now use global `change` and other methods to mutate registered fields all at once
- using the `setFieldState` will update and trigger field render
- `render` is now required registration attribute (it should have been before)
> feat(manager): lift field state to global state

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/tests/utils/use-subscription.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- packages/form-state-manager/src/utils/use-subscription.ts
follow-up of #709 
- field state is created by the manager
- initializedFields are no longer required
> feat(manager): create field states in manager

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/tests/utils/use-subscription.test.js
- packages/form-state-manager/src/types/field-config.d.ts
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- packages/form-state-manager/src/utils/use-subscription.ts
part of https://github.com/data-driven-forms/react-forms/issues/687
- moves field validation logic to manager API
- removes duplicate change state change call in the field change method
- adds async watcher logic to field level validation
> feat(manager): add async validating field flag

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- packages/form-state-manager/src/utils/use-subscription.ts
part of https://github.com/data-driven-forms/react-forms/issues/687
- add state mutation after form level validation
- synchronizes form-level and field-level validation errors and state flags
> Form level validation state mutation

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- part of https://github.com/data-driven-forms/react-forms/issues/705 & https://github.com/data-driven-forms/react-forms/issues/690
> feat(manager): initialize + keepDirtyOnReinitialize

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
destroyOnUnregister is the same as clearOnUnmount
> feat(manager): introduce destroyOnUnregister

- packages/form-state-manager/src/files/form-manager-context.ts
- packages/form-state-manager/src/files/form-state-manager.tsx
- packages/form-state-manager/src/files/use-field-array.ts
- packages/form-state-manager/src/tests/files/use-field-array.test.js
- packages/form-state-manager/src/types/form-manager-context.d.ts
- packages/form-state-manager/src/types/use-field-array.d.ts
- adds a push method
- currently instead of just calling field `onChange` method and adding new fields, there is a setTimeout workaround until https://github.com/data-driven-forms/react-forms/issues/728 is resolved. Once the issue is closed we can enable the second test case
> feat(manager): add push feature to field array

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
closes https://github.com/data-driven-forms/react-forms/issues/705
> feat(manager): introduce setConfig

- packages/form-state-manager/.eslintrc
- packages/form-state-manager/src/files/use-field.ts
- packages/form-state-manager/src/tests/.eslintrc
- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/utils/manager-api.ts
- all fields are being revalidated on change
- validateFields shares the same behavior
- tslint won't allow unused vars
> feat(manager): Revalidate all fields

- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/files/use-field-api.js
- packages/react-form-renderer/src/tests/form-renderer/use-field-api.test.js
```jsx
const TextField = ({ name, label }) => {
const { input, meta } = useFieldApi({ name, validate: [{ type: validatorTypes.REQUIRED }] }); // the direct validate reference is the issue here
return (
<div>
<label>{label}</label>
<input {...input} />
</div>
);
};
```
Defining the `validate` constant directly inside the `useFieldApi` causes infinite looping. This is caused by `useEffect` which is resetting validators on `validate` change. Since in JS `[] !== []` and due to a fact that the `validate` array is a new instance in each render when used like in the example, we will be stuck in an infinite loop and crash the UI.
- serialize validate config to prevent infinite loop
> fix(renderer): serialize validate config to prevent infinite loop

- packages/react-renderer-demo/src/components/footer.js
This change makes it clearer which things are links or not (as now everything is a link), and also removes the words "Link To" as that's implied by having icons next to things in a footer.
Before:
After:
> Clean up footer presentation and icons

- packages/pf3-component-mapper/src/files/select.js
The power of a two-character fix!
Fixed console prop types warning.
> fix(pf3): fix incorrect invalid prop type in select component

- packages/react-form-renderer/src/files/form-renderer.d.ts
- packages/react-form-renderer/src/files/renderer-context.d.ts
- packages/react-form-renderer/src/files/validator-mapper.d.ts
- packages/react-form-renderer/src/form-renderer/validator-helpers.d.ts
When implementing the solution in https://github.com/data-driven-forms/react-forms/issues/764#issuecomment-680849795 I noticed that Typescript will throw an error `'validatorMapper' only refers to a type, but is being used as a value here.ts(2693).` when trying to import `validatorMapper`.
I realized that it should export a variable of this type by default since that is what is going on in https://github.com/data-driven-forms/react-forms/blob/862db36f2155cec9a6027464e9b158b4966048db/packages/react-form-renderer/src/files/validator-mapper.js#L6-L18
> Changed validator mapper type to export object

- packages/react-renderer-demo/src/components/common/example-link.js
- packages/react-renderer-demo/src/components/navigation/examples-definitions.js
- packages/react-renderer-demo/src/components/navigation/find-connected-links.js
- packages/react-renderer-demo/src/components/navigation/mapper.js
- packages/react-renderer-demo/src/doc-components/dual-list-select.js
- packages/react-renderer-demo/src/hooks/use-mapper-link.js
- packages/react-renderer-demo/src/pages/mappers/component-api.md
- packages/react-renderer-demo/src/pages/typescript.md
This PR fixes three issues:
- selected mapper persists when switching component examples
- there is no longer any link to component examples with no active mapper, so algolia should not duplicate results for MUI examples
- PF4 dual list documentation was hidden
> Fix links for components examples

- packages/react-form-renderer/demo/form-template.js
- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/files/use-field-api.js
This PR moves execution of `resolveProps` to top of `useFieldApi` hook.
This allows to rewrite props coming to `useField` hook. I was doing this to try to change `validate` via `resolveProps` function, however there is a final form issue, that does not revalidate fields when the validator is changed. So it's possible to change `validate`, but it's buggy right now.
> fix(renderer): move resolve props to top

- packages/form-state-manager/src/files/compose-validators.ts
- packages/form-state-manager/src/tests/files/compose-validators.test.js
- packages/form-state-manager/src/tests/files/use-field.test.js
- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/compose-validators.d.ts
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
part of https://github.com/data-driven-forms/react-forms/issues/739
I have added `composeValidators` but then I have realized, it's not usable for this feature. I have not added test but we will need this function later anyway.
> fix(manager): allow multiple field listener validators

- packages/form-state-manager/src/files/use-field.ts
- packages/form-state-manager/src/tests/files/use-field.test.js
- packages/form-state-manager/src/types/data-types.d.ts
- packages/form-state-manager/src/utils/convert-value.ts
closes https://github.com/data-driven-forms/react-forms/issues/771
> fix(manager): convert initialValue/defaultValue when dataType

- packages/form-state-manager/src/tests/performance/field-render-cycle.test.js
- packages/form-state-manager/src/tests/utils/find-difference.test.js
- packages/form-state-manager/src/utils/find-difference.ts
- packages/form-state-manager/src/utils/manager-api.ts
This PR prepares API for rerendering form based on state changes
```jsx
function = () => {
const render = prepareRerender(); // snapshots current state
... do some changes ...
render(); // as the argument additional formState keys can be inserted manually, compare the old state and new state
}
```
> feat(manager): prepare API for rendering based on state changes

- packages/react-form-renderer/src/files/use-field-api.d.ts
The component attribute should not be inside the useFieldApi config. Only in the schema.
> fix(renderer): make component option in use field api interface

- packages/react-form-renderer/src/files/use-field-api.d.ts
Make the useFieldApi type generic with default `any` type.
This will allow us to pass a type definition to the function and that will be used for `input.value`:
```TS
const {
input: { value, onChange }
} = useFieldApi<string[]>({ name });
value.filter(...)
```
> fix(renderer): Make use-field-api accept value definition.

- packages/react-renderer-demo/src/pages/optimization.md
- do not convert examples for CJS and ESM imports
- transform the error message into an inline code to be included in the algolia search
> Fix optimization page

- packages/react-renderer-demo/src/components/component-example.js
- this should prevent algolia to index MUI components twice in the search index
> Redirect on examples when no mapper

- packages/form-state-manager/src/files/use-field.ts
- packages/form-state-manager/src/tests/files/use-field-array.test.js
- packages/form-state-manager/src/tests/performance/field-render-cycle.test.js
- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/field-config.d.ts
- packages/form-state-manager/src/types/use-field.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
This PR rerenders form on these events:
- register field
- unregister field
- initialize
- reset
- resetFieldState
- blur
- focus
- change
not tested yet but should work:
- submitting (submit is not properly implemented now)
- validating
- error
- valid
also implements silent from https://github.com/data-driven-forms/react-forms/issues/726 because we have encountered the same issue as all other libraries. React does not like rendering from the first render..  we should probably brainstorm a solution of registering field in useEffect..(edit: I have an idea, will try it after this PR is merged)
> feat(manager): rerender form on basic functions

- packages/react-renderer-demo/src/components/component-example.js
- packages/react-renderer-demo/src/pages/404.js
- so the previous PR actually made impossible to crawl these results so I reverted it :sob: :sob: :skull: 
- I also added the query param when users are redirected from the old route.
> Revert "Redirect on examples when no mapper" 

- packages/form-state-manager/src/files/use-field.ts
- packages/form-state-manager/src/tests/files/use-field-array.test.js
- packages/form-state-manager/src/tests/files/use-field.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
- to avoid rendering other fields during initialization of a field, this render is called in `useEffect` via `afterSilentRegistration` function. This function revalidates all fields and rerender all fields (except the one that has been just registered) based on changed form state attributes from the last field registration.
> fix(manager): fix rendering issues by rerendering forms on mount

- packages/react-form-renderer/src/files/wizard-context.d.ts
closes https://github.com/data-driven-forms/react-forms/issues/786
Changed wizard context type to constant from an interface
> fix(renderer): fix wizard context export type

- packages/react-renderer-demo/src/components/code-editor/index.js
- packages/react-renderer-demo/src/components/code-example.js
> Fix code editor width to keep menu the same

- packages/react-renderer-demo/src/components/mdx/mdx-components.js
Material UI tables are not very responsive on smaller screens, so I fixed it (it messes with the menu width)
**Before**
**After**
> Make tables fixed on smaller screens

- packages/react-form-renderer/src/files/parse-condition.d.ts
- packages/react-form-renderer/src/files/parse-condition.js
- packages/react-form-renderer/src/form-renderer/condition.js
- packages/react-form-renderer/src/index.js
- packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js
> fix(renderer): export parse condition function

- packages/carbon-component-mapper/src/files/sub-form.d.ts
- packages/carbon-component-mapper/src/files/sub-form.js
- packages/carbon-component-mapper/src/files/sub-form.scss
- packages/carbon-component-mapper/src/files/tabs.d.ts
- packages/carbon-component-mapper/src/files/tabs.js
- packages/carbon-component-mapper/src/files/tabs.scss
- packages/carbon-component-mapper/src/files/wizard.d.ts
- packages/carbon-component-mapper/src/files/wizard.js
- packages/carbon-component-mapper/src/files/wizard.scss
- packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-sub-form.md
- packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-tabs.md
- packages/react-renderer-demo/src/doc-components/examples-texts/carbon/carbon-wizard.md
- packages/react-renderer-demo/src/doc-components/tabs.js
These three components were missing the form spacing
**Before**
**After**
> fix(carbon): fix styles for wizard/subform/tabs

- packages/react-renderer-demo/src/components/common/connected-links.js
- packages/react-renderer-demo/src/components/component-example-text.js
- packages/react-renderer-demo/src/components/doc-page.js
- packages/react-renderer-demo/src/helpers/generic-mui-component.js
- packages/react-renderer-demo/src/helpers/list-of-contents.js
- packages/react-renderer-demo/src/pages/mappers/date-picker.js
- packages/react-renderer-demo/src/pages/mappers/time-picker.js
This PR limits maxWidth of content. I think on bigger screens the documentation is difficult to read because the text is spread across the whole screen.
**Before**
**After**
> Limit max width for content on documentation

- packages/react-form-renderer/src/files/compose-validators.js
- packages/react-form-renderer/src/files/field.d.ts
- packages/react-form-renderer/src/files/use-field-api.d.ts
- packages/react-form-renderer/src/files/use-field-api.js
- packages/react-form-renderer/src/files/validator-mapper.d.ts
- packages/react-form-renderer/src/files/validators.d.ts
- packages/react-form-renderer/src/form-renderer/validator-helpers.d.ts
- packages/react-form-renderer/src/form-renderer/validator-helpers.js
- packages/react-form-renderer/src/tests/form-renderer/validator.test.js
- packages/react-renderer-demo/src/components/navigation/schemas/schema.schema.js
- packages/react-renderer-demo/src/pages/schema/validator-warnings.md
closes #835 
I have tried several ways how to store warnings and not to use state (`useRef`, `meta.data` via mutator), however I have encounter several issues with the initial validation, where both solutions didn't triggered a re-rerender and who knows how it would handle async functions.
So I implemented it using `useState` and to prevent performance issues, I created a `useWarnings` prop, that turn this functionality on. However, this prop **cannot be changed at runtime** because of hooks ordering. That's one possible issue.
If you don't want to block the form from submitting when a validator fails, you can convert the validator into a warning validator.
In the field, set `useWarnings` to `true`. This feature can impact performace, so it was made to be opt-in. Please, do not change …
>  feat(renderer): add useWarnings functionality

- packages/carbon-component-mapper/demo/demo-schemas/sandbox.js
There was no demo for the dual-list-select component for the Carbon mapper, so I'm adding one.
> Add missing dual list select into the carbon demo schema

- packages/carbon-component-mapper/src/common/is-required.js
- packages/carbon-component-mapper/src/common/is-required.scss
- packages/carbon-component-mapper/src/common/prepare-props.js
- packages/carbon-component-mapper/src/files/checkbox.js
- packages/carbon-component-mapper/src/files/date-picker.js
- packages/carbon-component-mapper/src/files/dual-list-select.js
- packages/carbon-component-mapper/src/files/field-array.js
- packages/carbon-component-mapper/src/files/radio.js
- packages/carbon-component-mapper/src/files/select.js
- packages/carbon-component-mapper/src/files/switch.js
- packages/carbon-component-mapper/src/tests/components.test.js
- packages/react-renderer-demo/src/pages/mappers/carbon-component-mapper.md
I tried to create the least invasive solution to add a `*` to the labels of fields that have an `isRequired: true` attribute. Most of the components are using the `prepareProps` in their `useFieldApi` call, so I added a `buildLabel` function in the same file. However, some components like `FieldArray` don't leverage the `prepareProps` so I am also exporting the `buildLabel` function and calling it explicitly where it is necessary. 
@kavyanekkalapu can you please verify if it's visually correct to have the `*` like this? The color is probably wrong and I will need a better one for sure.
> feat(carbon): implemented optional isRequired for all fields

- packages/form-state-manager/src/files/compose-validators.ts
- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/compose-validators.d.ts
- packages/form-state-manager/src/types/use-field.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
fixes #843 
- it follows the same format as the renderer, however it's no longer opt-in (so we could get rid of `useWarnings` in the next version)
> feat(manager): introduce warnings feature

- packages/carbon-component-mapper/src/files/select.js
- packages/carbon-component-mapper/src/tests/select.test.js
- packages/react-renderer-demo/src/pages/mappers/carbon-component-mapper.md
I found a way to implement the `isSearchable` and `isClearable` functionalities for non-multi selects in carbon usin the [`ComboBox`](https://react.carbondesignsystem.com/?path=/docs/combobox--combobox) component. Unfortunately, these two features come hand in hand, it's not possible to turn off one just of them without turning off the other one as well. Therefore, I adjusted the logic to turn on both features if at least one of them is enabled, i.e. `isClearable || isSearchable` for both the single and the multiselect.
I guess I'll need some help with tests :pray: :see_no_evil:
> feat(carbon): Implement searchable/clearable non-multi select

- packages/pf3-component-mapper/demo/index.js
- packages/pf3-component-mapper/package.json
- packages/pf3-component-mapper/src/files/select.js
- packages/pf3-component-mapper/src/files/select/dropdown-indicator.js
- packages/pf3-component-mapper/src/files/select/select.js
- packages/pf3-component-mapper/src/tests/form-fields/select/__snapshots__/select.test.js.snap
- packages/react-form-renderer/src/form-renderer/enhanced-on-change.js
- yarn.lock
closes #615
If null option was selected, the label was not showing as selected value (although the null value was submitted). Snapshots are updated due to the dependency version update.
@skateman the other values (0, -1, ...) were working without any modification.
> fix(pf3): allow select null value

- packages/react-renderer-demo/src/stackblitz-templates/blueprint-templates.js
- packages/react-renderer-demo/src/stackblitz-templates/mui-templates.js
- packages/react-renderer-demo/src/stackblitz-templates/pf3-templates.js
- packages/react-renderer-demo/src/stackblitz-templates/suir-template.js
closes #865
Some mappers are missing some dependencies in respective stackblitz templates. Guess stackblitz must have pruned their default dependencies :shrug: 
This fixes broken templates.
> Fix missing template dependencies.

- packages/pf3-component-mapper/src/files/select/select.js
closes #866 
If there is an initial value for pf3 select component with lazy loaded options, the searchable dropdown tris to create the label from an option that does not exist yet. 
Now it will display the placeholder until options are resolved.
> fix(pf3): display placeholder for pre-selected lazy options.

- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/utils/manager-api.ts
> fix(manager): reset errors when revalidated

- packages/form-state-manager/src/files/use-field.ts
- packages/form-state-manager/src/tests/files/use-field.test.js
- packages/form-state-manager/src/tests/utils/manager-api.test.js
- packages/form-state-manager/src/types/manager-api.d.ts
- packages/form-state-manager/src/utils/manager-api.ts
closes #769 
- same API as for form renderer, just changed `unRegisterInputFile` to `unregisterInputFile` to achieve a consistency. As it is mainly an internal function, it should not be a big deal.
> feat(manager): implement fileInput features

- packages/carbon-component-mapper/src/files/select.js
The `onChange` of the combobox (single select with search + clear) has a `selectedItem` argument, unlike the `selectedItems` of any other (multi)select. So in order to make the field working, it is necessary to adjust the onChange to deal with this case as well.
> fix(carbon): adjusted combobox onchange invocation for singlevalues

- packages/react-form-renderer/src/files/default-schema-validator.js
- packages/react-form-renderer/src/files/parse-condition.js
- packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js
- packages/react-form-renderer/src/tests/parsers/__snapshots__/default-schema-validator.test.js.snap
- packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
- packages/react-renderer-demo/src/components/navigation/schemas/schema.schema.js
- packages/react-renderer-demo/src/examples/components/conditions/comparators.js
- packages/react-renderer-demo/src/examples/components/conditions/is-function.js
- packages/react-renderer-demo/src/helpers/generic-mui-component.js
- packages/react-renderer-demo/src/pages/schema/comparators.md
- packages/react-renderer-demo/src/pages/schema/is.md
closes #899 
- `is` can be a custom function receiving value and config as arguments and should return boolean
- adds 4 basic math comparators (>, >=, <, <=)
> feat(renderer): enhance condition with custom function and comparators

- packages/react-form-renderer/src/validators/helpers.js
Using `arguments` within arrow functions can cause runtime errors because `arguments` is not defined. This issue was hidden while using webpack < 5, but because webpack@5 is no longer providing any polyfills, this has now surfaced.
> fix(renderer): convert arrow functions with arguments

- packages/pf4-component-mapper/src/files/wizard/wizard-nav.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
Buttons in PF4 Wizard Nav were missing `type=button` so in non-modal version, they triggered the submit action. :fairy:
> fix(pf4): fix wizard navigation buttons to not submit forms

- packages/common/src/wizard/reducer.js
- packages/pf4-component-mapper/src/tests/wizard/wizard.test.js
When building navSchema in common wizard, the substepOfTitle should be inherited in the group so all substeps share the same title.
```jsx
{
name: 'security',
title: 'Security',
nextStep: 'credentials',
substepOf: { name: 'Configuration', title: customTitle }, // custom title
fields: []
},
{
name: 'credentials',
title: 'Credentials',
nextStep: 'summary',
substepOf: 'Configuration', // this step should use the same title
fields: []
},
{
name: 'summary',
title: 'Summary',
fields: []
},
```
**Before** (notice that the name of the primary step is different in the toggle button)
**After**
> fix(pf4): inherit substepOfTitle in wizard

- packages/pf4-component-mapper/src/common/form-group.js
- packages/pf4-component-mapper/src/common/show-error.js
- packages/pf4-component-mapper/src/files/field-array.js
- packages/pf4-component-mapper/src/tests/form-fields.test.js
Part of #922 
Implements submitErrors support for PF4 mapper. (I will add the support for other mappers in a batch as fixes, this is made separately to provide it to our community ASAP)
```jsx
onSubmit={() => ({field: 'some error message'})}
```
> feat(pf4): add support for submit errors

- packages/carbon-component-mapper/src/files/text-field.js
Carbon has a [`NumberInput`](https://www.carbondesignsystem.com/components/number-input/usage) component that is more suitable for numeric values in text fields.
**Before:**
**After:**
Resolves https://github.com/data-driven-forms/react-forms/issues/945
> feat(carbon): use NumberInput for text-field if type=number

- packages/carbon-component-mapper/src/files/sub-form.js
- packages/react-renderer-demo/src/doc-components/examples-texts/carbon/sub-form.md
Replacing the `h5` with an `h3` element.
**Before:**
**After:**
Fixes #946
> fix(carbon): make the subform title element larger

- packages/carbon-component-mapper/src/files/form-template.js
The [docs](https://www.carbondesignsystem.com/components/button/usage#Alignment) are saying that if the buttons are aligned to the left, the primary button should be on the left, so changing ...
> fix(carbon): reorder the buttons according to the alignment guide

- packages/carbon-component-mapper/src/files/text-field.js
- packages/carbon-component-mapper/src/tests/components.test.js
The `TextInput` component takes a `labelText` prop, while the `NumberInput` needs a `label` :confused: :disappointed: 
**Before:**
**After:**
> fix(carbon): pass the label for numeric text-field correctly

- packages/react-renderer-demo/src/stackblitz-templates/mui-templates.js
Fixes #911
By updating React to latest, the demo is working again.
> Fix MUI templates in demo

- packages/pf4-component-mapper/src/files/slider.js
- packages/pf4-component-mapper/src/files/slider.scss
- packages/pf4-component-mapper/src/tests/form-fields.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/pf4/slider.md
- packages/react-renderer-demo/src/helpers/generic-mui-component.js
Fixes #954 
Replaces the custom slider with the original one
```jsx
schema={{
fields: [{
component: componentTypes.SLIDER,
name: 'slider',
isDiscrete: true,
steps: [
{ value: 0, label: '0' },
{ value: 12.5, label: '1', isLabelHidden: true },
{ value: 25, label: '2' },
{ value: 37.5, label: '3', isLabelHidden: true },
{ value: 50, label: '4' },
{ value: 62.5, label: '5', isLabelHidden: true },
{ value: 75, label: '6' },
{ value: 87.5, label: '7', isLabelHidden: true },
{ value: 100, label: '8' }
]
}]
}}
```
> feat(pf4): use original PF4 slider

- packages/pf4-component-mapper/README.md
- packages/pf4-component-mapper/src/common/form-group.js
- packages/pf4-component-mapper/src/common/show-error.js
- packages/pf4-component-mapper/src/files/checkbox.js
- packages/pf4-component-mapper/src/files/date-picker.js
- packages/pf4-component-mapper/src/files/dual-list-select.js
- packages/pf4-component-mapper/src/files/radio.js
- packages/pf4-component-mapper/src/files/select.js
- packages/pf4-component-mapper/src/files/slider.js
- packages/pf4-component-mapper/src/files/switch.js
- packages/pf4-component-mapper/src/files/text-field.js
- packages/pf4-component-mapper/src/files/textarea.js
- packages/pf4-component-mapper/src/files/time-picker.js
- packages/pf4-component-mapper/src/tests/form-fields.test.js
- packages/pf4-component-mapper/src/tests/show-error.test.js
Adds validateOnMount option to PF4 mapper.
**Schema** 
```
schema={{
fields: [
{
name: 'textarea_box_1',
label: 'Text Area',
title: 'Text Area',
validate: [
{
type: validators.PATTERN,
pattern: '[0-9]'
}
],
validateOnMount: true,
component: components.TEXTAREA
}
]
}}
```
@Hyperkid123
> Add validateOnMount option

- packages/pf4-component-mapper/src/files/wizard/step-buttons.js
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/step-buttons.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard-step.test.js.snap
- packages/pf4-component-mapper/src/tests/wizard/__snapshots__/wizard.test.js.snap
Copy of https://github.com/patternfly/patternfly-react/pull/5391
**After**
> fix(pf4): add class for cancel wizard button

- packages/ant-component-mapper/package.json
- packages/pf4-component-mapper/package.json
- scripts/copy-css.js
Fixes #931 
CSS files are copied to their build folders.
> fix(ant,pf4): copy css to build folders

- packages/react-renderer-demo/src/pages/schema/introduction.md
Corrects 2 small typos in the documentation
> MAINT: fix typos in documentation

- packages/react-form-renderer/src/common/index.js
- packages/react-form-renderer/src/tests/form-renderer/data-types.test.js
- packages/react-form-renderer/src/use-field-api/convert-type.js
Part of https://github.com/data-driven-forms/react-forms/issues/980
```
}[dataType] || value);
```
This OR operator skips `0` values because it's falsy. 🤕 
Added a seperate check to check if the value is convertable to number values.
Also, JS is funny because
```jsx
parseInt() => NaN
```
```jsx
Number() => 0
``` 
**Schema**
```jsx
{
component: 'text-field';
name: 'number',
dataType: 'integer'
}
```
> fix(renderer): fix numbers conversions

- packages/react-form-renderer/src/form-renderer/render-form.js
Import common package to just import `export const childrenPropTypes = PropTypes.oneOfType([PropTypes.node, PropTypes.arrayOf(PropTypes.node)]);` ( === `PropTypes.node`) seems like a overkill. 🤔
> fix(renderer): do not use common to import PropTypes.node

- packages/react-form-renderer/package.json
- packages/react-form-renderer/src/common/convert-type.js
- packages/react-form-renderer/src/tests/form-renderer/data-types.test.js
**BACKPORT OF https://github.com/data-driven-forms/react-forms/pull/982**
Part of https://github.com/data-driven-forms/react-forms/issues/980
```
}[dataType] || value);
```
This OR operator skips `0` values because it's falsy. 🤕 
Added a seperate check to check if the value is convertable to number values.
Also, JS is funny because
```jsx
parseInt() => NaN
```
```jsx
Number() => 0
``` 
**Schema**
```jsx
{
component: 'text-field';
name: 'number',
dataType: 'integer'
}
```
> [V2] fix(renderer): fix numbers conversions

- packages/common/src/dual-list-select/dual-list-select.js
- packages/mui-component-mapper/demo/index.js
- packages/pf4-component-mapper/src/dual-list-select/dual-list-select.js
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
- packages/react-form-renderer/src/tests/form-renderer/use-field-api.test.js
- packages/react-form-renderer/src/use-field-api/use-field-api.js
- packages/react-renderer-demo/src/pages/migration-guide-v3.md
- packages/react-renderer-demo/src/pages/schema/introduction.md
Fixes #986 
🚨  **BREAKING** 🚨 
A new [FieldProps](/schema/introduction#fieldprops) props is introduced. This object serves to pass values to Final Form [useField configuration](https://final-form.org/docs/react-final-form/types/FieldProps). Do not use for natively supported props (`initialValue`, `validate`, ...).
```diff
{
name: 'component-with-complex-isEqual',
component: 'dual-list-selector',
-   isEqual: (a, b) => isEqual(a, b),
+   FieldProps: {
+     isEqual: (a, b) => isEqual(a, b),
+   }
}
```
**Schema**
```jsx
{
name: 'texttonumber',
FieldProps: {
parse: value => Number(Value)
}
}
```
> feat(renderer): introduce FieldProps

- packages/common/.gitignore
- scripts/clean-build.js
This ensures that `demoschema` is removed and not causing any issues with lerna
> Fix cleaning build files

- packages/react-form-renderer/src/form-renderer/form-renderer.js
Fixes error
```
Warning: Failed prop type: Invalid prop `FormTemplate` of type `object` supplied to `FormRenderer`, expected `function`.
```
> Fixing prop-type for FormTemplate

- packages/ant-component-mapper/src/switch/switch.js
fix(antd): Antd switch should bind 'input.checked' not 'input.value'.
If not bind with 'input.checked', the initial value will always `false` no matter the real value you provide.
> fix(antd): antd switch should bind 'checked' not 'value'

- packages/pf4-component-mapper/src/dual-list-select/dual-list-select.js
- packages/pf4-component-mapper/src/dual-list-tree-select/dual-list-tree-select.d.ts
- packages/pf4-component-mapper/src/dual-list-tree-select/dual-list-tree-select.js
- packages/pf4-component-mapper/src/dual-list-tree-select/index.d.ts
- packages/pf4-component-mapper/src/dual-list-tree-select/index.js
- packages/pf4-component-mapper/src/index.js
- packages/pf4-component-mapper/src/tests/dual-list-select.test.js
- packages/pf4-component-mapper/src/tests/dual-list-tree-select.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/pf4/dual-list-select.md
Introduces support for isTree variant of Dual List Selector (but it doesn't work properly because of issues in PF4...)
```jsx
import { componentTypes as components } from '@data-driven-forms/react-form-renderer';
const output = {
title: 'Testing dual list',
description: 'Description of testing dual list',
fields: [
{
component: components.DUAL_LIST_SELECT,
name: 'dual-list-select',
label: 'choose favorite animal',
isTree: true,
isSearchable: true,
isSortable: true,
options: [
{
value: 'cats',
label: 'cats'
},
{
value: 'cats_1',
label: 'cats_1'
},
{
value: 'cats_2',
label: 'cats_2'
},
{
value: 'zebras',
label: 'zebras'
},
{
value: 'pigeons',
label: 'pigeons'
}
],
options1: [
{label: 'bb', hasBadge: true, badgeProps: { isRead: true }, children: [ …
```
> feat(pf4): introduce dual list tree select component

- packages/form-state-manager/src/field-spy/field-spy.ts
- packages/form-state-manager/src/field-spy/index.ts
- packages/form-state-manager/src/index.ts
- packages/form-state-manager/src/manager-api/manager-api.ts
- packages/form-state-manager/src/tests/files/field-spy.test.js
Fixes #1020 
Adds `FieldSpy` component.
Accepts these props:
`names` array of field names
`subscription`
`onChange`
> Implement FieldSpy

- packages/react-renderer-demo/src/components/landing-page/landing-page-cards.js
After PF3 removal, the grid went offset
**Before**
**After**
> Fix grid for landing page cards

- package.json
- packages/react-renderer-demo/src/pages/development-setup.md
We cannot run clean before install because we are missing packages needed in the clean script.
> Update clean script to run only before build

- packages/react-renderer-demo/src/pages/components/form-template.md
- packages/react-renderer-demo/src/pages/components/renderer.md
- packages/react-renderer-demo/src/pages/examples/resolve-props-example.md
- packages/react-renderer-demo/src/pages/faq.md
- packages/react-renderer-demo/src/pages/mappers/action-mapper.md
- packages/react-renderer-demo/src/pages/mappers/schema-validator-mapper.md
- packages/react-renderer-demo/src/pages/mappers/validator-mapper.md
- packages/react-renderer-demo/src/pages/schema/resolve-props.md
Splitting the table into a coherent text makes it more readable and we can make links to it.
> Change Renderer props from table to list

- packages/mui-component-mapper/src/dual-list-select/dual-list-select.d.ts
- packages/mui-component-mapper/src/dual-list-select/dual-list-select.js
- packages/mui-component-mapper/src/tests/dual-list-select.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/mui/dual-list-select.md
Updates design of MUI Dual List to latest: https://material-ui.com/components/transfer-list/
```jsx
{
fields: [
{
component: 'dual-list-select',
name: 'dual-list-select',
isFilterable: false,
checkboxVariant: true,
leftTitle: '',
rightTitle: '',
options: [
{
value: 'cats',
label: 'cats'
},
{
value: 'cats_1',
label: 'cats_1'
},
{
value: 'cats_2',
label: 'cats_2'
},
{
value: 'zebras',
label: 'zebras'
},
{
value: 'pigeons',
label: 'pigeons'
}
]
}
]
}
```
> feat(mui): update duallist styling

- packages/ant-component-mapper/src/tests/wizard.test.js
- packages/ant-component-mapper/src/wizard/step-buttons.js
- packages/ant-component-mapper/src/wizard/wizard-step.js
- packages/ant-component-mapper/src/wizard/wizard.js
- packages/blueprint-component-mapper/src/tests/wizard.test.js
- packages/blueprint-component-mapper/src/wizard/step-buttons.js
- packages/blueprint-component-mapper/src/wizard/wizard.js
- packages/carbon-component-mapper/src/tests/wizard.test.js
- packages/carbon-component-mapper/src/wizard/wizard.js
- packages/common/src/wizard/consts.d.ts
- packages/common/src/wizard/consts.js
- packages/common/src/wizard/index.d.ts
- packages/common/src/wizard/index.js
- packages/common/src/wizard/wizard.d.ts
- packages/common/src/wizard/wizard.js
- packages/mui-component-mapper/src/tests/wizard.test.js
- packages/mui-component-mapper/src/wizard/step-buttons.js
- packages/mui-component-mapper/src/wizard/wizard.js
- packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js
- packages/pf4-component-mapper/src/wizard/wizard-components/step-buttons.js
- packages/pf4-component-mapper/src/wizard/wizard-components/wizard-step.js
- packages/pf4-component-mapper/src/wizard/wizard.js
- packages/react-renderer-demo/src/doc-components/examples-texts/wizard.md
- packages/suir-component-mapper/src/tests/wizard.test.js
- packages/suir-component-mapper/src/wizard/step-buttons.js
- packages/suir-component-mapper/src/wizard/wizard.js
based on a feature request in discord
If a conditional next step contains a submit flag (can be configured), the step will show submit button instead of a next button and wizard won't progress further.
```jsx
nextStep: {
when: 'source-type',
stepMapper: {
aws: 'aws-step',
google: CONDITIONAL_SUBMIT_FLAG,
...
},
},
```
Flag value can be configured via `conditionalSubmitFlag` flag in wizard component schema:
```jsx
fields: [{
{
"component": "wizard",
"name": "wizard",
// custom flag definition
conditionalSubmitFlag: 'make-me-final-step',
fields: [{
name: 'step-1',
// next step definition
nextStep: {
when: 'value',
stepMapper: {
"value-one": 'step-2',
"value-two": 'make-me-final-step',
},
}
...
}, {
name: 'step-2'
...
}]
...
}}]
}
```
@rvsia if you can think of a better …
> feat(wizard): enable conditional submit step conversion

- packages/react-renderer-demo/src/doc-components/examples-texts/wizard.md
By default, we are using imports from root and editor automatically translates them. In this case we want to disable it.
cc @nathanbaleeta
> Do not translate wizard flag import

- packages/react-renderer-demo/src/components/navigation/schemas/custom-examples.schema.js
- packages/react-renderer-demo/src/examples/components/examples/custom-wizard.js
- packages/react-renderer-demo/src/pages/examples/custom-wizard.md
Adds an example for custom wizard component using `common/wizard` package. Just the most basic stuff, no fancy features.
> Add example for custom wizard

- packages/react-renderer-demo/src/components/navigation/schemas/custom-examples.schema.js
- packages/react-renderer-demo/src/pages/components/form-template.md
- packages/react-renderer-demo/src/pages/examples/custom-form-buttons.md
- packages/react-renderer-demo/src/pages/examples/form-level-errors.md
- seperate examples
- better searchability
> Reorganize form template documentation page

- packages/carbon-component-mapper/src/switch/switch.js
- packages/carbon-component-mapper/src/tests/switch.test.js
Fixes #1048 
For some reason, carbon is using custom toggled attribute.
```jsx
schema={{
fields: [
{
component: 'switch',
name: 'switchTest',
label: 'Switch',
onText: 'True',
offText: 'False',
initialValue: true
}
]
}}
```
> fix(carbon): fix switch toggled attribute

- packages/carbon-component-mapper/src/dual-list-select/dual-list-select.js
Search component props has renamed in carbon components, so we are getting console error.
> fix(carbon): Fix console error in search component for placeholder prop

- packages/mui-component-mapper/src/checkbox/checkbox.js
- packages/mui-component-mapper/src/multiple-chioce-list/multiple-choice-list.js
addresses: #1056
fixes problem number one in linked issue
> fix(mui): remove component prop from multi checkbox

- packages/common/src/form-template/form-template.js
- packages/pf4-component-mapper/src/form-template/form-template.js
- packages/pf4-component-mapper/src/tests/form-template-common.test.js
- packages/pf4-component-mapper/src/tests/wizard/step-buttons.test.js
- packages/react-form-renderer/src/form-error/form-error.d.ts
- packages/react-form-renderer/src/form-error/form-error.js
- packages/react-form-renderer/src/form-error/index.d.ts
- packages/react-form-renderer/src/form-error/index.js
- packages/react-form-renderer/src/index.js
- packages/react-renderer-demo/src/pages/components/form-template.md
Part of https://github.com/data-driven-forms/react-forms/issues/923
Adds `BeforeError` component to common FormTemplate.
Adds `alertProps` to common FormTemplate.
Adds implementation of the Alert for PF4 mapper (based on [guidelines](https://www.patternfly.org/v4/components/form/design-guidelines#error-validation-on-submission))
Reexports `FORM_ERROR` as `FormError` in the renderer package.
```jsx
validate={({something}) => {
if(something?.length > 3) {
return {[FormError]: 'too long'}
}
if(something) {
return {[FormError]: 'too short'}
}
return {}
}}
```
> Add form alerts and add implementation for PF4

- packages/react-form-renderer/src/form-renderer/render-form.js
- packages/react-form-renderer/src/get-validates/get-validates.d.ts
- packages/react-form-renderer/src/get-validates/get-validates.js
- packages/react-form-renderer/src/get-validates/index.d.ts
- packages/react-form-renderer/src/get-validates/index.js
- packages/react-form-renderer/src/get-visible-fields/get-visible-fields.d.ts
- packages/react-form-renderer/src/get-visible-fields/get-visible-fields.js
- packages/react-form-renderer/src/get-visible-fields/index.d.ts
- packages/react-form-renderer/src/get-visible-fields/index.js
- packages/react-form-renderer/src/prepare-component-props/index.d.ts
- packages/react-form-renderer/src/prepare-component-props/index.js
- packages/react-form-renderer/src/prepare-component-props/prepare-component-props.d.ts
- packages/react-form-renderer/src/prepare-component-props/prepare-component-props.js
- packages/react-form-renderer/src/tests/validation/get-validates.test.js
- packages/react-form-renderer/src/tests/validation/get-visible-fields.test.js
- packages/react-form-renderer/src/tests/validation/validation.test.js
- packages/react-form-renderer/src/validation/index.d.ts
- packages/react-form-renderer/src/validation/index.js
- packages/react-form-renderer/src/validation/validation.d.ts
- packages/react-form-renderer/src/validation/validation.js
- packages/react-renderer-demo/src/components/navigation/schemas/schema.js
- packages/react-renderer-demo/src/components/navigation/schemas/utilities.schema.js
- packages/react-renderer-demo/src/examples/components/utilities/standalone-validation.js
- packages/react-renderer-demo/src/pages/utilities/standalone-validation.md
TODO:
*@data-driven-forms/react-form-renderer/validation*
*(schema: Schema, options: Options) => object: Errors*
Data Driven Forms provides an async function that validates values based on a provided schema. This feature can be useful to implement validation on backend endpoints with using the same schema as in frontend applications.
*object*
The same [schema](/schema/introduction) as for the form renderer. Validation supports all features except array validators that are being used by field arrays. This functionallity will be implemented in the future.
*object*
```ts
{
values: AnyObject;
componentMapper?: ComponentMapper;
validatorMapper?: ValidatorMapper;
actionMapper?: ActionMapper;
schemaValidatorMapper?: SchemaValidatorMapper;
omitWarnings?: boolean;
}
```
*object*
Form values as …
> Add ability to validate fields in the form schema separately 

- packages/carbon-component-mapper/src/select/select.js
- packages/carbon-component-mapper/src/tests/select.test.js
Creates an array with `undefined`.
`(Array.isArray(value) ? value : [value])` => `value = undefined` => `[undefined]` => 😢 
**Schema**
```jsx
schema={{
fields: [
{
name: 'multi',
isMulti: true,
options: [
{ label: 'cats', value: 'cats' },
{ label: 'dogs', value: 'dogs' }
]
}
]
}}
```
> fix(carbon): fix empty initial value in multi select

- packages/carbon-component-mapper/src/select/select.js
Fixes #https://github.com/data-driven-forms/react-forms/issues/1080
Carbon select omits `isMulti`
```jsx
{
component: "select",
name: "days",
label: "Days",
isMulti: true,
initialValue: [1, 2, 4],
options: [
{
value: 0,
label: "Sunday"
},
{
value: 1,
label: "Monday"
},
{
value: 2,
label: "Tuesday"
},
{
value: 3,
label: "Wedensday"
},
{
value: 4,
label: "Thursday"
},
{
value: 5,
label: "Friday"
},
{
value: 6,
label: "Saturday"
}
]
}
```
> fix(carbon): pass isMulti to ddf select

- packages/carbon-component-mapper/src/select/select.js
- packages/carbon-component-mapper/src/tests/select.test.js
- packages/common/src/select/select.js
- packages/common/src/tests/select/select.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/carbon/select.md
- packages/react-renderer-demo/src/doc-components/examples-texts/mui/select.md
- packages/react-renderer-demo/src/doc-components/examples-texts/pf4/select.md
- packages/react-renderer-demo/src/doc-components/examples-texts/select.md
- packages/react-renderer-demo/src/doc-components/examples-texts/suir/select.md
- Carbon select is now using the shared onChange function
- `selectAll: true` option selects all (except itself)
- `selectNone: true` option deselect all
**After**
**Schema**
```jsx
schema={{
fields: [
{
name: 'select',
isMulti: true,
simpleValue: true,
isSearchable: true,
options: [
{ label: 'Select all', selectAll: true, value: 'select-all' },
{ label: 'Select none', selectNone: true, value: 'select-none' },
{ label: 'Dogs', value: 'd' },
{ label: 'Cats', value: 'c' },
{ label: 'Hamsters', value: 'h' },
]
}
]
}} 
```
**Checklist:**
> Select all

- packages/carbon-component-mapper/src/checkbox/checkbox.js
- packages/carbon-component-mapper/src/tests/checkbox.test.js
Fixes see discord
An event is not passed as the first argument, but as the third one. And because it is type: checkbox, it causes issues.
```jsx
schema={{
fields: [
{
component: 'checkbox',
label: 'Checkbox',
name: 'checkbox',
options: [
{
label: 'Dog',
value: '1'
},
{
label: 'Cats',
value: '2'
},
{
label: 'Hamsters',
value: '3'
}
]
}
]
}}
```
> fix(carbon): fix multiple checkbox by correctly passing event

- packages/carbon-component-mapper/src/select/select.js
- packages/carbon-component-mapper/src/tests/select.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/carbon/select.md
Fixes see Discord
Adds an ability to group options in simple single select.
```jsx
{
name: 'select-with-categories',
label: 'With categories',
options: [
{
label: 'Category 1',
options: [
{ label: 'value 1', value: '111' },
{ label: 'value 2', value: '222' }
]
},
{
label: 'Category 2',
options: [
{ label: 'value 3', value: '333' },
{ label: 'value 4', value: '444' }
]
}
]
}
```
**After**
> feat(carbon): allow to group options in single select

- packages/mui-component-mapper/src/form-template/form-template.js
- packages/mui-component-mapper/src/tests/form-template.test.js
Part of https://github.com/data-driven-forms/react-forms/issues/923
Adds alert for form errors in MUI-mapper.
**Schema**
```jsx
validate={({something}) => {
if(something?.length > 3) {
return {[FormError]: 'too long'}
}
if(something) {
return {[FormError]: 'too short'}
}
return {}
}}
```
> feat(mui): add form error alert

- packages/react-renderer-demo/src/components/component-example.js
Adds button for expanding/hiding options in examples
**After**
> Add button for expanding/hiding options in examples

- packages/pf4-component-mapper/src/checkbox/multiple-choice-list.js
Pass the rest of option to a single checkbox in mutliple checkbox. Allows to disable just one option:
**Schema**
```jsx
schema={{
fields: [ {
"component": "checkbox",
"label": "Checkbox",
"name": "checkbox",
initialValue: ['1'],
"options": [
{
"label": "Dog",
"value": "1",
isDisabled: true
},
{
"label": "Cats",
"value": "2"
},
{
"label": "Hamsters",
"value": "3"
}
]
}]
}}
```
> fix(pf4): pass rest props to option in mutliple checkbox

- packages/react-form-renderer/src/tests/form-renderer/enhanced-on-change.test.js
- packages/react-form-renderer/src/use-field-api/enhanced-on-change.js
Fix #1109 
I found out that there is unexpected behavior for passed date objects. It will be handled as empty object in `checkEmpty` function. These is because of `isEmpty` function from **lodash** - it will return **true** for Date. https://github.com/lodash/lodash/issues/5131
> Fix wrong set of Date

- packages/pf4-component-mapper/src/select/select/option.css
- packages/pf4-component-mapper/src/select/select/option.js
- packages/pf4-component-mapper/src/tests/select/select.test.js
- packages/react-renderer-demo/src/doc-components/examples-texts/pf4/select.md
Fixes #1113 
Adds description to PF4 select options.
```jsx
options: [
{ value: 'value', label: 'Some label', description: 'Some description' }
]
```
> Add description to pf select

- package.json
- the message with demo was confusing
- updated list of packages
:tada: This ${issue.pull_request ? 'PR is included' : 'issue has been resolved'} in version ${nextRelease.version} :tada:
The release is available on
- [react-form-renderer (@latest dist-tag)](https://www.npmjs.com/package/@data-driven-forms/react-form-renderer)
- [ant-component-mapper (@latest dist-tag)](https://www.npmjs.com/package/@data-driven-forms/ant-component-mapper)
- [blueprint-component-mapper (@latest dist-tag)](https://www.npmjs.com/package/@data-driven-forms/blueprint-component-mapper)
- [carbon-component-mapper (@latest dist-tag)](https://www.npmjs.com/package/@data-driven-forms/carbon-component-mapper)
- [mui-component-mapper (@latest dist-tag)](https://www.npmjs.com/package/@data-driven-forms/mui-component-ma …
> Update bot message

- packages/common/src/select/select.js
- packages/common/src/tests/select/select.test.js
Fixes #1118 
**Schema** (try in PF4 mapper)
```jsx
schema={{
fields: [
{
label: 'Select',
name: 'select',
isSearchable: true,
options: [{label: '111', value: 1 }],
noValueUpdates: true,
simpleValue: true,
isClearable: true,
isMulti: true
}
]
}}
```
> fix(common): handle isMulti and null change

- packages/common/babel.config.js
- this is a preparation for switching to node 12+
- for some reason, node12 installs dependencies randomly in root folder/packages folder
- this PR ensures that transform-imports plugin checks both folders
> Check root and packages node_modules at the same time

- .circleci/config.yml
- README.md
- packages/ant-component-mapper/README.md
- packages/blueprint-component-mapper/README.md
- packages/carbon-component-mapper/README.md
- packages/carbon-component-mapper/src/tests/time-picker.test.js
- packages/common/README.md
- packages/mui-component-mapper/README.md
- packages/parsers/README.md
- packages/pf4-component-mapper/README.md
- packages/react-renderer-demo/README.md
- packages/react-renderer-demo/package.json
- packages/react-renderer-demo/src/pages/development-setup.md
- packages/suir-component-mapper/README.md
Fixes #929
Firebase now supports node14.
- updated development setup page
- better formatting
- requirements info
- reorganized and updated root readme
- updated packages readme (removed development setup from there)
> Switch to node14 and update documentation

- packages/ant-component-mapper/src/validation-error/validation-error.d.ts
- packages/mui-component-mapper/src/validation-error/validation-error.d.ts
- packages/react-form-renderer/src/component-types/component-types.d.ts
- packages/react-form-renderer/src/data-types/data-types.d.ts
- packages/react-form-renderer/src/validator-types/validator-types.d.ts
- scripts/generate-typings.js
Fixes #1165
Functions and constants had incorrect type name casing resulting in missing TS types when using named exports. For example:
```TS
// results in TS error that the module does not exist
import { useFieldApi } from '@data-driven-forms/react-form-renderer'
// the type was named but that function does not exist
import { UseFieldApi } from '@data-driven-forms/react-form-renderer'
```
- the default re-export name is based on the actual variable/function name instead of automatically converting everything to CamelCase. If the script is unable to extract the correct name, it will fall back to CamelCase conversion.
- fixed some invalid type definitions
- fix will release a …
> Update types generator to use correct variable/function names.

- packages/pf4-component-mapper/src/radio/radio.js
Options were taken from props, not from enhanced props, so `resolveProps` didn't work here.
> fix(pf4): use options from field hook

- package.json
- packages/ant-component-mapper/package.json
- packages/mui-component-mapper/package.json
- packages/pf4-component-mapper/package.json
- packages/suir-component-mapper/package.json
- scripts/update-common.js
- yarn.lock
We can replace common version in package.json using [`semantic-release/exec`](https://github.com/semantic-release/exec/tree/master/test) plugin. This will prevent issues with mismatched package versions as seen in Edge frontend.
This plugin takes the `nextVersion`, finds all `package.json`s in `packages/package/` folders and changes the `*` to the `nextVersion`.
I tested the script directly and it *worked*, but I wasn't able to test it in dry-run, I guess we have to just hope. @Hyperkid123 Please do not merge it when we are not online so if there is any issue, we can deprecate the wrong versions. 😄 
This step happens **after git commit** so the changes should not be committed to the repository.
> fix(common): update common version in package.json

- packages/react-form-renderer/src/get-condition-triggers/get-condition-triggers.js
- packages/react-form-renderer/src/tests/form-renderer/condition.test.js
`not` condition was totally missing from the new condition handler
```jsx
schema={{
fields: [
{ label: 'a', component: 'text-field', name: 'a' },
{ label: 'b-not', component: 'text-field', name: 'b', condition: { not: { when: 'a', is: 'cat' } } },
{ label: 'b-is', component: 'text-field', name: 'b', condition: { when: 'a', is: 'cat' } },
],
}}
```
> fix(renderer): fix NOT condition

- packages/ant-component-mapper/src/radio/radio.js
- packages/ant-component-mapper/src/tests/radio.test.js
Fixes #1207 
Ant radio does not behave as other radios, there is only one onChange on radio group. check [example](https://ant.design/components/radio/#components-radio-demo-radiogroup)
cc @PawanKolhe
> fix(ant): fix radio, make initial values work

- packages/react-form-renderer/src/wizard-context/wizard-context.d.ts
Updates the types for `currentStep` in Wizard Context. 
Resolves the following typescript errors:
```
Property 'fields' does not exist on type 'string'.ts(2339)
Property 'nextStep' does not exist on type 'string'.ts(2339)
```
- i.e. `Fix button on documenation …
> fix(types): update types for currentStep in Wizard

- packages/react-renderer-demo/src/components/code-editor/index.js
- packages/react-renderer-demo/src/components/code-example.js
- packages/react-renderer-demo/src/components/landing-page/landing-page-cards.js
- packages/react-renderer-demo/src/components/mdx/mdx-components.js
- packages/react-renderer-demo/src/pages/releases.js
1. Add border-radius:4 to index page example code and component to
achieve a better user experience.
2. Add border-radius:4 to all the code blocks in markdown.
3. Change the code block font to "ui-monospace,SFMono-Regular,SF
Mono,Menlo,Consolas,Liberation Mono,monospace"
4. Change the code block highlight theme to oceanicNext, modify the related
wrapper background color.
5. Move the AccordionSummary of the example component to the bottom of the
component, as it's more logical to expand the code below the actual
component.
6. Turn off the rotate of accordion expand icon, replace it with
<CodeIcon/> and <CodeOffIcon/> to maintain the expand state.
7. Replace the markdown default divider(<hr>) to @mui/material/Divider.
Please include a summary of the change.
**Schema** *(if …
> Improve the styles of the doc site

- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/condition/condition.js
- packages/react-form-renderer/src/tests/form-renderer/condition.test.js
Fixes #1224
Field initial value is being overridden if a set condition is met during initialization phase
```jsx
fields: [
{
name: 'field-1',
label: 'first name',
},
{
name: 'field-2',
label: 'last name',
},
{
name: 'field-3',
label: 'occupation',
condition: {
sequence: [
{
and: [
{ when: 'field-1', is: 'james' },
{ when: 'field-2', is: 'bond' },
],
then: { set: { 'field-3': 'SPY' } },
else: { visible: true },
},
{
and: [
{ when: 'field-1', is: 'steve' },
{ when: 'field-2', is: 'jobs' },
],
then: { set: { 'field-3': 'CEO' } },
else: { visible: true },
},
],
},
},
],
};
```
**Checklist:** *(please see [documentation …
> fix(renderer): Do not override initial values with set values.

- packages/react-form-renderer/src/form-renderer/form-renderer.d.ts
> fix(renderer): mark onSubmit and FormTemplate as optional props.

- packages/react-form-renderer/src/condition/condition.js
- packages/react-form-renderer/src/tests/form-renderer/condition.test.js
- packages/react-renderer-demo/src/pages/schema/condition-set.md
Fixes #1233 
- When a field is being unmounted (`meta == false`), we should finish the execution of condition setter.
- instead of field.modified we should check the entire form.modified as we do not know what fields are triggering the condition (there is a memoized setter result + fieldListeners, so that ensures that the setter is not triggered when anything else changes after the first render, but it only listens to the correct changes)
```jsx
fields: [
{
name: 'field1',
initialValue: 'B',
},
{
name: 'field2',
initialValue: 'schema initial value',
clearOnUnmount: true,
condition: {
when: 'field1',
is: 'B',
then: { set: { field2: 'set with then' } },
else: { set: { field2: 'set …
```
> fix(renderer): fix undefined meta in condition

- packages/react-form-renderer/src/form-renderer/form-renderer.js
- packages/react-form-renderer/src/renderer-context/renderer-context.d.ts
- packages/react-form-renderer/src/tests/form-renderer/form-renderer.test.js
- packages/react-renderer-demo/src/pages/components/children.md
- packages/react-renderer-demo/src/pages/hooks/use-form-api.md
Fixes #1236
Add additional options to render children in form renderer
- allow passing `null` as a child
- only permit one root child element
- use `schema` and `formFields` if explicitly given to renderer child
- expose schema in `formOptions`
- i.e. `Fix …
> Update children rendering

- .circleci/config.yml
- README.md
- packages/react-renderer-demo/package.json
- packages/react-renderer-demo/src/pages/development-setup.md
See https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version
> Update Node to version 16

- packages/form-state-manager/src/manager-api/manager-api.ts
When one field is dirty, then the whole form is dirty too - so we do not have to check the other fields.
> fix(manager): when one field is dirty, whole form is dirty

- packages/common/src/dual-list-select/dual-list-select.js
Fixes hanging remove button is enabled even if no option is selected
Fixed dual list select action dispatch typo
https://codesandbox.io/s/modal-multiselect-forked-7w9yl7?file=/src/index.js
How to produce:
1. select one option and add it to the right
2. click on the option in the right column but make no other action
3. Click on the Remove all button
The remove button stays enabled (as if the option was still selected)
The button should be disabled
> fix(common): Fix clear all right values dual list action type typo

- packages/common/src/wizard/select-next.d.ts
- Extends the `NextStep` type to allow specifying an async function that resolves with the string of the next page
- Updates the `selectNext` type to indicate it returns the result of any `NextStep` function provided to it
- Adjusts the `NextStep` function parameter type to match current implementation
I've listed as a `fix` because this is just a type change, but can list as a `feat` if anybody is concerned about breaking existing types.
I didn't update documentation as I'm not sure if you wanted to have this be mentioned in the standard `Wizard` docs since it's not supported by anything other than custom wizards.
- format `fix|feat({scope}): …
> NextStep and selectNext async typing updates

- packages/pf4-component-mapper/src/wizard/wizard-components/step-buttons.js
- packages/pf4-component-mapper/src/wizard/wizard-components/wizard-step.js
- packages/pf4-component-mapper/src/wizard/wizard.js
Removed isRequired from conditionalSubmitFlag because it caused unnecessary  warnings.
@Hyperkid123
> Remove isRequired from conditionalSubmitFlag

- packages/react-renderer-demo/src/components/navigation/schemas/custom-examples.schema.js
- packages/react-renderer-demo/src/pages/examples/custom-component-mapper.md
Adds a custom mapper example to examples section so people can easily find it.
> Just add a link to custom component mapper to examples

- packages/carbon-component-mapper/src/dual-list-select/dual-list-select.js
- packages/common/babel.config.js
- packages/mui-component-mapper/src/date-picker/date-picker.d.ts
- yarn.lock
There are import path changes in minor releases. Using absolute imports
will cause backwads compatibility issues.
Fixes #1298
> fix(carbon): do not use absolute import paths

- package.json
- packages/react-form-renderer/src/tests/form-renderer/data-types.test.js
- packages/react-form-renderer/src/use-field-api/convert-type.js
When typing a "." in a field having dataType as "float", the input is ignored and due to which user is never able to type a decimal value even if the type is set to "float". 
Reason: The canBeConvertedToNumber functions returns true for values like "11.", but the parseFloat functions returns "11" only and thus removing the decimal.
Issue is replicated at https://stackblitz.com/edit/1dkk8s?file=schema.js
> Float Issue fix

- packages/react-renderer-demo/src/components/navigation/schemas/schema.js
- packages/react-renderer-demo/src/pages/404.js
Fixes https://github.com/data-driven-forms/react-forms/discussions/1337
Redirects the old live-editor to the new version of it.
> Remove live-editor link and redirect old page to new page

- scripts/clean-build.js
When demo is built, a dist folder with empty package.json is created. Let's remove this folder to prevent mismatch error:
> Remove demo/dist folder on clean-build

- packages/ant-component-mapper/src/date-picker/date-picker.js
- packages/ant-component-mapper/src/form-group/form-group.js
- packages/ant-component-mapper/src/select/select.js
- packages/ant-component-mapper/src/slider/slider.js
- packages/ant-component-mapper/src/switch/switch.js
- packages/ant-component-mapper/src/text-field/text-field.js
- packages/ant-component-mapper/src/textarea/textarea.js
- packages/ant-component-mapper/src/time-picker/time-picker.js
Fixes #1356 
- form.item name includes Ant form functionality we do not want to initialize
> fix(ant): use htmlFor and id instead of Form.item name

- packages/pf4-component-mapper/src/wizard/wizard.js
Fix the problem with Escape button on wizard in the modal. Now Escape normally works after clicking outside the modal window/text area and clicking back on modal.
@Hyperkid123
> Fix problem with ESC button on wizard in modal

- packages/react-form-renderer/src/common-types/field.d.ts
- packages/react-form-renderer/src/form-renderer/form-renderer.d.ts
- packages/react-form-renderer/src/renderer-context/renderer-context.d.ts
- packages/react-form-renderer/src/use-form-api/use-form-api.d.ts
At this moment there is support for Typescript but not every component/hook is using Typescript generics. This PR adds generic typings for the Field type, FormRenderer component and for some hooks(useForm, useFieldApi).
**Examples**
- i.e. `Fix button on …
> fix: better generic types for field, FormRenderer and hooks

- packages/react-form-renderer/src/common-types/index.d.ts
- packages/react-form-renderer/src/common-types/no-index.d.ts
- packages/react-form-renderer/src/form-renderer/form-renderer.d.ts
Final-form-api is using FormProps with `[otherProp: string]: any;`. If you then use Omit it will resolve in `[otherProp: string]: any;` and all other types will not be visible anymore.
[Typescript playground](https://www.typescriptlang.org/play?ts=5.0.2#code/JYWwDg9gTgLgBAbwGLRABShMBnAvnAM0xDgCIoBTAQwGMYBaA4AOyoBtHVSAobmATzAU4AOQgBJZgBMKADwA8AFQB8cALyJucOAG0A0nBZwA1hX4QCcRXCrZE+OTArS7AJQo1oU+XoA0cAEZVAH44ZgoANwooOAAuOD0AXXjFfUTuXF4BITgAeRBgGAB1QoALCABXGDFJGQVtFCgQADV2Coo7DXdPKG9sGCgWAHN-KmZ+ZV9JQuB2Rpa2jvU4NCpYWbZ5eda2duxlVQ18wq3UDCxsU6advf9pmA3txf3-UghmAGUKgCMCmFJlNwAPRA7TaAB6wV4fEEwmOxTKNWkcnkDVQNyWXQ8Xnk-UGzBGNnGk3uj3Rz2Wq3W7CuC12HQOy3h8iRdVp5xwtIx2DuzBmc3J9P2kzI7y+v0KAOBoLBkO4QA)
By using `NoIndex` we can exclude `[otherProp: string]: any;` and have all the types that …
> fix(TS): no-index type to exclude [otherProp: string]: any;

- packages/react-form-renderer/src/form-renderer/render-form.js
- packages/react-form-renderer/src/tests/form-renderer/condition.test.js
Fixes https://discord.com/channels/682555108932059173/682555109447565356/1095312333707948162
Currently, it wasn't possible to generate `condition` via the action mapper
```jsx
actionMapper = {
fieldArrayCondition: (condition) => ({
...condition,
when: ({ name }) => name.replace('lastName', 'name'),
}),
}
schema = {
fields: [
{
component: 'field-array',
name: 'nicePeople',
label: 'Nice people',
fields: [
{
name: 'name',
label: 'Select',
initialValue: 'hide',
options: [
{ label: 'show', value: 'show' },
{ label: 'hide', value: 'hide' },
],
},
{
name: 'lastName',
label: 'Last Name',
actions: {
condition: ['fieldArrayCondition', { is: 'show' }],
},
},
],
},
],
};
```
> Always use overriden props

- packages/react-form-renderer/src/tests/validators/validators.test.js
- packages/react-form-renderer/src/validators/validator-functions.js
Currently the numeric validators (min or max) doesn't shows any validation error if the value in the field is zero.
Scenario:
If a field is added with min validation with threshold as 3, the validator will show error for values like 1,2,-1 etc but nothing for 0.
> Fix numeric validator

- packages/react-form-renderer/src/tests/validators/validators.test.js
- packages/react-form-renderer/src/validators/validator-functions.js
Currently if have a validation (ex: minimum) on a numeric field and the value is not a number then it shows the data type wrong message (Value must be an integer) and if the type is correct then it shows the correct message (Value must be greater or equal.....). But when we are passing a custom validation message, then the data type message is not displayed and in that case also the custom message is shown.
> Fix data type validation message for numeric validator in case of custom message

- packages/react-form-renderer/demo/form-fields-mapper.js
- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/condition/condition.js
- packages/react-form-renderer/src/tests/form-renderer/initial-values-condition-schema.json
- packages/react-form-renderer/src/tests/form-renderer/render-form.test.js
Fixes #1383
The input of type `radio` does not trigger the condition after `re-mount` if the condition is based on `initialValues` renderer prop.
Issue is with the `values` that are collected from all the triggers. Because the `radio` type is registered multiple times, per each option, the `useField` does not `yield` the actual state value immediately. Therefore we have to use the `getState().values` to retrieve the state values and pass it to the condition parser instead of the smaller, `values` collected from the triggers. 
To reproduce the issue, use the following schema with initial values. Select `form1` from the top radio component, and then `reselect` the `form2` option.
Without the fix the `Radio1` text field will not be visible, even though the values for the …
> fix(renderer): nested condition based on form initial values

- packages/react-renderer-demo/src/stackblitz-templates/mui-templates.js
specify stackblitz dependency on `@mui/x-date-pickers` for latest release of major version 5 instead of using `latest` which used incompatible version 6
> Fix mui date picker and time picker examples

- packages/react-form-renderer/src/use-field-api/compose-validators.d.ts
- packages/react-form-renderer/src/use-field-api/compose-validators.js
- packages/react-form-renderer/src/use-field-api/use-field-api.js
This file is duplicated (already in `packages/react-form-renderer/src/compose-validators`)
> fix(renderer): remove duplicated file

- packages/mui-component-mapper/package.json
- packages/mui-component-mapper/src/date-picker/date-picker.js
- packages/mui-component-mapper/src/time-picker/time-picker.js
- yarn.lock
Resolves issues with duplicate dependencies on yarn and relaxes the restriction of the package version.
Fixes: #1409
> fix(mui): Move date pickers to peer dependencies.

- packages/common/src/select/deep-equal.d.ts
- packages/common/src/select/deep-equal.js
- packages/common/src/select/select.d.ts
- packages/common/src/select/select.js
- packages/common/src/tests/select/deep-equal.test.js
- packages/common/src/tests/select/select.test.js
- packages/common/src/use-select/reducer.js
- packages/common/src/use-select/use-select.d.ts
- packages/common/src/use-select/use-select.js
- packages/pf4-component-mapper/demo/demo-schemas/select-schema.js
- packages/react-renderer-demo/src/doc-components/examples-texts/select.md
- packages/react-renderer-demo/src/pages/provided-mappers/component-api.md
Fixes #1401
```jsx
const loadOptions = (searchValue = '') => {
return getGroups({ name: searchValue }).then((data) => {
return data.results.map(({ name, id }) => ({
label: name,
value: { id, name },
}));
});
};
const exampleSchema = (hosts) => ({
fields: [
{
name: 'group',
label: 'Select a group',
simpleValue: true,
isSearchable: true, // enables typeahead
isRequired: true,
isClearable: true,
placeholder: 'Type or click to select a group',
loadOptions,
options: [],
validate: [{ type: validatorTypes.REQUIRED }],
}
],
});
```
- i.e. `fix(pf3): wizard correctly …
> Add compareValues prop to useSelect's reducer

- packages/pf4-component-mapper/src/wizard/wizard-components/wizard-nav.js
In Patternfly 4, the WizardNavItem component `step` prop is "the step passed into the onNavItemClick callback".
http://v4-archive.patternfly.org/v4/components/wizard#wizardnavitem
In Patternfly 5, onNavItemClick no longer exists. Instead, there is an onClick callback which expects the index of the step to be navigated to.
https://www.patternfly.org/components/wizard/#wizardnavitem
However, filtering the navSchema like so: `.filter((field) =>
field.primary)` results in substeps with field.primary===false being dropped. Practically, this means the 2nd substep and those following it. Therefore, the index provided by `.map((step, ind) => ...` is incorrect.
The correct index can still be found from `step.index`.
We first encountered a bug related to this while upgrading our app to PF5, see the …
> fix(pf4): fix bug in wizard navigation toolbar

- packages/pf4-component-mapper/src/wizard/wizard-components/wizard-nav.js
In the Image Builder wizard we are no longer seeing step numbers with the pf5 upgrade.
The wizard navigation should only contain one WizardNav component. Wrapping the WizardNavItems in two WizardNav components is causing all steps to be treated as substeps and therefore don't have step numbers. The fix is to remove one of the WizardNav wrappers.
The other WizardNav component is here: https://github.com/data-driven-forms/react-forms/blob/baaf60020a972b51d01ef7722cb91ab66297dc98/packages/pf4-component-mapper/src/wizard/wizard.js#L129
And here is a screenshot of the issue.
> fix(pf): bug in wizard navbar

- packages/mui-component-mapper/src/date-picker/date-picker.js
- packages/mui-component-mapper/src/time-picker/time-picker.js
onBlur and onFocus weren't called for MUIDatePicker and MUITimePicker. Can be tested in the mui playground. Required validation won't be displayed without these changes because meta.touched never gets set.
```jsx
```
- i.e. `Fix …
> fix(mui): Correctly use onBlur and onFocus for MUIDatePicker and MUITimePicker

- packages/react-form-renderer/src/parse-condition/parse-condition.js
- packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js
Fixes #1422
`field` is not passed to inner sequence and not conditions
> fix(renderer): pass field property to when in sequence and not

- packages/react-form-renderer/demo/index.js
- packages/react-form-renderer/src/condition/condition.d.ts
- packages/react-form-renderer/src/condition/condition.js
- packages/react-form-renderer/src/default-schema-validator/default-schema-validator.js
- packages/react-form-renderer/src/form-renderer/condition-mapper.d.ts
- packages/react-form-renderer/src/form-renderer/form-renderer.d.ts
- packages/react-form-renderer/src/form-renderer/form-renderer.js
- packages/react-form-renderer/src/parse-condition/parse-condition.d.ts
- packages/react-form-renderer/src/parse-condition/parse-condition.js
- packages/react-form-renderer/src/renderer-context/renderer-context.d.ts
- packages/react-form-renderer/src/tests/form-renderer/parse-condition.test.js
- packages/react-form-renderer/src/tests/parsers/default-schema-validator.test.js
- packages/react-renderer-demo/src/components/navigation/schemas/mappers.schema.js
- packages/react-renderer-demo/src/examples/components/condition-mapper.js
- packages/react-renderer-demo/src/pages/components/renderer.md
- packages/react-renderer-demo/src/pages/mappers/condition-mapper.md
> feat(renderer): allow condition mapping

- packages/pf4-component-mapper/src/date-picker/date-picker.js
- packages/pf4-component-mapper/src/time-picker/time-picker.js
Fixes #1432 
Fix the order of the pickers attributes sent to the change callback
> fix(pf4): fix date and time picker change attributes order

- packages/react-renderer-demo/src/pages/mappers/custom-mapper.md
> Fix fielprovider typo

- packages/common/src/select/select.js
- packages/common/src/use-select/reducer.js
- packages/common/src/use-select/use-select.js
Fixes #1448 
- default options prop resetting select state if not cached
- `compareValues` included in select promises payload
- select updateOptions dispatch triggering on with same options
> Common select fixes

- packages/react-renderer-demo/src/stackblitz-templates/ant-templates.js
Fixes #1451
Examples were using v5 while the mapper is built with v4 in mind
> Pin antd packages docs version to 4.x

- packages/react-renderer-demo/src/examples/components/examples/value-listener.js
- packages/react-renderer-demo/src/pages/examples/value-listener.md
> Fix documentation typo

- packages/mui-component-mapper/src/multiple-choice-list/multiple-choice-list.js
On `multiselect` `initialValue` was passed to the span element resulting in console errors.
- [✅] `Yarn build` passes
- [✅] `Yarn lint` passes
- [✅] `Yarn test` passes
- [✅] Correct commit message
> fix(mui): added initialValue to the list of excluded props

- packages/pf4-component-mapper/src/wizard/wizard-components/wizard-step.js
In the new PF5 wizard, the prop to disable body padding is called `hasNoPadding` rather than `hasNoBodyPadding`.
> fix(pf4): Use PF5 name for WizardBody no padding

- packages/react-form-renderer/src/tests/validators/validators.test.js
- packages/react-form-renderer/src/validators/validator-functions.js
Fixes #1484
When passing a falsy numeric value to the "is required" validator, the validator would report an error.  These changes properly handle this case.
> Updated the required validator to properly handle falsy numeric values

- packages/pf4-component-mapper/src/checkbox/multiple-choice-list.js
Fixes #1493  
Changed order of the onChange params to fix checkbox filters toggle
```jsx
export default {
"fields": [
{
"component": "checkbox",
"label": "Checkbox",
"name": "checkbox",
"options": [
{
"label": "Dog",
"value": "1"
},
{
"label": "Cats",
"value": "2"
},
{
"label": "Hamsters",
"value": "3"
}
]
}
]
};
```
- [-] Test coverage for new code *(if applicable)*
- [-] Documentation update *(if applicable)*
- feat will release a new \_.X.\_ version (use when you introduce new …
> fix: fix multiple choices checkbox component

- packages/ant-component-mapper/LICENSE
- packages/blueprint-component-mapper/LICENSE
- packages/carbon-component-mapper/LICENSE
- packages/common/LICENSE
- packages/mui-component-mapper/LICENSE
- packages/parsers/LICENSE
- packages/pf4-component-mapper/LICENSE
- packages/react-form-renderer/LICENSE
- packages/suir-component-mapper/LICENSE
Went in and manually removed the symlink for the Licenses file.
I am not sure if this will get it copied over down to npm.
```jsx
```
> Remove symlink for licenses in packages

- packages/common/babel.config.js
- packages/common/config/webpack.config.js
- packages/pf4-component-mapper/src/wizard/wizard-components/step-buttons.js
Fixes the button's layout and spacing.
> fix(pf4): wix wizard buttons layout
